{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.2-0.1.2.jar",
          "url": "numen-api-common-1.20.2-0.1.2.jar",
          "size": 536639,
          "sha512": "74fc25ebb5f6d3d7df84cbba1623d57248a650e79cc7b36d2b8a1f270afec2e82f97764aad729852c068b091b1404ada44138137019c82dcd48250b6a64efe9a",
          "sha256": "0bd80a9ad997b899c98c4e47565c739f4bcd3af6a981c5631e1aebaabbbe237f",
          "sha1": "88dd6ac918d42e42bf6196517735ef3b250c5ef2",
          "md5": "1ed1cde1770c6bae86e1488c78691542"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.2-0.1.2.jar",
          "url": "numen-api-common-1.20.2-0.1.2.jar",
          "size": 536639,
          "sha512": "74fc25ebb5f6d3d7df84cbba1623d57248a650e79cc7b36d2b8a1f270afec2e82f97764aad729852c068b091b1404ada44138137019c82dcd48250b6a64efe9a",
          "sha256": "0bd80a9ad997b899c98c4e47565c739f4bcd3af6a981c5631e1aebaabbbe237f",
          "sha1": "88dd6ac918d42e42bf6196517735ef3b250c5ef2",
          "md5": "1ed1cde1770c6bae86e1488c78691542"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.2-0.1.2-sources.jar",
          "url": "numen-api-common-1.20.2-0.1.2-sources.jar",
          "size": 496888,
          "sha512": "66e73482e2450a6dd72766e5e2eed88cf94f28e973275b842deb36ab20cc3b89c00076d4d3149228e3b28731fed8ce123287ae9eb4d2361393fc7a5a4640523a",
          "sha256": "1943b43d98abcbd95d6d7df50efbea2e58f80456ab556d9447cb1bea22dc797c",
          "sha1": "60515647244f1287643edf3a68e70b1801b0903e",
          "md5": "a163a155c3abd197cd042e205b1d8d07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-api-common-1.20.2-0.1.2-javadoc.jar",
          "size": 687917,
          "sha512": "c6e5201857196cf302a2bb1f66e65dc769e9f33bf9d1b2ca6adc2e10648ddf6bb74f1aa241f1b3377adef10cf09e853549928e9c180971f931a2e99128a6f870",
          "sha256": "a88f24f30fbe4ff3216b5a551a929353a02067fc0afa04fdb4552deaa8ddbc3b",
          "sha1": "4ed87361a7fb1bbe8311e2dc4a81ccaa62eab4f8",
          "md5": "9ce2ea0631280106f444ba000d308842"
        }
      ]
    }
  ]
}
