{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT.jar",
          "size": 907732,
          "sha512": "5731205519d1f446423229e6961562e8df8551737cea37e073a6a46c1f39ad7e23eee8d5851a8247ed540534c2ed2d184adc75db38c1fb4a124bd9d895e49e5b",
          "sha256": "902b4a9373bb89c8fd14a213faa026c35de48a44619e8ea0d60c9a77be727c7d",
          "sha1": "0894ea77e4d2c6fd505b17fb7827e21676cc958a",
          "md5": "5f394667810271e09398953b5554704c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT.jar",
          "size": 907732,
          "sha512": "5731205519d1f446423229e6961562e8df8551737cea37e073a6a46c1f39ad7e23eee8d5851a8247ed540534c2ed2d184adc75db38c1fb4a124bd9d895e49e5b",
          "sha256": "902b4a9373bb89c8fd14a213faa026c35de48a44619e8ea0d60c9a77be727c7d",
          "sha1": "0894ea77e4d2c6fd505b17fb7827e21676cc958a",
          "md5": "5f394667810271e09398953b5554704c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT-sources.jar",
          "size": 729383,
          "sha512": "601d53c3434d517a71541948eadd60d1b3521bb91789a1b70039c9954d9732b7068c1934559d478407d03348c67edd9c1d83f8e86b8c856be5bcdebe47347607",
          "sha256": "7f5d357af09cdff8e863070d8fa8c606faff3951c7b0dbb831cff32a9ace7945",
          "sha1": "3dca5a1515da2ce1b16247c2daa009f5b2056acc",
          "md5": "dca61a84e4b5b9bfc858a8b84e96120a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
