{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.1-0.1.2.jar",
          "size": 1339603,
          "sha512": "3e09cec46e9434becb08838d3850fcb2fe9bdf8712d74fbacb015430131fe75c8af7a01aa141c169b524a95140fc54675da00e27e788b067aa8d49f565f903a8",
          "sha256": "7dabe194b0ca5d313a82dfb9e0b745936bee67cce4e63fdaff7d6a297656ba37",
          "sha1": "d35681f305e1d9fe8ef2702e25a5669053669753",
          "md5": "0733c88c5b250dd7a392ad13fe62e97a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.1-0.1.2.jar",
          "size": 1339603,
          "sha512": "3e09cec46e9434becb08838d3850fcb2fe9bdf8712d74fbacb015430131fe75c8af7a01aa141c169b524a95140fc54675da00e27e788b067aa8d49f565f903a8",
          "sha256": "7dabe194b0ca5d313a82dfb9e0b745936bee67cce4e63fdaff7d6a297656ba37",
          "sha1": "d35681f305e1d9fe8ef2702e25a5669053669753",
          "md5": "0733c88c5b250dd7a392ad13fe62e97a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21.1-0.1.2-sources.jar",
          "size": 1065327,
          "sha512": "ad90de7802cfe87e51d609d32ad84b6de07649be6552eeb711a2c6d9581fc273379121fd3273ff2dfd7a36cdcc419d2dff13f141cd3a7d5c07f42d57a645b2f7",
          "sha256": "bfb9bfef161792c3ed45133e4fb44e6a7b7642d3d38c82d30da7dcdedd237262",
          "sha1": "b1da64adfa9674adc3c7475bc9fe486a2925a4ef",
          "md5": "b1727ed3c3c8b07ca487335d5a987f31"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.1-0.1.2-javadoc.jar",
          "size": 1564717,
          "sha512": "42fddc16a5a11fc7db79c636005a1fd168e64909548ac3bd60bdea89ff5433c27c5f782fd86ab3b28f48fd46c35f002d94e1647d7e1d2dc5d5fb7ce7135c9088",
          "sha256": "0514e40dc57fb43fa6f32bb291f7d2e67e8776865023e1212829415fa3dcd0ac",
          "sha1": "b4a140bc696214102203292e0b81cacb138ec516",
          "md5": "576070b1fd516adeea878ab07e106cff"
        }
      ]
    }
  ]
}
