{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.4",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.3.jar",
          "url": "numen-api-fabric-1.20.4-0.1.3.jar",
          "size": 1353113,
          "sha512": "c108c2d47c0461fa6db0393bdb8517eecc8e39fe3439620195a00556b0b179d1a0fb2e61cdf64ba5d22e44f6c01026cb6ef0e85a43ceb1c5409334e364dd9e4b",
          "sha256": "5caf918cbbc6085a6f04ce24d4f51cb028ccd3f86461a30708527290fe125043",
          "sha1": "d94efa97d125979de9bc73e38d270ff0dd682119",
          "md5": "29caa61edd989d1528891b96c1d6dec4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.3.jar",
          "url": "numen-api-fabric-1.20.4-0.1.3.jar",
          "size": 1353113,
          "sha512": "c108c2d47c0461fa6db0393bdb8517eecc8e39fe3439620195a00556b0b179d1a0fb2e61cdf64ba5d22e44f6c01026cb6ef0e85a43ceb1c5409334e364dd9e4b",
          "sha256": "5caf918cbbc6085a6f04ce24d4f51cb028ccd3f86461a30708527290fe125043",
          "sha1": "d94efa97d125979de9bc73e38d270ff0dd682119",
          "md5": "29caa61edd989d1528891b96c1d6dec4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.3-sources.jar",
          "url": "numen-api-fabric-1.20.4-0.1.3-sources.jar",
          "size": 1104325,
          "sha512": "e03eeca5f99ce6bdd92251bf0c69a0cad2e12b19e7c2d74b3f65f36740978911dc18b336f0faa9fb45c9ea771b748c61bfda42f690e307138b69e7e6858a11b5",
          "sha256": "97d25fb819d25fdc30d1fe3986c5d0d912d8b9991ea3b5acaa8e13c2e529e2a6",
          "sha1": "478dd1a51d12ff1cf8891ce7ecbcbd06c0852a5a",
          "md5": "0cde545c1b5e105a5176611b9db5db37"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.3-javadoc.jar",
          "url": "numen-api-fabric-1.20.4-0.1.3-javadoc.jar",
          "size": 1563777,
          "sha512": "be19ca8be917fc7be98fec4a7288ccb98fbb398d47cccc240650b8caf9250256817b1d8c84366b95030cfe855e506ec16464b2ed2f6cc37a0dd369033ac5aa4e",
          "sha256": "636363c6f46dba0dbab1e6d74179f7117be740cc86b5538c25a2a6b65eca54cd",
          "sha1": "5a1043d5d8318ee06d331cf3912befd4d057993f",
          "md5": "36bc78d6b3409db366cc7f30d2ab55c1"
        }
      ]
    }
  ]
}
