{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.1",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "size": 833399,
          "sha512": "32a2e4901a09529e338e94e9654b047245ffde526e828c4316b76e405adebad92e12e848da6799c9c317620d5c88ce837610696f98189fe7f117889093fba699",
          "sha256": "e12d78d41349e6f1733e61ea11130bd802bf9c06b5c97552682459c2b77bf145",
          "sha1": "e40771f09e35a9de003b344d4e41f0b705eba757",
          "md5": "fd133cbc10d6b4effb63983eb0c13c04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "size": 833399,
          "sha512": "32a2e4901a09529e338e94e9654b047245ffde526e828c4316b76e405adebad92e12e848da6799c9c317620d5c88ce837610696f98189fe7f117889093fba699",
          "sha256": "e12d78d41349e6f1733e61ea11130bd802bf9c06b5c97552682459c2b77bf145",
          "sha1": "e40771f09e35a9de003b344d4e41f0b705eba757",
          "md5": "fd133cbc10d6b4effb63983eb0c13c04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-sources.jar",
          "size": 680510,
          "sha512": "013b448a3693169b7b3b60886d3a477514f32681779cc6eb651c2395bd48e9e3bc7dd8c0fc22338f2465b0112b712ad67a1e06643db0be832d48e0884fa05143",
          "sha256": "8b8f54c707ac9caae2ce001de75c4b6969e49731cb4ccf44df125746268842ca",
          "sha1": "0a23aeeb2258a013d21943666f1de818aaaadfe2",
          "md5": "847b7314a2bd9acf2c1ed677fdc58493"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 1127892,
          "sha512": "04bd566f296fef1db49c1530665d399f2e01239127d356290495363ce4207f16e35608d76ed99e9f17c3fa1dd8908811e06f446c91a21118a293b181e5df4661",
          "sha256": "98ebb6783a5924d1887728107bb5f58934b512366bf4bf39540a9e4b95faeff1",
          "sha1": "d5823a4a4546e87b319cb39e2bc24aca34c6f7d1",
          "md5": "a9a08a0ade05dd60b12b1c1fffab5cbd"
        }
      ]
    }
  ]
}
