{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.1",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "size": 854429,
          "sha512": "349fa586ca80e9e75f86710ac02c066b387c573328da4bc18d6552d56fca313005ee0b5ccc510a67ece42d37a0c4855adf5ef2f206a868df21d02b530d357bad",
          "sha256": "d7d1297c88117c6ce236ad3aed325c57d585d52988de03bd466229e43fe2104b",
          "sha1": "4b40201feffbdd22ff62fde4b40296ad039fc205",
          "md5": "f8602999e5374c0e365978ed85423572"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT.jar",
          "size": 854429,
          "sha512": "349fa586ca80e9e75f86710ac02c066b387c573328da4bc18d6552d56fca313005ee0b5ccc510a67ece42d37a0c4855adf5ef2f206a868df21d02b530d357bad",
          "sha256": "d7d1297c88117c6ce236ad3aed325c57d585d52988de03bd466229e43fe2104b",
          "sha1": "4b40201feffbdd22ff62fde4b40296ad039fc205",
          "md5": "f8602999e5374c0e365978ed85423572"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-sources.jar",
          "size": 694131,
          "sha512": "b79573033003b93df8c176e984b500b17150e955bb6ea112579bcd2ef705b302258513e2a7957bbcd98c130166a1be8df0a8940bcb24b9ae02a5357856093bdd",
          "sha256": "88421f25d069b27fb62cc98f74f83e46646e7bfb0b2959e551582859441cd2bb",
          "sha1": "fe559cb09039ec7ba7d6afec2b0346988d688d50",
          "md5": "ddf600b4f8068013714ceec39cb1964e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 1127892,
          "sha512": "04bd566f296fef1db49c1530665d399f2e01239127d356290495363ce4207f16e35608d76ed99e9f17c3fa1dd8908811e06f446c91a21118a293b181e5df4661",
          "sha256": "98ebb6783a5924d1887728107bb5f58934b512366bf4bf39540a9e4b95faeff1",
          "sha1": "d5823a4a4546e87b319cb39e2bc24aca34c6f7d1",
          "md5": "a9a08a0ade05dd60b12b1c1fffab5cbd"
        }
      ]
    }
  ]
}
