{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-26.1.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-26.1.2-0.1.2.jar",
          "url": "numen-fabric-26.1.2-0.1.2.jar",
          "size": 2488632,
          "sha512": "ef94a7ac6119855cec456da9bbdf4b2d640414d796731024733d5b444f02e427a6382b45af2dc7b7a835f200622b325005db0b435a5990c5fa01ba938d29895a",
          "sha256": "40f59f9415dec6d954111a54853731d823424c6abf9c204ebcbf23d288574b08",
          "sha1": "a208f9d0cfb49bd4a96407ed53119551793c21fb",
          "md5": "1f3637e3b7f08348678e5533cea48d6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.148.2+26.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-26.1.2-0.1.2.jar",
          "url": "numen-fabric-26.1.2-0.1.2.jar",
          "size": 2488632,
          "sha512": "ef94a7ac6119855cec456da9bbdf4b2d640414d796731024733d5b444f02e427a6382b45af2dc7b7a835f200622b325005db0b435a5990c5fa01ba938d29895a",
          "sha256": "40f59f9415dec6d954111a54853731d823424c6abf9c204ebcbf23d288574b08",
          "sha1": "a208f9d0cfb49bd4a96407ed53119551793c21fb",
          "md5": "1f3637e3b7f08348678e5533cea48d6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-26.1.2-0.1.2-sources.jar",
          "url": "numen-fabric-26.1.2-0.1.2-sources.jar",
          "size": 1011255,
          "sha512": "1690f594bc1ede5ee65835315d481af811c35f0c09ef5bfbad1af893a75dcd8eb7ee22faedfb2fcc851d1c6c63d60fd8b88af2503af223d6ce0540d4a809da2c",
          "sha256": "9d3b4b3067c96663fe89f0d2675c60ca1d0bbc236051f57fd395226e1c827434",
          "sha1": "07e527421fe61dbeed2872925a52ed3eee5449e2",
          "md5": "281f6105dcf93487edb212ea5e6a1f89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-26.1.2-0.1.2-javadoc.jar",
          "url": "numen-fabric-26.1.2-0.1.2-javadoc.jar",
          "size": 5606595,
          "sha512": "ce502cb8edbd94dcc06e3bcf8b1cf3d9cbe207f4f075053070aaad56c605ac16afb55887625bc2e69c9c7340251556cd15cfc1324ff60ad693431956be9dfdae",
          "sha256": "a85adfb7f0a14bda767053b9a666b2c71ada1953cbb7cddb98a8e83c6855fae0",
          "sha1": "1c155ebeb950564006ad90a69635cf890c4ac036",
          "md5": "2bae3aaa3b58f266713a4f98684c64e3"
        }
      ]
    }
  ]
}
