{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.11",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT.jar",
          "size": 542527,
          "sha512": "c60b23143b5b53f60b1d039250b6098f43e9c373f394e2205a47ef57b35be4a8b0c71953f484d7153b23c4eaab9d3c4d0c0f50ab97072b804b4a1d7e60275fae",
          "sha256": "26e9d379e1ad4485040404ec3f6cf683a848c8f7f96ecb9df4c2b1952d1d70e6",
          "sha1": "dcc816446a541a6773be059b35381d22e359a1b3",
          "md5": "0e6bf7a0a126adbfc7ed4f5763aace12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.5+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT.jar",
          "size": 542527,
          "sha512": "c60b23143b5b53f60b1d039250b6098f43e9c373f394e2205a47ef57b35be4a8b0c71953f484d7153b23c4eaab9d3c4d0c0f50ab97072b804b4a1d7e60275fae",
          "sha256": "26e9d379e1ad4485040404ec3f6cf683a848c8f7f96ecb9df4c2b1952d1d70e6",
          "sha1": "dcc816446a541a6773be059b35381d22e359a1b3",
          "md5": "0e6bf7a0a126adbfc7ed4f5763aace12"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT-sources.jar",
          "size": 464129,
          "sha512": "95226375e4499294254f17186e02a92dc5dce194716d26e371f748968909092929c5e1362f4bb2e66b69c0ee44d9af4974b373433cc52dc202307429d848c6d5",
          "sha256": "791f888dd5db5a033b3dd46ad42d3ecf0001f474e0994447d9b49e66cc76e453",
          "sha1": "a87d73f5b42abfede2b7f8c6c9a3661336c17050",
          "md5": "14a005e23b9feaeadb5d19a5d0c7b103"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.11-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 694088,
          "sha512": "ab3fcd002c68fa63cf9b6cf03f69afb4791901dafc685309f4a441c2042eae9dfb208473c1385f14396e28490eddbaede6236df5d1dedec80893065bd0e743c7",
          "sha256": "300b23820105eb588dec4166a7cada0df86ea9c1ee88279f9db62a6d60e53d92",
          "sha1": "33d508fc0792519ad56658f340fe4e6a30021fd6",
          "md5": "b1ac0db9284ef3558f43d0bc733efca9"
        }
      ]
    }
  ]
}
