{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2.jar",
          "url": "numen-fabric-1.21-0.1.2.jar",
          "size": 2464053,
          "sha512": "66ede4fb88fa637755ef5051c0f7fb51c4b8e0c90e10e768412d56d0aec712338d47d45537dd5d694825274a8d943230932f6d529a5b8409c193f54dcbb8aeb8",
          "sha256": "cc4050140ff996b09ca96e02c9ee320b66f2255ca320b052150cc49dadf4b68c",
          "sha1": "4a12c9cea7c3f81d1586989b7b0c1945356fa583",
          "md5": "78725a9bc29a19c3b2273a44cfa70df3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2.jar",
          "url": "numen-fabric-1.21-0.1.2.jar",
          "size": 2464053,
          "sha512": "66ede4fb88fa637755ef5051c0f7fb51c4b8e0c90e10e768412d56d0aec712338d47d45537dd5d694825274a8d943230932f6d529a5b8409c193f54dcbb8aeb8",
          "sha256": "cc4050140ff996b09ca96e02c9ee320b66f2255ca320b052150cc49dadf4b68c",
          "sha1": "4a12c9cea7c3f81d1586989b7b0c1945356fa583",
          "md5": "78725a9bc29a19c3b2273a44cfa70df3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2-sources.jar",
          "url": "numen-fabric-1.21-0.1.2-sources.jar",
          "size": 1012842,
          "sha512": "1c68aa7bf32695aad57def7bb90d212288346d9cc0c42089e36a27ac80b8c247970224d8991377ec3657603c2df8f9363d250ba4f4ecee371450c2180f24258b",
          "sha256": "0204f419a7a29036ae2cb07c69af36cf1a4ec0c7ab1e9fc4282394089c755f17",
          "sha1": "e73ee4e5aabd7b6dc9409ea5f8fcbbe01c472779",
          "md5": "1c17e7c1801ddbf2d292026be6b543e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.21-0.1.2-javadoc.jar",
          "size": 1483096,
          "sha512": "fd33b1e6ee7d6a07b73279c37cbd85efa268f96255ddb801a5780c99710f8ede710158b2c1b5d0c84d9d541b9a4a3e506edc8b21db21e8bb4f1ceecfb7494a76",
          "sha256": "8a622cd45afd656098dd2b009816b7dcb2bee20c0034ff3ef51aba3329f4b99b",
          "sha1": "61e0e72b1b8539e65a49ef3ab98062e24bbe65c5",
          "md5": "29ff033d8e72a9a3256850692f11e559"
        }
      ]
    }
  ]
}
