{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2.jar",
          "url": "numen-fabric-1.21-0.1.2.jar",
          "size": 2464052,
          "sha512": "945d2991c313c831b52f068e5538b2f21788c011589d418bb10f1e350f736daece329deac1c9caa0915718abacfad444f9551ae93fc6096309befefc662e1040",
          "sha256": "602879caa5f30b61b327287dad3ee91c847d67dd17aaa9ee6983aba27fc174a1",
          "sha1": "4559b68186bd3409fce434dc3b4499c74c69f129",
          "md5": "a01850151de5be7aeac9d171acd19d8f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2.jar",
          "url": "numen-fabric-1.21-0.1.2.jar",
          "size": 2464052,
          "sha512": "945d2991c313c831b52f068e5538b2f21788c011589d418bb10f1e350f736daece329deac1c9caa0915718abacfad444f9551ae93fc6096309befefc662e1040",
          "sha256": "602879caa5f30b61b327287dad3ee91c847d67dd17aaa9ee6983aba27fc174a1",
          "sha1": "4559b68186bd3409fce434dc3b4499c74c69f129",
          "md5": "a01850151de5be7aeac9d171acd19d8f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2-sources.jar",
          "url": "numen-fabric-1.21-0.1.2-sources.jar",
          "size": 1012843,
          "sha512": "f94d0b10eb27041e7674a881df38733ede379acc047a3403830dc1cecfc920adc24df07ce670c480f9046ff4460807dccd14b4f74f82031283c3709eb8978036",
          "sha256": "cefae850455c893d0b522a51f2ab4f5a3b0da27a0e1426dea6345db8a1e34efb",
          "sha1": "3d504bc0ec7a2a42a841bf90d9d8f7ffc17ee888",
          "md5": "5b53b1839048a46979f020d0c2382bcf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.21-0.1.2-javadoc.jar",
          "size": 1483096,
          "sha512": "fd33b1e6ee7d6a07b73279c37cbd85efa268f96255ddb801a5780c99710f8ede710158b2c1b5d0c84d9d541b9a4a3e506edc8b21db21e8bb4f1ceecfb7494a76",
          "sha256": "8a622cd45afd656098dd2b009816b7dcb2bee20c0034ff3ef51aba3329f4b99b",
          "sha1": "61e0e72b1b8539e65a49ef3ab98062e24bbe65c5",
          "md5": "29ff033d8e72a9a3256850692f11e559"
        }
      ]
    }
  ]
}
