{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2.jar",
          "url": "numen-fabric-1.21-0.1.2.jar",
          "size": 2464056,
          "sha512": "b8f2745cf068cc40bb3c4009c315e58ae547ec6551256baadfc0e7dfca760635271a12453640f3eaced3a99220047a587fe4e924c8e9e62b89a683ce2088e1f3",
          "sha256": "7af0ab39c561ecc7345fcbe457c12273e6300bb1cba8c2ec8579168c4f94a7d2",
          "sha1": "ca5464fde031970c092caedf17f3de436b9b7136",
          "md5": "20f1209ea09bacf3f516a4c67ce0d9f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2.jar",
          "url": "numen-fabric-1.21-0.1.2.jar",
          "size": 2464056,
          "sha512": "b8f2745cf068cc40bb3c4009c315e58ae547ec6551256baadfc0e7dfca760635271a12453640f3eaced3a99220047a587fe4e924c8e9e62b89a683ce2088e1f3",
          "sha256": "7af0ab39c561ecc7345fcbe457c12273e6300bb1cba8c2ec8579168c4f94a7d2",
          "sha1": "ca5464fde031970c092caedf17f3de436b9b7136",
          "md5": "20f1209ea09bacf3f516a4c67ce0d9f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2-sources.jar",
          "url": "numen-fabric-1.21-0.1.2-sources.jar",
          "size": 1012841,
          "sha512": "5a6d6cd3ae56b5ee1ba4af168e609ebc4f155e87bf13c362fe5b9016890593620a1348576e2f9e2930d75f7d62f241db646f42371aafdc3cc7c678f746978dff",
          "sha256": "9dbb949bf08c10a9cca6dd7275889f9d1baa7b1f4d169551adadb80094b19b85",
          "sha1": "993bba02b79c897e69e5220558a17b0b23dacb47",
          "md5": "d5bed819412c5b58ba6790651bfdd9b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.21-0.1.2-javadoc.jar",
          "size": 1483096,
          "sha512": "fd33b1e6ee7d6a07b73279c37cbd85efa268f96255ddb801a5780c99710f8ede710158b2c1b5d0c84d9d541b9a4a3e506edc8b21db21e8bb4f1ceecfb7494a76",
          "sha256": "8a622cd45afd656098dd2b009816b7dcb2bee20c0034ff3ef51aba3329f4b99b",
          "sha1": "61e0e72b1b8539e65a49ef3ab98062e24bbe65c5",
          "md5": "29ff033d8e72a9a3256850692f11e559"
        }
      ]
    }
  ]
}
