{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-ai-1.20.1",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-1.20.1-0.0.9.jar",
          "url": "numen-ai-1.20.1-0.0.9.jar",
          "size": 77142,
          "sha512": "50445f4f36eb8c0997bce7499166c57d8789b0beb38f3937887d4137ff735e297a785b5920dc896049a0d1543835b7e968a2db15293fa09d478c051433af4088",
          "sha256": "dedf69bd4abff1afeb415030eab4f9174a34abb330527aea64e6a2f9668d1f62",
          "sha1": "352f8fe98f410e1a02af102e0ba017b0fd6c10cf",
          "md5": "2e7e3c4ede8bd7cdc7714154a3ebc404"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-1.20.1-0.0.9.jar",
          "url": "numen-ai-1.20.1-0.0.9.jar",
          "size": 77142,
          "sha512": "50445f4f36eb8c0997bce7499166c57d8789b0beb38f3937887d4137ff735e297a785b5920dc896049a0d1543835b7e968a2db15293fa09d478c051433af4088",
          "sha256": "dedf69bd4abff1afeb415030eab4f9174a34abb330527aea64e6a2f9668d1f62",
          "sha1": "352f8fe98f410e1a02af102e0ba017b0fd6c10cf",
          "md5": "2e7e3c4ede8bd7cdc7714154a3ebc404"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-1.20.1-0.0.9-sources.jar",
          "url": "numen-ai-1.20.1-0.0.9-sources.jar",
          "size": 62191,
          "sha512": "53b799bc55ea573818a041eb38acd9b4efc467c2244ab860ab5041737db71c88476c6b63feeb16bcc5aac70a0b776905faf93cb9d0dcaf6cfce38436a950a672",
          "sha256": "493ceb5fd2d1634270fcd975a2aa7736b86aa0745b30874d54076f32fe482c22",
          "sha1": "a64406e16c9476145b97f6e0131e614d5efe031d",
          "md5": "a3e0459c71b1922961f8a0b8399d6186"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-1.20.1-0.0.9-javadoc.jar",
          "url": "numen-ai-1.20.1-0.0.9-javadoc.jar",
          "size": 244384,
          "sha512": "bc14427d9ee6443830d1709141f8e2cee1ac952e3e09346a90c40b5b0eab8c73dbb969999a8b72ebe6ffc7edaf8ae5fc389642e33f1cc48c75e2b4cd14c39f12",
          "sha256": "0e0d9b940ad954bdc427582d31451c4e9d9d4ad78a858591bf8d01fed65f2c9d",
          "sha1": "22e78ce352dff84727271892c5263b5e773e2d34",
          "md5": "9b95fb506b935c12d7f98a7c6f416f52"
        }
      ]
    }
  ]
}
