{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2.jar",
          "url": "numen-fabric-1.20.2-0.1.2.jar",
          "size": 2460124,
          "sha512": "21602229313409d6a8e94115282bbc701cd68cd51c90b55d7863536935bd4d50bf62c4a13b7b427dc395956c8632dc65d98fdcba28d02637e49f89d503bbb375",
          "sha256": "d6c5eb7cef7e9fdb4606239ae23793a66c45dabf55f96300f707afde54d3e262",
          "sha1": "5736e96c0c105ccc12650c4951fdf210939bf0d3",
          "md5": "f0de3203047c80cf2810d1c1493adf5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.0+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2.jar",
          "url": "numen-fabric-1.20.2-0.1.2.jar",
          "size": 2460124,
          "sha512": "21602229313409d6a8e94115282bbc701cd68cd51c90b55d7863536935bd4d50bf62c4a13b7b427dc395956c8632dc65d98fdcba28d02637e49f89d503bbb375",
          "sha256": "d6c5eb7cef7e9fdb4606239ae23793a66c45dabf55f96300f707afde54d3e262",
          "sha1": "5736e96c0c105ccc12650c4951fdf210939bf0d3",
          "md5": "f0de3203047c80cf2810d1c1493adf5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.2-0.1.2-sources.jar",
          "size": 1022325,
          "sha512": "f9638339d1c528a8b1e2dbc90f40560d08ed388bb9eb65dab6d66096348a5f44fdf8691b424314ddcdb073551ef95e912fa44323aba8d90e51d1544a1f9d3050",
          "sha256": "7e692ca8b1218fe6a7f88b967b6ffbc0c647dee6e53265c13986b04ca668672b",
          "sha1": "f4e5fba7737ac95d78ad07fc941003b1c710cc12",
          "md5": "2e4377b0ea55cf1660a34de4f0ceb712"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.2-0.1.2-javadoc.jar",
          "size": 1445092,
          "sha512": "dd654f0ad4994c2b603c61411a811af61c9c9327832e065f5fd6b3c7946260953de870b83e9cc8a424c5a7ab66b933d9953d34f8fe149e0664a6e8dbf15f4801",
          "sha256": "a880af4d83b0fb7a0c77daeef7a24505d77c592cb6a630c8c911f4a578af4f11",
          "sha1": "19ad26e2c92b4c049f41cd71faf737f2a25e7dbd",
          "md5": "e7a3e600b2e476b9413f19481e730639"
        }
      ]
    }
  ]
}
