{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2.jar",
          "url": "numen-fabric-1.20.2-0.1.2.jar",
          "size": 2460121,
          "sha512": "dfe74165e6d77a5f77a329dddb6d8252197fe758c2a2b351e288c09713e85deccbba18b327170ca7ba21835fd486bef596afd1a958ecfa3149e12b80657edcfb",
          "sha256": "6701c3caedb557b6bfc32b17764a7832617775569d1e229e62f00c80ab86e4bb",
          "sha1": "c09483ccc455e16950e65aff300f7427cb03682a",
          "md5": "6b34cc2b91ada9df9d295e93d28e1b79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.0+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2.jar",
          "url": "numen-fabric-1.20.2-0.1.2.jar",
          "size": 2460121,
          "sha512": "dfe74165e6d77a5f77a329dddb6d8252197fe758c2a2b351e288c09713e85deccbba18b327170ca7ba21835fd486bef596afd1a958ecfa3149e12b80657edcfb",
          "sha256": "6701c3caedb557b6bfc32b17764a7832617775569d1e229e62f00c80ab86e4bb",
          "sha1": "c09483ccc455e16950e65aff300f7427cb03682a",
          "md5": "6b34cc2b91ada9df9d295e93d28e1b79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.2-0.1.2-sources.jar",
          "size": 1022329,
          "sha512": "36d109b3f975ed36076bc6dc84902d3fe5f167ff490a0d84d064fd14f936464cf165501d3977e04c2e43fda16324614ce2d28a78e69b0f9a14e3b8389cc3c871",
          "sha256": "f4cb36488fb3afd2c3cdfedc2549a5e6c1932954b65b5ca415dc717d8e6b8308",
          "sha1": "997d70b3d475bddd898af97195651bde87fd5dc6",
          "md5": "8c667e2fb309ea47f774fc2a5f17f69c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.2-0.1.2-javadoc.jar",
          "size": 1445092,
          "sha512": "3019a4c3b2b5137afe6aa69569dad7f1ec1db7980cd11eb18809bd646c88dabbe64bd97e6f324dbcc2d475b4b29c7f212c6f79503bd04ea86a5f6073fdf2ed2b",
          "sha256": "dee9463ff35e81cb7861246ca68e41a0f39995434e5d3555f03bc7652d44b60e",
          "sha1": "b388fa914d665c4fe7f5e5fb407f952a19d134be",
          "md5": "15695cb787f5eef43ac74608fd42f019"
        }
      ]
    }
  ]
}
