{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.4-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.4-0.1.2.jar",
          "size": 1323691,
          "sha512": "85e0725f52140f883a57fb3113384b8063f1cbca8f492f0fefce53fff9b769ae389604cc97cf70333c9814a8ec061ddbdea8c7c8911fc7b1dd12eac82eba88c7",
          "sha256": "4bb91c9417be92612a603cbecee8185d021637603212559adb2c57bc3a81bac9",
          "sha1": "84b909979580e31cc0e464bfe0062181fe0e6a91",
          "md5": "4aeefee4c424ca8701524e135ab459ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.4-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.4-0.1.2.jar",
          "size": 1323691,
          "sha512": "85e0725f52140f883a57fb3113384b8063f1cbca8f492f0fefce53fff9b769ae389604cc97cf70333c9814a8ec061ddbdea8c7c8911fc7b1dd12eac82eba88c7",
          "sha256": "4bb91c9417be92612a603cbecee8185d021637603212559adb2c57bc3a81bac9",
          "sha1": "84b909979580e31cc0e464bfe0062181fe0e6a91",
          "md5": "4aeefee4c424ca8701524e135ab459ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.4-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21.4-0.1.2-sources.jar",
          "size": 1055370,
          "sha512": "7c696d13f181b433b2badfea6adbb7d8d6c5b9be6e9591733905ca69b7ebe5298fbddb1306c1e1a059927f736ae44687227a624174ccea81170242f84bb215ab",
          "sha256": "506a86d00e8addd8d55ecf26c760b2ec77031c9d6e0e2448a9471429f3e02622",
          "sha1": "ba707597a50e1dcc2e8696a6db6e99d077d7ff5d",
          "md5": "87ec7b93a6d5842577bfffc4bad4981d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.4-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.4-0.1.2-javadoc.jar",
          "size": 1564814,
          "sha512": "16afab38b7ba232444bc53561ee1d43c9f2b5081862e4f55ee90daa1324fcbb6ccc5328031a10a1732f8c87f78cc98233b09953782a55aba05f98f11667c075f",
          "sha256": "f3a354ee91c31a12f14f85e9623b0c8dd32574ae9353db0cb60b7d915a0c5abf",
          "sha1": "1d8d7b9e5316fed0e71904acf9200d581fa226f2",
          "md5": "5b44d0d605b92f702be6d6fd003972af"
        }
      ]
    }
  ]
}
