{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.21.10",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.21.10-0.1.4.jar",
          "url": "numen-common-1.21.10-0.1.4.jar",
          "size": 1162906,
          "sha512": "f2c01cb5ead27b029829b2cc96cb21d7dcd111b509b56443aa4a43996eaffa7cdbe3f15804b10f444ccf26fb6d5a679ce8b2c2a11964d7bfa040806cad4f2b90",
          "sha256": "03a42bff8ec00590402e127d8704ec26ca17fe9003d803a1ea42f148d06b0b36",
          "sha1": "032cd05deb028456e33eaec095488f95f369fce3",
          "md5": "a9234178988524c99260ed11f383dc2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.10-0.1.4.jar",
          "url": "numen-common-1.21.10-0.1.4.jar",
          "size": 1162906,
          "sha512": "f2c01cb5ead27b029829b2cc96cb21d7dcd111b509b56443aa4a43996eaffa7cdbe3f15804b10f444ccf26fb6d5a679ce8b2c2a11964d7bfa040806cad4f2b90",
          "sha256": "03a42bff8ec00590402e127d8704ec26ca17fe9003d803a1ea42f148d06b0b36",
          "sha1": "032cd05deb028456e33eaec095488f95f369fce3",
          "md5": "a9234178988524c99260ed11f383dc2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.10-0.1.4-sources.jar",
          "url": "numen-common-1.21.10-0.1.4-sources.jar",
          "size": 876610,
          "sha512": "0997956557c453c40fbc1ed28533ad9ca79cfa0ef5f6791789f632bcd1d965259cb9d15445d2d10ef9c6077e8b6634d9aeb6841b7690a91c2bd460a5d0ca1360",
          "sha256": "6369f5b69272554fe697e2ff0c6f11ecd95e023193fe30efe9b26a214f2a1dad",
          "sha1": "1f8b580525fa5a03c0d6dbf4cbac8996cf173ed7",
          "md5": "93f7c9c7724ec2afdbc566fffa7edee2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.10-0.1.4-javadoc.jar",
          "url": "numen-common-1.21.10-0.1.4-javadoc.jar",
          "size": 1571014,
          "sha512": "d22347569b0745f0060c223fb2b6aaa6a0bc739a54a9b34e57d4cfa07f435a1219addd88243dd182658b96f0ca617c276616c7820e1d5be2a4f3113a10bb96b7",
          "sha256": "e513f1e0638faf8289e9108b2a49eec3aaecc3ca14ab0b481ddaf17095571cb0",
          "sha1": "aa434ee81cb564a7c50062e8aed1c864f8906686",
          "md5": "f05b6cd4b5fac600041796814609817c"
        }
      ]
    }
  ]
}
