{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT.jar",
          "size": 821980,
          "sha512": "b7e9170eae0f67db98fdc4a884c749f5be30b3d255558c3c6b0c96583fbf59e9ab88714fea7b5ecca8a2719a83b1af8ee317d260fdac00db0e16b871a6a21a25",
          "sha256": "27b795adfc6524753d9cd0a9973be0dd5c5459773437ebee873f45006297a2c9",
          "sha1": "475a183c70e54601b8305a9e1f74bf67008413f2",
          "md5": "3e410f8ec99017c69b80f848c9cd19b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT.jar",
          "size": 821980,
          "sha512": "b7e9170eae0f67db98fdc4a884c749f5be30b3d255558c3c6b0c96583fbf59e9ab88714fea7b5ecca8a2719a83b1af8ee317d260fdac00db0e16b871a6a21a25",
          "sha256": "27b795adfc6524753d9cd0a9973be0dd5c5459773437ebee873f45006297a2c9",
          "sha1": "475a183c70e54601b8305a9e1f74bf67008413f2",
          "md5": "3e410f8ec99017c69b80f848c9cd19b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT-sources.jar",
          "size": 699683,
          "sha512": "de6c6f83bb1cb648f4a66b4d6d18f23fa7d71d970f06a3ac34b52cc6ede5585af7383fb716936d0ac71dce4f40aabc955942f5ccc950407b3b76333f6df4dc86",
          "sha256": "2bba4d4bb3fb01d515e546b26ab7b57e3d2477132573bb7bd6990fef74979576",
          "sha1": "a37dc480def7ae066ea6cd818d6342bb95781e72",
          "md5": "12fe2be3b49dfffbf2b7516cdc1ae8ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 1076567,
          "sha512": "f8ec79abeccbded362e87e51b0178364d001f5e3b6fa8c70b71f307bd2cf8842f909bb1a1d698e608ed0e809ae97d6a471839b17d6680994d454faea0a612522",
          "sha256": "22e5bb6eb4c1fff07e63dea19ae963623f06749a63cb99928a5daa405a7d8ecc",
          "sha1": "fc48b2504ee768f465d38cecdd44a1b2173a363a",
          "md5": "c97575ce11c5657f9f983b84b671eb24"
        }
      ]
    }
  ]
}
