{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2.jar",
          "url": "numen-fabric-1.20.1-0.1.2.jar",
          "size": 2464181,
          "sha512": "b8c114789ed83417e13dfbe830d182a0fd581125efc790e90817a8ec038c6d305a45d705abd721f846563ccd5ce998d56db15870750885bf27aa138c4c4893e2",
          "sha256": "8977eedc1a2011b30783acdb0680c2e2a52ad3cdf61bd3b4e880b02cbab90048",
          "sha1": "d6065e77b8bb9b921f910c647291856e5a36b05b",
          "md5": "cf273d5cae5ee962902a2e5bb9d4ab82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2.jar",
          "url": "numen-fabric-1.20.1-0.1.2.jar",
          "size": 2464181,
          "sha512": "b8c114789ed83417e13dfbe830d182a0fd581125efc790e90817a8ec038c6d305a45d705abd721f846563ccd5ce998d56db15870750885bf27aa138c4c4893e2",
          "sha256": "8977eedc1a2011b30783acdb0680c2e2a52ad3cdf61bd3b4e880b02cbab90048",
          "sha1": "d6065e77b8bb9b921f910c647291856e5a36b05b",
          "md5": "cf273d5cae5ee962902a2e5bb9d4ab82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.1-0.1.2-sources.jar",
          "size": 1022104,
          "sha512": "f0475fc0a87940f5d1192c770b11eaa8c3d491dcf77de23a017002b069f135cfdcb42e184e71a2b0ef2709903b4f53f4c80100443990dde76570692fb08846ac",
          "sha256": "d547ae66260af699a7a4cd8e0c6518638fe4cfda741303b94615b6e5064e64c8",
          "sha1": "853fbfecff2fef891c6ef184766bd6e8396b4190",
          "md5": "d626363800dcc7714fa88783d98cbb44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.1-0.1.2-javadoc.jar",
          "size": 1445091,
          "sha512": "f71617a2b5142b65124452ba7e339c9916a9688d8e7872a7467f89f8526257d26635a47a2b07266a4e3d68870782176167ea94bf1f6e2b44ca35779408713d81",
          "sha256": "a830235a28838bc26e65a191c8aca6696a41e7aa9e79c39d7ab7ab670788e377",
          "sha1": "64749469baa08469e833b481866ebd6524736e38",
          "md5": "6348da5c21cd521273e4851233e5be5b"
        }
      ]
    }
  ]
}
