{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2.jar",
          "url": "numen-fabric-1.20.1-0.1.2.jar",
          "size": 2464191,
          "sha512": "9c0ced46f19567273dd837b350b8e6c9eb37a2daca711206c8dbb3f786f78169b52409f7ac9052e2def3390a50b39d9228a3ec233dd562fffd9680b1aa874104",
          "sha256": "a945a7100e661a4178d386667c4d5859bba3b04c0e76a037ca3f625770d95759",
          "sha1": "b22768ce137e6e1aaea2618b64a0fdcca835c22c",
          "md5": "9b81deb5cc22fe00e3523b01682fa4c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2.jar",
          "url": "numen-fabric-1.20.1-0.1.2.jar",
          "size": 2464191,
          "sha512": "9c0ced46f19567273dd837b350b8e6c9eb37a2daca711206c8dbb3f786f78169b52409f7ac9052e2def3390a50b39d9228a3ec233dd562fffd9680b1aa874104",
          "sha256": "a945a7100e661a4178d386667c4d5859bba3b04c0e76a037ca3f625770d95759",
          "sha1": "b22768ce137e6e1aaea2618b64a0fdcca835c22c",
          "md5": "9b81deb5cc22fe00e3523b01682fa4c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.1-0.1.2-sources.jar",
          "size": 1022104,
          "sha512": "a2ccd70a223ac5c425e7cc0734293d28451abc6c0703b51672b5868b713768e60a79203bc394c7cc48e6868ce2fa609dee6722d7000d173ee4bebab90b74f04c",
          "sha256": "fcd75688546057953964ecea8680f1d62e8bbb637c1671e98e7e647262128d2f",
          "sha1": "b0861e796aaab9d44363cb722291f6daa87740e0",
          "md5": "1f25eb58ac80c9ae108c030bf1370160"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.1-0.1.2-javadoc.jar",
          "size": 1445091,
          "sha512": "18577f33b2ceabf95801004c4ff0527d67f231d53ef35f548ef6de28f3bcf5ac22d0ea0488fd662941173ff048d946c80cd7ad4c9858777b442c087ac95bbf88",
          "sha256": "37117ba7c55b358e43e0a82d16cba21912cbde63cbf49a29263124b0475472d5",
          "sha1": "c84ae8bac1985b18db557f8fe4390e18ccbfb029",
          "md5": "25506302d2bd83586c9e20567f89ac30"
        }
      ]
    }
  ]
}
