{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-26.1.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "size": 1328064,
          "sha512": "4aaa7dc256b0626631cce77d375acf989a01c89dcdaba6f6d326f452b186877b9ff357d7c4fcf05e2e450d8e76b6cfa6401f09716d191db798e204a7cb3157a7",
          "sha256": "4048821add1aa899aac332ee8d8528989d74e39a1d486f44996a9169fe87c4a9",
          "sha1": "e33e2b1df7e5617455abb2e96ea30f23cee3fbb9",
          "md5": "f6008b3a11c99e69135c4eccecc13414"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "size": 1328064,
          "sha512": "4aaa7dc256b0626631cce77d375acf989a01c89dcdaba6f6d326f452b186877b9ff357d7c4fcf05e2e450d8e76b6cfa6401f09716d191db798e204a7cb3157a7",
          "sha256": "4048821add1aa899aac332ee8d8528989d74e39a1d486f44996a9169fe87c4a9",
          "sha1": "e33e2b1df7e5617455abb2e96ea30f23cee3fbb9",
          "md5": "f6008b3a11c99e69135c4eccecc13414"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2-sources.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2-sources.jar",
          "size": 1060377,
          "sha512": "8b65c3c97778d177724d6415de2b8d7356138f33bde97393fab98346c16301cf7bdf0b6a67b6dda5ece1c3f9493f78ce692afd84b56749b11046550235a067d8",
          "sha256": "7ef886f84b74ab0c86d3a054f288814f6890d1824b759e70e687f59e401d1f5b",
          "sha1": "e53d00bcf72e9b822ec7d4a8659fbd759da14bdd",
          "md5": "f03fd8f2ab7fab947da07e49a71c0d36"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2-javadoc.jar",
          "size": 5692477,
          "sha512": "9fa8ebb3606aa99042c534b75c1da8c01a2586e2277ab8b94ff7e7f301e074944abd38ca5f4300359d8d3193907bd64bc2f274dd4a53b0375ff894925820553e",
          "sha256": "e3c50718cfa838033a463f65b2948b4aad07715bc2311d4b9651109066b4e5f5",
          "sha1": "9098070d93b3abbdf780d2ccbce621b17af637f0",
          "md5": "ad72dd141bd79cfab70432f775c9719b"
        }
      ]
    }
  ]
}
