{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-26.1.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "size": 1328064,
          "sha512": "509af3d3dd210eccb2bfbfd60abdc44ffac4e5be479e99d26c3500b0cd8ca90b93e6130f7521400e5e9de93284f21181956364e89dd63f7638d294c486a6e93d",
          "sha256": "dcb7fa9dcc1604cf15484ca3ad376e6fb9b545a45bde99244da515857071e024",
          "sha1": "0233c6248937cb4d726de70183e976ef34ebc8d8",
          "md5": "ddd64c8d0c7ec8fa5492fce0d7e25fc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2.jar",
          "size": 1328064,
          "sha512": "509af3d3dd210eccb2bfbfd60abdc44ffac4e5be479e99d26c3500b0cd8ca90b93e6130f7521400e5e9de93284f21181956364e89dd63f7638d294c486a6e93d",
          "sha256": "dcb7fa9dcc1604cf15484ca3ad376e6fb9b545a45bde99244da515857071e024",
          "sha1": "0233c6248937cb4d726de70183e976ef34ebc8d8",
          "md5": "ddd64c8d0c7ec8fa5492fce0d7e25fc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2-sources.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2-sources.jar",
          "size": 1060377,
          "sha512": "9123eabb1d63fb97a1d9ef16f7cfe76e65ffed36ef8c670fb2e6de5b18879492f47e79a63374c7df1459e6bd7d4a3692e19f41bbb64000da7191d1b1aa824fad",
          "sha256": "990b66ee8684cb68f912f3a72d59d4d1b612eacb8496145d6422059cd2813bfc",
          "sha1": "9e93ca15a70f3e9a6fee9721e4c2e194e131b2ed",
          "md5": "7e9a99a1a0e97942027bc7108fde83b2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.2-javadoc.jar",
          "size": 5692477,
          "sha512": "9fa8ebb3606aa99042c534b75c1da8c01a2586e2277ab8b94ff7e7f301e074944abd38ca5f4300359d8d3193907bd64bc2f274dd4a53b0375ff894925820553e",
          "sha256": "e3c50718cfa838033a463f65b2948b4aad07715bc2311d4b9651109066b4e5f5",
          "sha1": "9098070d93b3abbdf780d2ccbce621b17af637f0",
          "md5": "ad72dd141bd79cfab70432f775c9719b"
        }
      ]
    }
  ]
}
