{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.4",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.4-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.4-0.0.7-SNAPSHOT.jar",
          "size": 883306,
          "sha512": "fa866452d361fa745975844425225deff1701606fbad8450d215dba8f617af0a988a776d947f9b6eb26ff7bc12745c204043c7ab482cf99acbf8aa9b36bf21fd",
          "sha256": "9a756eda0b2d5528da1e07f7f76544b1fd5a524a6d4fc22212d956d7f05a3bae",
          "sha1": "4e1d7c5f2102e46b758efc085165c88bcc713c1b",
          "md5": "9a0791c7518f6939908e356731db5297"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.4-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.4-0.0.7-SNAPSHOT.jar",
          "size": 883306,
          "sha512": "fa866452d361fa745975844425225deff1701606fbad8450d215dba8f617af0a988a776d947f9b6eb26ff7bc12745c204043c7ab482cf99acbf8aa9b36bf21fd",
          "sha256": "9a756eda0b2d5528da1e07f7f76544b1fd5a524a6d4fc22212d956d7f05a3bae",
          "sha1": "4e1d7c5f2102e46b758efc085165c88bcc713c1b",
          "md5": "9a0791c7518f6939908e356731db5297"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.4-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-common-1.21.4-0.0.7-SNAPSHOT-sources.jar",
          "size": 708118,
          "sha512": "1bdec913eaec9d7a9154c430d9a9ed5c012bbf9061455da487f07ee056d330f2f6db2c3fc9e14e14e4649965d1dc5b51ff1606a8933063501b87c11773df3e86",
          "sha256": "761ef654a3269278fa7ae63a312fda92056b47034610314c518425c448e288dd",
          "sha1": "e15c745d3992519050035bae925e79738941e7f7",
          "md5": "977d420ce563361a51c405394b56b052"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.4-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-common-1.21.4-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
