{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.5",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT.jar",
          "size": 926892,
          "sha512": "b51a1305db9222e9a1203e720e9107330a56c8be05fd2979a8ca280f562f41205ca72676858e44b6fcd77d52439a7b6767aca14b1095b61c3639287e4ef01370",
          "sha256": "85b588d19a1bbea284acd9ec071b906076b936542bf9f6ab37ee3335bedaf603",
          "sha1": "7690626f46394cb47086852613c5cbac0c7f813b",
          "md5": "366e064d1a4ec2a8f14dfbff2892fc4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT.jar",
          "size": 926892,
          "sha512": "b51a1305db9222e9a1203e720e9107330a56c8be05fd2979a8ca280f562f41205ca72676858e44b6fcd77d52439a7b6767aca14b1095b61c3639287e4ef01370",
          "sha256": "85b588d19a1bbea284acd9ec071b906076b936542bf9f6ab37ee3335bedaf603",
          "sha1": "7690626f46394cb47086852613c5cbac0c7f813b",
          "md5": "366e064d1a4ec2a8f14dfbff2892fc4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT-sources.jar",
          "size": 740542,
          "sha512": "6d0f4ef6060734cb36603397bca84dd2ced3f5b5a50b1fae630d0eb2e558ed8c2247ba4065f96c7799224913711cf2453efe8b44cc316df9e2d30f82a4bac2be",
          "sha256": "0b866afcb73ba93941c6e73c90e5e5bbbba2c45c33352365f63f0c827aacc98c",
          "sha1": "e66fe0d65fea9d0dd80accb892da16eaf7f3006a",
          "md5": "8a6e7283760c7bdea2ee553f75cb6263"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
