{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-forge-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.4-0.1.2.jar",
          "url": "numen-api-forge-1.20.4-0.1.2.jar",
          "size": 1323483,
          "sha512": "da89ee8573ae933e2af035f04a4b8807e3f1f0f58776fd6cb85c49c88d769ba16873caf077ed3c527cbc583a4184129009ebb3e3fae1b861a362d36694360f90",
          "sha256": "606e6e15b66c12898af1533fd6c6c973d2d4346ab5c0777f415c227b1def414d",
          "sha1": "466ed515b3c54a8d6f6a1fd4821edaa020401348",
          "md5": "6d7ff279fd5679112ab13c1633ff9887"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.4-49.0.19_mapped_official_1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.4-0.1.2.jar",
          "url": "numen-api-forge-1.20.4-0.1.2.jar",
          "size": 1323483,
          "sha512": "da89ee8573ae933e2af035f04a4b8807e3f1f0f58776fd6cb85c49c88d769ba16873caf077ed3c527cbc583a4184129009ebb3e3fae1b861a362d36694360f90",
          "sha256": "606e6e15b66c12898af1533fd6c6c973d2d4346ab5c0777f415c227b1def414d",
          "sha1": "466ed515b3c54a8d6f6a1fd4821edaa020401348",
          "md5": "6d7ff279fd5679112ab13c1633ff9887"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.4-0.1.2-sources.jar",
          "url": "numen-api-forge-1.20.4-0.1.2-sources.jar",
          "size": 1054599,
          "sha512": "2dede9303763fc8b3a9f636993eb6c75f789431c31bcdf5339bf100a951797da78012417326abb0b5a44e6536a41df9406abad74cc6ff0c2d1cfa11e3dcf4981",
          "sha256": "367aad977fde111af34ea0bccb26f0faf2044220e370b44d032976070337c35f",
          "sha1": "830d0d8858164006529a2a86d319a121303bf547",
          "md5": "11cc524bf160ddb2b7f7a9cee3a019d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-api-forge-1.20.4-0.1.2-javadoc.jar",
          "size": 1516431,
          "sha512": "e6e2d3d025cd3bb9e1d239bf6e77abcac3436ad54aff66bed9a502a0e7456b47043df4123d462b722702dcc9deb42ece905071446e0a5d029cea4a80450a2ec5",
          "sha256": "4c2f1771cbfd820a448051916f199fd6d7dee1bb94aa0cdd0d895421511363b1",
          "sha1": "6791fa1309e58a812520247c42102c0ccef817a2",
          "md5": "4f53761f900fb3614427c59ce6bd9104"
        }
      ]
    }
  ]
}
