{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21.4",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.4",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.4.jar",
          "url": "numen-fabric-1.21.4-0.1.4.jar",
          "size": 3912642,
          "sha512": "ed741fda1dd063ebffdbd7abb2707efe5d9f45adc51b8075572401166fc43a197d6ab8abd2d6fbe13cbf83e80607ce241331caf693d07c3477a603b87edc4a90",
          "sha256": "ed8d84afc461a22c18d888ceb995561592e7fc02a65543a0aa75a2ffddf8a37d",
          "sha1": "91dc8ef32321ca79eb33b3a30753dc96347c81da",
          "md5": "d05c3aa50be9e1ade37b1101e93ba7e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.117.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.4.jar",
          "url": "numen-fabric-1.21.4-0.1.4.jar",
          "size": 3912642,
          "sha512": "ed741fda1dd063ebffdbd7abb2707efe5d9f45adc51b8075572401166fc43a197d6ab8abd2d6fbe13cbf83e80607ce241331caf693d07c3477a603b87edc4a90",
          "sha256": "ed8d84afc461a22c18d888ceb995561592e7fc02a65543a0aa75a2ffddf8a37d",
          "sha1": "91dc8ef32321ca79eb33b3a30753dc96347c81da",
          "md5": "d05c3aa50be9e1ade37b1101e93ba7e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.4-sources.jar",
          "url": "numen-fabric-1.21.4-0.1.4-sources.jar",
          "size": 886508,
          "sha512": "d4fb2dac21de60086d46762d03597a7b218333a62e35545769342545b5fd61cd0972c179d00baf9c56611a182e9d0eb1a5ac4b2b1cf82e3f9f67763f666ffa81",
          "sha256": "585ac9c773c7a94a33d1583adc7053582618cb4eee627d4723b1fab94d9ab9a3",
          "sha1": "8549c42aad845fc74d4c249b64fad018b2344dd3",
          "md5": "76862c6ded9998318d53cf4d3012c197"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.4-javadoc.jar",
          "url": "numen-fabric-1.21.4-0.1.4-javadoc.jar",
          "size": 1587978,
          "sha512": "f9b0c75d2d49f0c29da03de09cc72c983feb2cb20bf3ed135ea1674ecf80c3eb45918abd62b1f890aaa3a13cbaa34469c00835163b6e61a475bb9791f5bcac4c",
          "sha256": "f0e9a01416acb9334abad0009b690f74f49ce9769bb02954c734d330b6b8752c",
          "sha1": "7363cc0f0e1306782d20800804699ae20ab68dbe",
          "md5": "cbf14ebb72e35ab860c7e6a56aea49e0"
        }
      ]
    }
  ]
}
