{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.1",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT.jar",
          "size": 974314,
          "sha512": "5557b78147bbdb2763196babd2ccee33addf98dccfc94db626313ca452da9108c9b9dc261df72cb899f2f6774c966383b30b2a4485a7177c4d0835707ea62450",
          "sha256": "9fe21f434388bca4ef6cada839dafc693e623d073b9615680f3a1d1381612350",
          "sha1": "243323105b8624facadd5c2fa752622639db7ad3",
          "md5": "952bb6fc57e401f6a58db17a93e48486"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT.jar",
          "size": 974314,
          "sha512": "5557b78147bbdb2763196babd2ccee33addf98dccfc94db626313ca452da9108c9b9dc261df72cb899f2f6774c966383b30b2a4485a7177c4d0835707ea62450",
          "sha256": "9fe21f434388bca4ef6cada839dafc693e623d073b9615680f3a1d1381612350",
          "sha1": "243323105b8624facadd5c2fa752622639db7ad3",
          "md5": "952bb6fc57e401f6a58db17a93e48486"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT-sources.jar",
          "size": 780598,
          "sha512": "10f4befffdecdc184a994459284858104bab259be6bf21de5b21d38d1ede0838027042127cfa37365426fbc18f8d9026a036e613ce7c2d454da3ae057f19cb6b",
          "sha256": "4cea0e2a6f680ede84e266d8502d3bf7843da961bd3e26e12d8305c9243f0319",
          "sha1": "3082f0debaa2321085c266ad6f2d361a7ca1aa23",
          "md5": "b00bf4661d9bd31a4a4bc9d8428216fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.8-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
