{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2.jar",
          "url": "numen-api-common-1.21.1-0.0.2.jar",
          "size": 526293,
          "sha512": "58b15aeae42dfa9b4410edf061c7c3034db6223c3981e0f15bf29b8ed3ea69eb37083d763d421b9dc285a758b6ba72348dcaa5d7547cc7c13ce9aba5fca1307a",
          "sha256": "0093c941c76087f88a968efef0b9c1140c8c9e8425b9e8226840c5b7950e09e4",
          "sha1": "00725fa45d8a85b846bb4c4cdc25677cad994ec4",
          "md5": "99592de7d19189cf5b43596f927667a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2.jar",
          "url": "numen-api-common-1.21.1-0.0.2.jar",
          "size": 526293,
          "sha512": "58b15aeae42dfa9b4410edf061c7c3034db6223c3981e0f15bf29b8ed3ea69eb37083d763d421b9dc285a758b6ba72348dcaa5d7547cc7c13ce9aba5fca1307a",
          "sha256": "0093c941c76087f88a968efef0b9c1140c8c9e8425b9e8226840c5b7950e09e4",
          "sha1": "00725fa45d8a85b846bb4c4cdc25677cad994ec4",
          "md5": "99592de7d19189cf5b43596f927667a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-sources.jar",
          "url": "numen-api-common-1.21.1-0.0.2-sources.jar",
          "size": 452836,
          "sha512": "b1b0c53ad6ac773e8e81a699dd81591fb8699fd2db97ada598110ec930913184e5e52452094d0dce959da2ca8604b55b1587a54620720d7e7fbd916ab6775936",
          "sha256": "49bee1b8248f44a8e8fd8895d47b5134a07cd35987030c537d381b863de928f8",
          "sha1": "b2ee5f261720b0d2f0cd4f999679baea3de348e6",
          "md5": "2739b0695f75d1310f5e3580c7bf0103"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.0.2-javadoc.jar",
          "size": 665573,
          "sha512": "12a3e84c3ed1f83d74c18546ff27f0d04cc2024c91bcb12e05c796ba60f6b57a1f76cdfaae39de3f13d39fbc2b7122d0f35a8ee5bdbda8cb5103a5a5704fd0df",
          "sha256": "97c209d26fe97e8c1921c42b69988447dd82586d236d5bbc0eb93f09cbca2e33",
          "sha1": "8c09887804ac1b79dd4d2d0886e318e73e03ffbc",
          "md5": "5c0e032054b8c9ab5e74a252eb996886"
        }
      ]
    }
  ]
}
