{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2.jar",
          "url": "numen-api-common-1.21.1-0.0.2.jar",
          "size": 557339,
          "sha512": "13fe94152763ad89e5eebe9ad7e3309afbabd619ad3b25df93514afd5b94122c7939efc2100c4cdc13a0af451272ac26185facf80fe07193fa81ede243617d02",
          "sha256": "494d776e9abec820a647d4d62a4c28c3290624425c697fed13f9f8e3f359ea74",
          "sha1": "d31947528322405dbb37330d3041dae10455eed0",
          "md5": "dce0e86b6d6b3339e058c70578be823d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2.jar",
          "url": "numen-api-common-1.21.1-0.0.2.jar",
          "size": 557339,
          "sha512": "13fe94152763ad89e5eebe9ad7e3309afbabd619ad3b25df93514afd5b94122c7939efc2100c4cdc13a0af451272ac26185facf80fe07193fa81ede243617d02",
          "sha256": "494d776e9abec820a647d4d62a4c28c3290624425c697fed13f9f8e3f359ea74",
          "sha1": "d31947528322405dbb37330d3041dae10455eed0",
          "md5": "dce0e86b6d6b3339e058c70578be823d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-sources.jar",
          "url": "numen-api-common-1.21.1-0.0.2-sources.jar",
          "size": 473087,
          "sha512": "567e1098d0b1ee22034012503460062c6c84a9e1cb6276e793dcdd17a8402f93a42d313cd5c54a13f9265ccd5a550f3cca7e973c7fc6bf86a6b0896713ccc3de",
          "sha256": "b8f3778d6cdb106ac060e55b133c7e4656ae9cae44b7384fb5d086809e51b4ff",
          "sha1": "8fe6e82db2f53d3a6b4759cfe4c26e1e5b75cc94",
          "md5": "c42200311ae14313caa72a0e8b62ce1a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.0.2-javadoc.jar",
          "size": 725865,
          "sha512": "a8b13a99b4020b9e5943b8fd816b19b11db17f843af34091db2c29bc7cd24acc69be93b1b258ce9d3a0031bd8692dd079c48498a94fd669a6a3be973a97f8041",
          "sha256": "74250dbc811d0d540e75d3554aad8bb63514a549be663b1f1b0b15146a7bf0c7",
          "sha1": "79402db4f7db34acc8fc3381a265f8e903333dc7",
          "md5": "de3fdd5244385ecefff9b7a45d90b9d1"
        }
      ]
    }
  ]
}
