{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-forge-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-forge-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2.jar",
          "url": "numen-forge-1.20.2-0.1.2.jar",
          "size": 1291924,
          "sha512": "3719b85d0ce475d8fb00531737b619167eeeb48783f2df0ba3d13e4656b493a10e45bfbd9744a8b361d9516f8a7857bcf03e50a7c0964c35610135b0217e9cb9",
          "sha256": "a3ce097133d181d88c1bbca56af4541b02bc8f220e4a897a238439166defaf5a",
          "sha1": "ec54a315e10aed85dd76f224d2a16720150d218b",
          "md5": "02dd13de802ac58e281b4be5e9654f05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.2-48.0.49_mapped_official_1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2.jar",
          "url": "numen-forge-1.20.2-0.1.2.jar",
          "size": 1291924,
          "sha512": "3719b85d0ce475d8fb00531737b619167eeeb48783f2df0ba3d13e4656b493a10e45bfbd9744a8b361d9516f8a7857bcf03e50a7c0964c35610135b0217e9cb9",
          "sha256": "a3ce097133d181d88c1bbca56af4541b02bc8f220e4a897a238439166defaf5a",
          "sha1": "ec54a315e10aed85dd76f224d2a16720150d218b",
          "md5": "02dd13de802ac58e281b4be5e9654f05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2-sources.jar",
          "url": "numen-forge-1.20.2-0.1.2-sources.jar",
          "size": 1065813,
          "sha512": "39a91f9f0be7496eae9bb16df19cb8ae19758bdc25fb24724cd87a9af323503edbe5b7324677dfbee20c1f298bdcdcbcff1b597e4535f8ecc4ffd524410f8118",
          "sha256": "32bd24eb4f5c7e6609d64d02988777749d6e11a14d60359d6fc8ee54f7949a15",
          "sha1": "ac66b50c64ae1f1f0ddbb5d826bf9a93c241582d",
          "md5": "770f1212bf52ff9acb4dd604ac6662ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-forge-1.20.2-0.1.2-javadoc.jar",
          "size": 1486156,
          "sha512": "09f5b35a8d50f88d9e1b37e804c911faac278e7e829609e269e4fa208b57048e2a247c5d954248eedbf372c8219dfc6190cdd0a4b0da364b66209b2b447447ce",
          "sha256": "9d3b47c1ccf9d7cd2bada14029c831ba41f160dd00272131c5e9e460b09da357",
          "sha1": "907f22d12bd8b7b0976308b9402dcdeecc6cadce",
          "md5": "7236b397a8f09d162e086419ff4d64d7"
        }
      ]
    }
  ]
}
