{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-forge-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-forge-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2.jar",
          "url": "numen-forge-1.20.2-0.1.2.jar",
          "size": 1291924,
          "sha512": "74f330ee29a4fcd833978287751d61fb609e8c349d903efb0d6810baa098764ef2f7aec4ae7a9963bddf1f8f086ded72a37d4f9a26d0d097926d695401cc4fda",
          "sha256": "2cef5659f374bab91c1b14f1b88d10615d389d60eefbcf84211d7e1dfef55ea8",
          "sha1": "cf9d52271f8736022be4b1ea9c5cd2bc216a5e28",
          "md5": "7c742d6a89594078d002f6e06732da96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.2-48.0.49_mapped_official_1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2.jar",
          "url": "numen-forge-1.20.2-0.1.2.jar",
          "size": 1291924,
          "sha512": "74f330ee29a4fcd833978287751d61fb609e8c349d903efb0d6810baa098764ef2f7aec4ae7a9963bddf1f8f086ded72a37d4f9a26d0d097926d695401cc4fda",
          "sha256": "2cef5659f374bab91c1b14f1b88d10615d389d60eefbcf84211d7e1dfef55ea8",
          "sha1": "cf9d52271f8736022be4b1ea9c5cd2bc216a5e28",
          "md5": "7c742d6a89594078d002f6e06732da96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2-sources.jar",
          "url": "numen-forge-1.20.2-0.1.2-sources.jar",
          "size": 1065813,
          "sha512": "07138ec0c1ff95312c43c27187601a3ec0d55e88a7cf9c1971fc1fe5ccd4c09727f98bd4f2eff19bf42e2b5ae42cb9b836b02a8702100487e5466ac530822705",
          "sha256": "04aea7b63c68b92c53cf3e23334f5acaa8665031efbc9c4e60b4f68885939be6",
          "sha1": "98d941bf493e6721a1ebbffb2c63033e56043713",
          "md5": "97c8f0ac8b4cc0ca0997533f6cbd085c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-forge-1.20.2-0.1.2-javadoc.jar",
          "size": 1486156,
          "sha512": "be0dad8bb1c0064b217064cf58fafa41c78f7fc26310ce50e714c88495a56f686146890d863b28b0e18a3416dff6a29e7f4e9527f2e0dd585c8adadd8b40803e",
          "sha256": "f429705f5c11bcc94d54dce4d74aa449edfd04e473be9bc745804930ca3f3190",
          "sha1": "11386434c73e9820406e074e202123390a5f1cdb",
          "md5": "888db7c9337657aad45b3efb33863a10"
        }
      ]
    }
  ]
}
