{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.11",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.11",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.11",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.11-0.1.3.jar",
          "url": "numen-api-common-1.21.11-0.1.3.jar",
          "size": 550159,
          "sha512": "cfb45d559aa8ebc2a0bd08e1ee24d12b58d7d53e3c102770d81e25e04184dd677b077264719bce61f54b57f9dc8e689b4d0fdb32ebdfe13ee198e3343ceea34a",
          "sha256": "025a292fb660b63aed0df556ef4266d30b672479cd74aa3d6446d0638d006902",
          "sha1": "f489eab7d285454ae8db9ac3213c6662422b9f07",
          "md5": "fb65864df94ed4eae527ee38a7a8097c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.11",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.11",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.11-0.1.3.jar",
          "url": "numen-api-common-1.21.11-0.1.3.jar",
          "size": 550159,
          "sha512": "cfb45d559aa8ebc2a0bd08e1ee24d12b58d7d53e3c102770d81e25e04184dd677b077264719bce61f54b57f9dc8e689b4d0fdb32ebdfe13ee198e3343ceea34a",
          "sha256": "025a292fb660b63aed0df556ef4266d30b672479cd74aa3d6446d0638d006902",
          "sha1": "f489eab7d285454ae8db9ac3213c6662422b9f07",
          "md5": "fb65864df94ed4eae527ee38a7a8097c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.11-0.1.3-sources.jar",
          "url": "numen-api-common-1.21.11-0.1.3-sources.jar",
          "size": 509173,
          "sha512": "a5f1acafe02c7f1a645d8647db9a045a1e282d77dada5a8ae09df9838d54e193c99d86c801a5c47d6b473d2e5d3e2bf85f9ec971298cebd4268dd3b62c34d2f8",
          "sha256": "1ce01e88e66365740d51bed2fbf6d45d0f8b9b33dd9542ff61f7d0b7db6a043b",
          "sha1": "ed9d7bffc1a9f332078efd5db421428793c4dc09",
          "md5": "9453b7b7cd3e8b234fc781a27575a862"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.11-0.1.3-javadoc.jar",
          "url": "numen-api-common-1.21.11-0.1.3-javadoc.jar",
          "size": 750693,
          "sha512": "5779a2e04abf11bb94a7109ef327136c02110ff6aa6eec9b5135fa8adc83e5b7deeff657b13151f546017d912d3fd2f0564ade3852c575814c66a41a7fe04fc3",
          "sha256": "3efa82eb58e5b8d0c0f6335fac52c3c5fd78e2aed7139cc979440dfd1af3023f",
          "sha1": "7eeccfba0e48331a4784b5b10f86e2f6f14b1f3d",
          "md5": "aa8336536df2c8e0d04a10c3ad1ae16d"
        }
      ]
    }
  ]
}
