{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.2.jar",
          "url": "numen-api-fabric-1.20.6-0.1.2.jar",
          "size": 1319806,
          "sha512": "52346a905070ed93d6687465303be2883c30746a3ddbd07768de4c5e935f54a559fb4c0ded3bda02cedcb012dcb9e1c7e6d9ba186be115719e9da1b6283fe6db",
          "sha256": "d440475c9170f4cabc1d3a42bacde41a6858f7bd1d24bec580a515b20e933ce9",
          "sha1": "55751bd1c977af3d98a8b576ad56020c23de6fa4",
          "md5": "3de231ddf42956c2ce0c592836aee7ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.2.jar",
          "url": "numen-api-fabric-1.20.6-0.1.2.jar",
          "size": 1319806,
          "sha512": "52346a905070ed93d6687465303be2883c30746a3ddbd07768de4c5e935f54a559fb4c0ded3bda02cedcb012dcb9e1c7e6d9ba186be115719e9da1b6283fe6db",
          "sha256": "d440475c9170f4cabc1d3a42bacde41a6858f7bd1d24bec580a515b20e933ce9",
          "sha1": "55751bd1c977af3d98a8b576ad56020c23de6fa4",
          "md5": "3de231ddf42956c2ce0c592836aee7ee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.2-sources.jar",
          "url": "numen-api-fabric-1.20.6-0.1.2-sources.jar",
          "size": 1058772,
          "sha512": "75323f426ee0e6e9f14076168551dc5f4feb75a5be8be49b3555279805188c3ec38fcad0a3f59f54c86ed1d715ae63aacda19d34f955e0cf8a6656fb10ca96ce",
          "sha256": "1e9c1435fdf5d8900f6c38282a0ff10a84516125ac5f397a40cfee52fbec420e",
          "sha1": "6b60f11cf92a1ecec2adde60ef748051346fddb3",
          "md5": "8f49494b0af88261cd42a8bbcc8f45d4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-api-fabric-1.20.6-0.1.2-javadoc.jar",
          "size": 1565285,
          "sha512": "f1b2283afb2e66303822d62baaa4f11ac2c2c8ff9f62b840fb602c21d395b496fa064a49ead095f3e74a12fe0058eeffe625cd69ede06565bd7d54ea2b429bc2",
          "sha256": "024b53f58773f22eed24b6c215bc4942706d5558ac0d9a89600fd749a0dcaf2f",
          "sha1": "0e18a49ac3e1e995d186ba63351a479c9512780a",
          "md5": "4449c7a6934aaa91c2f855417bccfeb6"
        }
      ]
    }
  ]
}
