{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-26.2",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.2",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-26.2-0.1.3.jar",
          "url": "numen-api-fabric-26.2-0.1.3.jar",
          "size": 1362487,
          "sha512": "3b6a0094a5c03e3d8ea5f4bf75ec388edc23497d79421d818f52539cdd49c1a497845a9cce2342c84db8f84e30b68d964351702f60e577a2f786e190a2415885",
          "sha256": "0d9bb60706410c4190f46b28867613a053d60b4078847f765fe0db1fb0121b88",
          "sha1": "37b9a97ad8cd2f75e9947a634efb2476c3ef1c24",
          "md5": "ee5a24fe0b9dbbe26ac0ab2ca9aaad23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.158.0+26.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.2",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-26.2-0.1.3.jar",
          "url": "numen-api-fabric-26.2-0.1.3.jar",
          "size": 1362487,
          "sha512": "3b6a0094a5c03e3d8ea5f4bf75ec388edc23497d79421d818f52539cdd49c1a497845a9cce2342c84db8f84e30b68d964351702f60e577a2f786e190a2415885",
          "sha256": "0d9bb60706410c4190f46b28867613a053d60b4078847f765fe0db1fb0121b88",
          "sha1": "37b9a97ad8cd2f75e9947a634efb2476c3ef1c24",
          "md5": "ee5a24fe0b9dbbe26ac0ab2ca9aaad23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-26.2-0.1.3-sources.jar",
          "url": "numen-api-fabric-26.2-0.1.3-sources.jar",
          "size": 1094087,
          "sha512": "93ae454fe734d2982cd9a6fe81f6fefb366fb83f5535000b7bd431fd5d84b8ac825a4d061303abfb4e182b174f90ed9995d283fa873f3faa10a2811fd2b4813f",
          "sha256": "51463a1be4f649c4dbdc9eaf09068203034851eab4ca42440d723cd59b086cd9",
          "sha1": "2090d03aeeb21fdc31fb78f60670cb93c037766a",
          "md5": "1641499ab2d07f6a9c3ba517790b2f1a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-26.2-0.1.3-javadoc.jar",
          "url": "numen-api-fabric-26.2-0.1.3-javadoc.jar",
          "size": 5744047,
          "sha512": "449e8a6c95410d426d0c7176bf9c0a565613752f735f8ad96d7ed8b00b243319dad9dc36a775e9d501638d42bb0e033f0953aa08207ad40df714efae7d296a04",
          "sha256": "006fc29dd4ff07c569ea670a4660851224ea2a7b27672afefa53a4da6399adea",
          "sha1": "f25b71cc9dd9fe5f0c3b6c1b1f94e9967baa795b",
          "md5": "f3ed253aeaa32d3961ccbc26f804a456"
        }
      ]
    }
  ]
}
