{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-26.1.2",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT.jar",
          "size": 912426,
          "sha512": "7f91b332d7515a4974a6215335cba0f452531e71c1bb9d852f1a9dc02c9c211c2db1ce071fe564fbdd46f64139b960bf20f5b4964556c23d93bf24f72243f433",
          "sha256": "03d15eab98bd32c98b8533874838c68b6c3588fab0ae12fee8b62b534bb19a3e",
          "sha1": "9f2bb95f09ea0a0eb25326ce2c4bbcfe6dd9f4d8",
          "md5": "3bbf93ba0cfe5c00bbb78383cbe956d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.148.2+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT.jar",
          "size": 912426,
          "sha512": "7f91b332d7515a4974a6215335cba0f452531e71c1bb9d852f1a9dc02c9c211c2db1ce071fe564fbdd46f64139b960bf20f5b4964556c23d93bf24f72243f433",
          "sha256": "03d15eab98bd32c98b8533874838c68b6c3588fab0ae12fee8b62b534bb19a3e",
          "sha1": "9f2bb95f09ea0a0eb25326ce2c4bbcfe6dd9f4d8",
          "md5": "3bbf93ba0cfe5c00bbb78383cbe956d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT-sources.jar",
          "size": 716852,
          "sha512": "99cb6cb78c351d410e0a3705326c7cd447e564ff9d0cce032406c520f09f25ff27eb85c5453b9eff7a81c47021585c7b6e2842c4a55c563aa9f1ed4397e191c0",
          "sha256": "dc1404736c623d0977a54bbacf3041ae7e3d9fcb0b9261cae17b00226862828c",
          "sha1": "7d3125eccc89e298008508de37049b0f41a099c2",
          "md5": "66e791b4f47e2f234f51e31f4814d049"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-26.1.2-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
