{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-forge-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.1.2.jar",
          "url": "numen-api-forge-1.20.1-0.1.2.jar",
          "size": 1327752,
          "sha512": "01d1004e052c69d730867bb3ef53b5985e5106ea5eeade1c901aedd51313e96c30dff766ba0dd686bb2fb17be637b9745f3454b886c9bfb0588f5da3b8b3e0ab",
          "sha256": "a1b793c1dec5dffad761c0a7d02aa1f747a63cacf767cad50aa807e4fe6a8f82",
          "sha1": "eff44f12c08b5dd56c1973c9126e5b1ebf4c5b15",
          "md5": "163a61aa735fd73fe4890a0758fa3df5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.30_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.1.2.jar",
          "url": "numen-api-forge-1.20.1-0.1.2.jar",
          "size": 1327752,
          "sha512": "01d1004e052c69d730867bb3ef53b5985e5106ea5eeade1c901aedd51313e96c30dff766ba0dd686bb2fb17be637b9745f3454b886c9bfb0588f5da3b8b3e0ab",
          "sha256": "a1b793c1dec5dffad761c0a7d02aa1f747a63cacf767cad50aa807e4fe6a8f82",
          "sha1": "eff44f12c08b5dd56c1973c9126e5b1ebf4c5b15",
          "md5": "163a61aa735fd73fe4890a0758fa3df5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.1.2-sources.jar",
          "url": "numen-api-forge-1.20.1-0.1.2-sources.jar",
          "size": 1058374,
          "sha512": "daea25b431045fd8841cf60ef3267c5271f432ef700c9a2621664bf8f4e0805302b7e9eefe8f82d6ded1049fe618f9e8705c482a35556302407bae6df87536fc",
          "sha256": "1071f02cd1753e313a58c24ccfc8bd4dac955f63f5997a3cfbc4b009bd7eb7ee",
          "sha1": "b56dd1c1c0d69a2fa97395db75e10bf2f136c3d9",
          "md5": "9dbfde7eef8bc66236a119c5f7932f35"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-api-forge-1.20.1-0.1.2-javadoc.jar",
          "size": 1527532,
          "sha512": "a33b113284f07632facc2a9373817f121232aa7881214cff376dbfb23be6ae485cd7f06b5712283cd89ab98cb0d508758bc7f4c8d5261f95539d3aa6b0e652ff",
          "sha256": "1a555abd89af9c877137ac0960ec82127faeac1cba09517eb93d9b44eea4801c",
          "sha1": "567b05a64a1482c9fa34e99bef68ee962b56961a",
          "md5": "898e3500df359bd0dae41eeeaebbedd2"
        }
      ]
    }
  ]
}
