{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.11",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.11",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.3.jar",
          "url": "numen-neoforge-1.21.11-0.1.3.jar",
          "size": 2598356,
          "sha512": "7403170af98ddb7e3788db16735086bc34b6a486fb008d372bbab0157f741f04c9e484f3efaa85cad88851dffdcb37e8898d6630fd514c1a118e1b13b1b533a5",
          "sha256": "7c87521407196eb5815bbd39154cfbe772708e97dec1436fcb7d5ffde5bff723",
          "sha1": "4253ae15a0970a6a9fc5d5d318ed7400e7d27bef",
          "md5": "08e889ea66a9820e7df21021a7bc6fe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.11",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.3.jar",
          "url": "numen-neoforge-1.21.11-0.1.3.jar",
          "size": 2598356,
          "sha512": "7403170af98ddb7e3788db16735086bc34b6a486fb008d372bbab0157f741f04c9e484f3efaa85cad88851dffdcb37e8898d6630fd514c1a118e1b13b1b533a5",
          "sha256": "7c87521407196eb5815bbd39154cfbe772708e97dec1436fcb7d5ffde5bff723",
          "sha1": "4253ae15a0970a6a9fc5d5d318ed7400e7d27bef",
          "md5": "08e889ea66a9820e7df21021a7bc6fe3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.3-sources.jar",
          "url": "numen-neoforge-1.21.11-0.1.3-sources.jar",
          "size": 1074491,
          "sha512": "3b68d8c96fe45bfe2478dd0d360c973d3a45c3227fd433abca64b3a53197cea96069489cc420a004eea06486d1f3765e44334e19e4d0364804e550dbced50f2a",
          "sha256": "e9b0518bc97a149c0a7707f31ca613a67bd809596150f0aecb2871c5aa0b4f98",
          "sha1": "1a148a31036c6e681e39a006f16197bf8f6f691b",
          "md5": "7446e833ecbb836f96a721452e0447a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.3-javadoc.jar",
          "url": "numen-neoforge-1.21.11-0.1.3-javadoc.jar",
          "size": 1540120,
          "sha512": "b50a2a2e6af68edc8f4065f826de679ad435423d284a54b95cb6def84ec2bc0fe79c1926cd20bb4dac7faed737ad4d59b51bb49d79947d053220c90d5afd25ad",
          "sha256": "1683c1bf42ed1a58fb3f6bcce52fd355ddb09af1317984283fc1641653f5b0ed",
          "sha1": "22ecb8403edca34cc036d2fcda804647a874e8fc",
          "md5": "7f852f4b1f78a30a4916ffcfb31d30ab"
        }
      ]
    }
  ]
}
