{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 611726,
          "sha512": "21670d3856d941b148d0c990c36b9ef77cff69d82cd377e99e9cc3f2437cb04b4b15ab4d7da9a4774b65acc08211584370ce7df65b8a218f5e32b092236125ec",
          "sha256": "757420613b2400fdd1a1bbeff0d526566a500f1b107ff9adee7a09d6d9f5bcae",
          "sha1": "1ca0c07f9abc093aa9c4071e395895bd2ab32525",
          "md5": "e246fe1ea69f05a108880de6de18df42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 611726,
          "sha512": "21670d3856d941b148d0c990c36b9ef77cff69d82cd377e99e9cc3f2437cb04b4b15ab4d7da9a4774b65acc08211584370ce7df65b8a218f5e32b092236125ec",
          "sha256": "757420613b2400fdd1a1bbeff0d526566a500f1b107ff9adee7a09d6d9f5bcae",
          "sha1": "1ca0c07f9abc093aa9c4071e395895bd2ab32525",
          "md5": "e246fe1ea69f05a108880de6de18df42"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "size": 506658,
          "sha512": "18ef9e0a04e785723fabbe01f38e19593564d1ad52072ff975659100642eac7da111433df52776ce21386fdccdad304c0288fdce2137e35f85c6dd613a9e3aa8",
          "sha256": "b1dde1fcb07ce15518a558d64384a5731af96cdc817b3937d7531f28470ebc8d",
          "sha1": "d02d20bd674979dcab3f0c36cc35ed08bc19f286",
          "md5": "d9d62de30c2b8aa165abf5f9d9952d2d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 745547,
          "sha512": "68f4bbdb5471625d661ea4f89939f3047dcd7471bf35c5baa1db54a27e33aca5991cae944db5ef2aff55956e0777785fcc521ae8dfc634549efb1c5291d062b0",
          "sha256": "f46f5e985e10bd8bb3c28df6eee2f0ec3626aa81269fefcfbb0c71b8418beb89",
          "sha1": "84487d44ead4c396aa9718a81b6a614fe9a359b0",
          "md5": "8f38d7903ef76bc7b08247d591325662"
        }
      ]
    }
  ]
}
