{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 526102,
          "sha512": "ef20625f22850eada0c4e8c1a7f5018d98e8f77a4d682a754037f39514a70b2ec1df06e9182342a660425b257616b7a738b59e8b6cdfb19494d8f3794320991c",
          "sha256": "8083845c61db146f9576f92e3691c8c0f446bf68be9e9f76f9b295adebccfcdb",
          "sha1": "1ed3c307897db7f5f92158c1a67b48438a00ba34",
          "md5": "ddc9dde2611d13b9b4e8d3b56f8f27ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 526102,
          "sha512": "ef20625f22850eada0c4e8c1a7f5018d98e8f77a4d682a754037f39514a70b2ec1df06e9182342a660425b257616b7a738b59e8b6cdfb19494d8f3794320991c",
          "sha256": "8083845c61db146f9576f92e3691c8c0f446bf68be9e9f76f9b295adebccfcdb",
          "sha1": "1ed3c307897db7f5f92158c1a67b48438a00ba34",
          "md5": "ddc9dde2611d13b9b4e8d3b56f8f27ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "size": 454684,
          "sha512": "43f78047ab664f0e6d9b548a8a16fbec9cd90131bca32aed87a36b73f24f5c60a3c95b6d994c053cfdd19f831334b3a3f91a8d09250437520491c941f2abc22a",
          "sha256": "a817a9d4be481ce45c2b9695fbd35b54feb5fe2d80799a1b325199b9f42855e6",
          "sha1": "700f27b96f5c3780b1a713c49092a38a163a1efe",
          "md5": "3d74afeb2548a3bbd250629cf9cabf0e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 662523,
          "sha512": "ca3bfedb2086a3435b570bbba7c56ae7a8aa649a5d3e9a6b916ab828ccb2e7d785d70d5dee984210d6dc0a469b84a6db0c8a4ab9b59e7832e1b9645a31e55583",
          "sha256": "689d76cf3c2b0fa3d12a80afc15124507339fe79e5eb5b877d6955cf8d78cd99",
          "sha1": "dbbcd077195374ba19b605138851f0bffd402ada",
          "md5": "c88be13ad6c3a0ad1a57ac865566b097"
        }
      ]
    }
  ]
}
