{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.20.1",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-common-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 882725,
          "sha512": "fdc0fbc6467c35f79180733d4cccb6ebc7b78ad98b753a3e2cd278fb09fe2ace479d6cfd6684ec515a37f87631861f42a5835b4854eef3ea856b5f6d3a86b760",
          "sha256": "66417b2a03b9e4a642a779768d7b5c7db1d86adb7f39023e0ceb11be8a32c96c",
          "sha1": "e256f00a2c3ba636b4807863e28d95d3bc1658ec",
          "md5": "58008d7aaa0724c34435851da6998373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-common-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 882725,
          "sha512": "fdc0fbc6467c35f79180733d4cccb6ebc7b78ad98b753a3e2cd278fb09fe2ace479d6cfd6684ec515a37f87631861f42a5835b4854eef3ea856b5f6d3a86b760",
          "sha256": "66417b2a03b9e4a642a779768d7b5c7db1d86adb7f39023e0ceb11be8a32c96c",
          "sha1": "e256f00a2c3ba636b4807863e28d95d3bc1658ec",
          "md5": "58008d7aaa0724c34435851da6998373"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-common-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "size": 707081,
          "sha512": "bb5eb07ac92a91faf17ecc8a931cd2c34fb46e4e150dfa78049aa127ef060320ad07449858f3860d11f5ec97cdf622014511593ac1841c1796bad3414c6a70d5",
          "sha256": "5a1ff8eb9db52db3c377c79e1244cdc16c5cc3d3a071d3e4722331c7a57e6860",
          "sha1": "3f4325dd69ccc9dc5fd4ff63674d20f4d7712409",
          "md5": "acdd642b87fa91ac7ab6ed045ac3e28b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-common-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1b9d50db0dbaa37c579386e8d33e98ef99b32e87dd807a6bb3d4bddc6fa852a511ef5820135daf87124a037cda248efde090ede8e2dc789103c4d42207105f2b",
          "sha256": "83de7c850eaf77e9104ff1a23493d7c16274b9058f31e635bb95c41d9e5e87d3",
          "sha1": "189fac460e55fb8cef01c2b71f5b56f9606b543f",
          "md5": "a24a87dbb805a3a1e0f6b40c75df0482"
        }
      ]
    }
  ]
}
