{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-26.1.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-neoforge-26.1.2-0.1.2.jar",
          "size": 2569310,
          "sha512": "6905c9133631a91cd6ef4ce25c9e396c0970e518cc48bbc77534201622db7b4dc50a4394657c703a1becbeba0d39e749a075f5956b56c3ca1d2fcfce065e3272",
          "sha256": "8540bce3c07d99e2584ea36a24ed760933cc381b780b15ccd6a923f54cfafcd4",
          "sha1": "bd62689fa22d84bc4705a533ade88637b211f968",
          "md5": "c4bbd649690752075deb4c2ee9846eb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-neoforge-26.1.2-0.1.2.jar",
          "size": 2569310,
          "sha512": "6905c9133631a91cd6ef4ce25c9e396c0970e518cc48bbc77534201622db7b4dc50a4394657c703a1becbeba0d39e749a075f5956b56c3ca1d2fcfce065e3272",
          "sha256": "8540bce3c07d99e2584ea36a24ed760933cc381b780b15ccd6a923f54cfafcd4",
          "sha1": "bd62689fa22d84bc4705a533ade88637b211f968",
          "md5": "c4bbd649690752075deb4c2ee9846eb7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2-sources.jar",
          "url": "numen-neoforge-26.1.2-0.1.2-sources.jar",
          "size": 1075150,
          "sha512": "f080cd1ab40cdf801c1f2cd073cca9bdf4e6d4fdf9a62a4abfc2b7c94eb99b9575b676eb59c6378b2814399e2b3c0732c6ed5de3eeaf8d24b3101c4b74bb0e58",
          "sha256": "26931696a8a83668ff0f3803c5aa7de5408b6cab2b84c884f05fe1cde6cbc865",
          "sha1": "38a82bedec70ed36deea15ebf3701d329c38d316",
          "md5": "8cb133d8d6e4fe332d42d7ba9d8a493f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2-javadoc.jar",
          "url": "numen-neoforge-26.1.2-0.1.2-javadoc.jar",
          "size": 5665913,
          "sha512": "a5681db0874eb1dc6b11dda0963aeecca2814ff172b3d805d491bf195fa4a1a5bb001441c9e0a5de692773936dee813bed4c83069f18ff61a7b14b9ad5149ee1",
          "sha256": "49a67e9bbad6226bf487a4427bc07b276f9329848efe61060b488a86a8d7329e",
          "sha1": "c74ccf98f550bf8583f33e3bd623e491400a10e3",
          "md5": "f176e9ad305cfe80e118e6c9d9b1935c"
        }
      ]
    }
  ]
}
