{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-26.1.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-neoforge-26.1.2-0.1.2.jar",
          "size": 2569305,
          "sha512": "e323c099e744110056f887bbc3fb64e89c7ca577458bb91ecd019dd539666ed3108e08862ef34254174dc6999673bfb771e3ee693913e4a0fa91b979e1401e44",
          "sha256": "8381b35e15951031aa369eb0d1bbf5ab044bb33ae3324dc840321956a4b57d2a",
          "sha1": "21edf1906c54224583fbf37b77b5e94929a0fbf0",
          "md5": "610a102bea86c8d4852eabcd401de0a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.1.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2.jar",
          "url": "numen-neoforge-26.1.2-0.1.2.jar",
          "size": 2569305,
          "sha512": "e323c099e744110056f887bbc3fb64e89c7ca577458bb91ecd019dd539666ed3108e08862ef34254174dc6999673bfb771e3ee693913e4a0fa91b979e1401e44",
          "sha256": "8381b35e15951031aa369eb0d1bbf5ab044bb33ae3324dc840321956a4b57d2a",
          "sha1": "21edf1906c54224583fbf37b77b5e94929a0fbf0",
          "md5": "610a102bea86c8d4852eabcd401de0a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2-sources.jar",
          "url": "numen-neoforge-26.1.2-0.1.2-sources.jar",
          "size": 1075150,
          "sha512": "680838b2e02dc37575955fd90abd344a0f204225a784794a1e036d2155a67b7504a30830a7e27bc4d6dd69b7ea10bf2edc08013e224205de258c44eb6f9219f0",
          "sha256": "f17a1a94031addcca8451e9ed20f8e6f8681c6b5acfeebdfdc9ab9c42157a013",
          "sha1": "5b485ea1acb478d1c990c21706e12256f200d0e8",
          "md5": "796c416835879f36480d6772edbad14d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.1.2-0.1.2-javadoc.jar",
          "url": "numen-neoforge-26.1.2-0.1.2-javadoc.jar",
          "size": 5665913,
          "sha512": "a5681db0874eb1dc6b11dda0963aeecca2814ff172b3d805d491bf195fa4a1a5bb001441c9e0a5de692773936dee813bed4c83069f18ff61a7b14b9ad5149ee1",
          "sha256": "49a67e9bbad6226bf487a4427bc07b276f9329848efe61060b488a86a8d7329e",
          "sha1": "c74ccf98f550bf8583f33e3bd623e491400a10e3",
          "md5": "f176e9ad305cfe80e118e6c9d9b1935c"
        }
      ]
    }
  ]
}
