{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2.jar",
          "url": "numen-neoforge-1.21.4-0.1.2.jar",
          "size": 2553851,
          "sha512": "4619dcddbf88cd3d0ea83980d5695290999399f392c337de4979bd56d9c643038ebae4c6d473ed57b648d02673a198dffa88fce43550c5f53a8a475f52a31c0a",
          "sha256": "ef0435ab47e841808c8dd52374159645eecdac5bbc59217abb2a491e9e0be6ca",
          "sha1": "d3a4c0bc880dd287f0b7cb019ee3432a8e37fc73",
          "md5": "3b446c17f2a3c9864485fb4caeb57e9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2.jar",
          "url": "numen-neoforge-1.21.4-0.1.2.jar",
          "size": 2553851,
          "sha512": "4619dcddbf88cd3d0ea83980d5695290999399f392c337de4979bd56d9c643038ebae4c6d473ed57b648d02673a198dffa88fce43550c5f53a8a475f52a31c0a",
          "sha256": "ef0435ab47e841808c8dd52374159645eecdac5bbc59217abb2a491e9e0be6ca",
          "sha1": "d3a4c0bc880dd287f0b7cb019ee3432a8e37fc73",
          "md5": "3b446c17f2a3c9864485fb4caeb57e9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.4-0.1.2-sources.jar",
          "size": 1065308,
          "sha512": "f2fa53dd826abb4e3a81ca16c5c33c55324159ef39575761f42bc8849d82e28ff6cef260e2654c3666680c2659f65b2c544d03f80c9511471391223a15f9891c",
          "sha256": "f2c0e290c478a72a7bdcd1df71d7978ca3132b230e79b9353646dffc8604f96a",
          "sha1": "4c4e0539f1db1264a89b8b8613bbdc0253b4f4a2",
          "md5": "e21bcc1ef5a18379b972201b04ce0f94"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.4-0.1.2-javadoc.jar",
          "size": 1524942,
          "sha512": "c50911bb03a163856b94af5e82888c517b79f43c3c0bfca74646e471b7e951ee56ee2cadaf1f422d6b5f70d08a6b99fd74343da96fe0beab7f346b9965ad1a8f",
          "sha256": "267d9c36509042ce5a73e322b411a93bd5ffd1c297d80ac5ba2149e84e3effc4",
          "sha1": "52b39584f91d912c68c01e99a8f1286ee6b8a806",
          "md5": "f3a548bb558b80d81f1bd2a9bc54e152"
        }
      ]
    }
  ]
}
