{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2.jar",
          "url": "numen-neoforge-1.21.4-0.1.2.jar",
          "size": 2553851,
          "sha512": "899b99531499f5ebd7460b31efb987de61ab975c3436cc8f0e01a8049d6528b0bec4adade76f13771e5cdce886945120321aaebc2dcdf58b859328cb14131b12",
          "sha256": "9c87e07ee3eefcbecdb4b144f2b9269dc1f19c4e2e8eac7eff00037718d57ffd",
          "sha1": "c90fc4c404400bcc7fceee8128e4f40bd92af996",
          "md5": "f52a75a5f1d2d3e311b04dc2858a008e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2.jar",
          "url": "numen-neoforge-1.21.4-0.1.2.jar",
          "size": 2553851,
          "sha512": "899b99531499f5ebd7460b31efb987de61ab975c3436cc8f0e01a8049d6528b0bec4adade76f13771e5cdce886945120321aaebc2dcdf58b859328cb14131b12",
          "sha256": "9c87e07ee3eefcbecdb4b144f2b9269dc1f19c4e2e8eac7eff00037718d57ffd",
          "sha1": "c90fc4c404400bcc7fceee8128e4f40bd92af996",
          "md5": "f52a75a5f1d2d3e311b04dc2858a008e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.4-0.1.2-sources.jar",
          "size": 1065308,
          "sha512": "65d7f8bc68baedf95937ce7e37f7cc001b6406d4d63f9fc2ba107391624ecdda484fdfa8f49f282f699c0a3107325889f49c46d15fc9566046c36433431018ac",
          "sha256": "6cb741201dd8f3c8620d664c822e019cf1975cc6aedc1488386e7e458664cdab",
          "sha1": "d52e289890760fc442e37a01c235a0a283d8d948",
          "md5": "b1a47ef7f8b3f86a65b6c552e69f96b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.4-0.1.2-javadoc.jar",
          "size": 1524942,
          "sha512": "c50911bb03a163856b94af5e82888c517b79f43c3c0bfca74646e471b7e951ee56ee2cadaf1f422d6b5f70d08a6b99fd74343da96fe0beab7f346b9965ad1a8f",
          "sha256": "267d9c36509042ce5a73e322b411a93bd5ffd1c297d80ac5ba2149e84e3effc4",
          "sha1": "52b39584f91d912c68c01e99a8f1286ee6b8a806",
          "md5": "f3a548bb558b80d81f1bd2a9bc54e152"
        }
      ]
    }
  ]
}
