{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 619553,
          "sha512": "fffb6704c19bdec59db04e3389318c4488b757c24b0e5aeb1cbd154c56dd5f0f2fc9c30675858e3db68b989e95b4909849d2f12c8150ed62f06728d53f091fe2",
          "sha256": "f872fdb30bb3673bb39010647fb89e8d481f54ef62d57056715529b3433d4d5e",
          "sha1": "8dcaccf8861404aa48acf12116e48d6a2052200d",
          "md5": "6b85139fee330974a0740d81a29fcbec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 619553,
          "sha512": "fffb6704c19bdec59db04e3389318c4488b757c24b0e5aeb1cbd154c56dd5f0f2fc9c30675858e3db68b989e95b4909849d2f12c8150ed62f06728d53f091fe2",
          "sha256": "f872fdb30bb3673bb39010647fb89e8d481f54ef62d57056715529b3433d4d5e",
          "sha1": "8dcaccf8861404aa48acf12116e48d6a2052200d",
          "md5": "6b85139fee330974a0740d81a29fcbec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "size": 513942,
          "sha512": "564d1c8c3d58947054a20965e17d2fb793369e33ecd03881a37e5ce9b0ad6e89a6c9d630b396dfaf0a806bafb4f20f4a51b70bf4a150bb59399f73270ac0dfac",
          "sha256": "bca012a98c066196d2dfe341657ef872345ee7744e261488c25e14c3e947e03c",
          "sha1": "add6fdbb83e794e2f70b413cd181f99b1a7446fc",
          "md5": "cee76b0a36b1c6c4cf038702f2a40448"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 762433,
          "sha512": "e2f2eb2e0c4ae1d4938bd3ce9630fe3b7a2ad797fe6550ebb9689190f8614cee99f8dca3e20a734a9251d3d419dafb3b6148cdaddfa30d4ca7a4c6125114a837",
          "sha256": "ddb872ae89d91e1b4ee3394a8961c200b5d1f43cfe8f673a190769509f2d325b",
          "sha1": "d63e87eec39a8537fd5ea1c675d359c0099faffa",
          "md5": "335afb322174e7f0f85b831feeba00e6"
        }
      ]
    }
  ]
}
