{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 619565,
          "sha512": "4da2d7874444c1fd35d6a07e0e7f6ca9c8bd651a9cbc3598a2b8822f8528d6ec4a93d86f45ef6a42621d7fa32b4b8f4cb1d0015c5a43ff90023c82fbe291f675",
          "sha256": "4cb2d54281666ce9a19b61de485fe83f95bcdd4604bd06cc516ee722f18bc38e",
          "sha1": "dbdc8657f6f4fb4210ee37cb734470d63f26ed47",
          "md5": "a796b8bcde14d9e666f84453af78cbe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 619565,
          "sha512": "4da2d7874444c1fd35d6a07e0e7f6ca9c8bd651a9cbc3598a2b8822f8528d6ec4a93d86f45ef6a42621d7fa32b4b8f4cb1d0015c5a43ff90023c82fbe291f675",
          "sha256": "4cb2d54281666ce9a19b61de485fe83f95bcdd4604bd06cc516ee722f18bc38e",
          "sha1": "dbdc8657f6f4fb4210ee37cb734470d63f26ed47",
          "md5": "a796b8bcde14d9e666f84453af78cbe3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "size": 514095,
          "sha512": "7956cce1e313117217442259527e18dc6e459baf6e89a4f459cb2069a0767f66eabf31725b4af89b2d2f6a964f4851c382acc3862210af80cb547247001fb1ac",
          "sha256": "3362169de071d703372d61355a626426764b45975baabf230f52e5dd5e70d6fa",
          "sha1": "74f55b7a29dcef9e4f76cfafb3a7dab927e2dce7",
          "md5": "c1ff2e485c4ebe2bf46e6518e2f0c949"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 762433,
          "sha512": "e2f2eb2e0c4ae1d4938bd3ce9630fe3b7a2ad797fe6550ebb9689190f8614cee99f8dca3e20a734a9251d3d419dafb3b6148cdaddfa30d4ca7a4c6125114a837",
          "sha256": "ddb872ae89d91e1b4ee3394a8961c200b5d1f43cfe8f673a190769509f2d325b",
          "sha1": "d63e87eec39a8537fd5ea1c675d359c0099faffa",
          "md5": "335afb322174e7f0f85b831feeba00e6"
        }
      ]
    }
  ]
}
