{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 594695,
          "sha512": "8f67c01d473a8bba404cd7dbbdec5d7bd86df8e067481f29046c14af4fe460973aeb44606a08a53431018e4c479da823b96ecd1e35c191448eeb3e46374781b2",
          "sha256": "29c9f44102b668c80eda2f3d36f97164adfc7a16e9a428512301f9640d64dec7",
          "sha1": "027c7e9d57fb57ebe443bce30eaca9c9583ea0e2",
          "md5": "2d9086e0c1b18e6459c7b8ff3857af95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT.jar",
          "size": 594695,
          "sha512": "8f67c01d473a8bba404cd7dbbdec5d7bd86df8e067481f29046c14af4fe460973aeb44606a08a53431018e4c479da823b96ecd1e35c191448eeb3e46374781b2",
          "sha256": "29c9f44102b668c80eda2f3d36f97164adfc7a16e9a428512301f9640d64dec7",
          "sha1": "027c7e9d57fb57ebe443bce30eaca9c9583ea0e2",
          "md5": "2d9086e0c1b18e6459c7b8ff3857af95"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-sources.jar",
          "size": 497164,
          "sha512": "3de03e61685471fc6a23a3f1200bed14ea79d10310459cbd4610bcef237967036a8863d491875bc40d4e44eb000a12f4b370bc5d0e17366f3d76f0442970dcea",
          "sha256": "4760e301b818048a5290bde55de1d81a30f55489726e055b4307756d2aab24c2",
          "sha1": "58298b5c03787740b3085e32a9a40a2aad850fb8",
          "md5": "7c149b0144ab9e51ee83ba705b0177fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 757052,
          "sha512": "5f12fe64ee628e7f325da98d3f2c7e9f7163c543cb81b569b3d2c0a28e6ac1c71d1e9b289cd384233ee69ad2a4d83fe4827a807abf3046a098f64dc7558723f7",
          "sha256": "6afceeceff85c0c38ab0a3960da3e9748c005250676b8c79f6253a5128c36b30",
          "sha1": "e01d53847e2eb1f3a43982b0349a04f541b94e2c",
          "md5": "599cfaeb01ad82f073f85fd6c14bbcdf"
        }
      ]
    }
  ]
}
