{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.6",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT.jar",
          "size": 921563,
          "sha512": "2e57f4fc461b3567e0c068f22442c89aa916c36dbf8a368a6f629418593cb8d913f339b2f66bc46892c24f7bec090defd85f4f3db27604d89323c9800bc6d709",
          "sha256": "26d655862cd09828f6a369f310a17539ebf356fd2c8ff075aa68e739ecbc2db2",
          "sha1": "f085c07483a1c299d329e3e742fe4ba9c34f0e89",
          "md5": "b5874e00f67dd3a56a1e72cedd1a281e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT.jar",
          "size": 921563,
          "sha512": "2e57f4fc461b3567e0c068f22442c89aa916c36dbf8a368a6f629418593cb8d913f339b2f66bc46892c24f7bec090defd85f4f3db27604d89323c9800bc6d709",
          "sha256": "26d655862cd09828f6a369f310a17539ebf356fd2c8ff075aa68e739ecbc2db2",
          "sha1": "f085c07483a1c299d329e3e742fe4ba9c34f0e89",
          "md5": "b5874e00f67dd3a56a1e72cedd1a281e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT-sources.jar",
          "size": 742813,
          "sha512": "b1633a893c9cc91fddb5b28b1bf70387ecc32e5eef7d68d50e2c092ea2c0723455fdbb95ae97743ccffa2a7b38947483257b0c8b06826ee3b0575d9832f044c8",
          "sha256": "1b90a06e85f414b79a0cc7509067e11e62ffb2efdca2d62d3b9a2a92ba22c9fa",
          "sha1": "27daa9bd127beb141e898ad7b5a7a6029afef7c2",
          "md5": "7f1cdc51f74e6359057561c315354022"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.6-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
