{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.4",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.3.jar",
          "url": "numen-fabric-1.20.4-0.1.3.jar",
          "size": 2491174,
          "sha512": "9ad81d16b9e215dfadb632f51ed787ca9c071f0e13b82150124e41a5cf6229e130c567b2ff7e9d833795b8d040b4ec4e0c5b610d7fecdeb495e18e519a10a76c",
          "sha256": "63a46b23f42200531ba5e14dd9f52a4f9b34ca2e816c17acbb273661fe76480c",
          "sha1": "0f723adb9873bd4211930f773e68a62fc626f5f6",
          "md5": "607aaeeb956975187f9088dc0a0a8fc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.3.jar",
          "url": "numen-fabric-1.20.4-0.1.3.jar",
          "size": 2491174,
          "sha512": "9ad81d16b9e215dfadb632f51ed787ca9c071f0e13b82150124e41a5cf6229e130c567b2ff7e9d833795b8d040b4ec4e0c5b610d7fecdeb495e18e519a10a76c",
          "sha256": "63a46b23f42200531ba5e14dd9f52a4f9b34ca2e816c17acbb273661fe76480c",
          "sha1": "0f723adb9873bd4211930f773e68a62fc626f5f6",
          "md5": "607aaeeb956975187f9088dc0a0a8fc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.3-sources.jar",
          "url": "numen-fabric-1.20.4-0.1.3-sources.jar",
          "size": 1022313,
          "sha512": "c3175b8aaad7f4381278aa38504c33d8300e104350c77f08d6e593c9e10085ad862ae7fe8493bfcb21cfb157f4b1c8f1b4daf5416ef7418a496a1afcf01a4892",
          "sha256": "a47d5ec13cf91b1bb4dbc87a47e39f7c99706fa95cabd7d572986cf644188a1a",
          "sha1": "f5650660f91ba0906452aeebf1b1ac519c6c8f90",
          "md5": "cd20543a302cee536aec58a0a36bf4c8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.3-javadoc.jar",
          "url": "numen-fabric-1.20.4-0.1.3-javadoc.jar",
          "size": 1445090,
          "sha512": "acb80ef9f0a155ea166d62f9afeaf5660ce6623ffc73e0028e8c1fb497a522f696be192cb49a7eb18235353228f7cd319b68658028389c40dfa6f39b6b5ff99c",
          "sha256": "9d1fa7d797654bdc1154d13c8e8cc6eda6f29aa8fa4776bc077c6d4e56e192f4",
          "sha1": "c9cdade53c82b9db68c0f631fbdd6722d1441972",
          "md5": "2986064607e1d16683c3ec6f561bbfb9"
        }
      ]
    }
  ]
}
