{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-26.1.2",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.1.3.jar",
          "url": "numen-api-fabric-26.1.2-0.1.3.jar",
          "size": 1363167,
          "sha512": "4bbd06b9392827f6192823b09ff5fb05fd7c19d57ecbd853571933acb4d13b30fa463bab7b836e2e25458893c98da83eba721cdfa5e9a8ece49177b0508ca6e2",
          "sha256": "c1e818fe8dc617d601a7e3696c52d273a4d3000a2dca11eb9e07afd20440027e",
          "sha1": "11cf5535ab8a1ad6bad33cc3888e4edca261bb74",
          "md5": "00c64874f2ed74a660a568e195a6307c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.148.2+26.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.1.3.jar",
          "url": "numen-api-fabric-26.1.2-0.1.3.jar",
          "size": 1363167,
          "sha512": "4bbd06b9392827f6192823b09ff5fb05fd7c19d57ecbd853571933acb4d13b30fa463bab7b836e2e25458893c98da83eba721cdfa5e9a8ece49177b0508ca6e2",
          "sha256": "c1e818fe8dc617d601a7e3696c52d273a4d3000a2dca11eb9e07afd20440027e",
          "sha1": "11cf5535ab8a1ad6bad33cc3888e4edca261bb74",
          "md5": "00c64874f2ed74a660a568e195a6307c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.1.3-sources.jar",
          "url": "numen-api-fabric-26.1.2-0.1.3-sources.jar",
          "size": 1093563,
          "sha512": "48400cf68298983142b1429d9d7bbe58014cecd41a144e81c36ef527afbf49de6cdb9353433e763eae197b9d03637c4a05557f2f127f046b06ebbe5c8307c4b9",
          "sha256": "83d473b35fcd54eac0066f9db493219c1ac0f8a6213ca70a19edeaa36a71acbf",
          "sha1": "888f555c904ca7660553892180eef201ef09f015",
          "md5": "ec5dc64b2b362c8495b5553cc36efc2e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-26.1.2-0.1.3-javadoc.jar",
          "url": "numen-api-fabric-26.1.2-0.1.3-javadoc.jar",
          "size": 5742442,
          "sha512": "a4f6301cc975a563e2bcc5c79b7363243d3c053ec0872a32036a8d295918a6aef41df8508749d59315b4802ac25ba0b03eb1bd2ebe523f594ac7e40ed65daa0f",
          "sha256": "b6f82ec0913870aef3c79224517b1aa9797392766475d4b7020954aab310ef6f",
          "sha1": "bc1af5925f19898a29774bec6ad2639bcce95f41",
          "md5": "fb9e60a2e6836814465f82fc6611110b"
        }
      ]
    }
  ]
}
