{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.1.2.jar",
          "url": "numen-api-fabric-1.21.1-0.1.2.jar",
          "size": 1336324,
          "sha512": "f8404e7bdb715530b63835ba6a5f09df88177f72afb5b75813f997fe207a6fdf3d50016d73ff627ffd39a99a1c057f7a5211ae92b1e1b7f408190ab52cf67cfa",
          "sha256": "4539ea641c31cce30ad6c2f25e359c5e4b001f41317bbc8d91068c5533aeda68",
          "sha1": "3273d45f83591b61871485420f10de521bd559ed",
          "md5": "fecdde02685186a5d4aa459e86312e03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.1.2.jar",
          "url": "numen-api-fabric-1.21.1-0.1.2.jar",
          "size": 1336324,
          "sha512": "f8404e7bdb715530b63835ba6a5f09df88177f72afb5b75813f997fe207a6fdf3d50016d73ff627ffd39a99a1c057f7a5211ae92b1e1b7f408190ab52cf67cfa",
          "sha256": "4539ea641c31cce30ad6c2f25e359c5e4b001f41317bbc8d91068c5533aeda68",
          "sha1": "3273d45f83591b61871485420f10de521bd559ed",
          "md5": "fecdde02685186a5d4aa459e86312e03"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.1.2-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.1.2-sources.jar",
          "size": 1069835,
          "sha512": "90662247a14fd45f01fb9aa73aac6a357201d39c6aa705b7a90269ac9463b51a3238048eccb932266ff191a2ebe779f3a1bb694bffef4af0ea51176beb95ea69",
          "sha256": "f3931e248a445ded7c6cb5e0a3d92af6781c819c48d00b281b7d23e108c31fd0",
          "sha1": "cbca42f334a60ec73a56bfc5a913a34533eebce7",
          "md5": "19d28cf6d25fba11784c77a5d9238b7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.1.2-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.1.2-javadoc.jar",
          "size": 1566975,
          "sha512": "00b2b68bd077e89b177c54afffa5f66ecdc7952296ddc6774a36a7d337a389fd2c320a9b017e1e5e75db610620b1bd8008e5941a2e6f1866cf845ff1b87db280",
          "sha256": "9634c7c09e38b5a170345c67e60c7217def47818a8d932c7ce0867146e322932",
          "sha1": "6305d59c0317ecea97abdb2985351806a022bfd8",
          "md5": "8ca906e4cc92725d1050d09538fe4b93"
        }
      ]
    }
  ]
}
