{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.2.jar",
          "url": "numen-api-common-1.20.4-0.1.2.jar",
          "size": 536641,
          "sha512": "fe7079ee19d988175c1a4d5147c2a6c2f3b7fb8ee1a39008942372faabede6ea4e3a5f761b18b0222518c5b037a764bcf18d67f8c6e7ce44307d9b6823ba3e9d",
          "sha256": "f0c061723f139d6c612998e3318f06aa15c5dc82ac996680227d94ee6616cb8d",
          "sha1": "409cd7341eaefc2a088b5e34551430ef64debf24",
          "md5": "e454b45de7d013105d77aabf7db8f564"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.2.jar",
          "url": "numen-api-common-1.20.4-0.1.2.jar",
          "size": 536641,
          "sha512": "fe7079ee19d988175c1a4d5147c2a6c2f3b7fb8ee1a39008942372faabede6ea4e3a5f761b18b0222518c5b037a764bcf18d67f8c6e7ce44307d9b6823ba3e9d",
          "sha256": "f0c061723f139d6c612998e3318f06aa15c5dc82ac996680227d94ee6616cb8d",
          "sha1": "409cd7341eaefc2a088b5e34551430ef64debf24",
          "md5": "e454b45de7d013105d77aabf7db8f564"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.2-sources.jar",
          "url": "numen-api-common-1.20.4-0.1.2-sources.jar",
          "size": 496892,
          "sha512": "c9fea22e8cb06397540d957180d6c86f49be8a975ca83d10d0e2204ca1b33a6a6209ddbd6d3d3ab69dc9163d746710e947855d0e61f2137892994bf33650b465",
          "sha256": "aa4fffbf6571bbd53a65cc669d5a04469b80ccc4ce2e2a7ef0f4caaf2b8baf77",
          "sha1": "ebcba12fd83f533851f00863f8e265d5cf2834bf",
          "md5": "48484ec126aa9e6e81a59265964a0761"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-api-common-1.20.4-0.1.2-javadoc.jar",
          "size": 688090,
          "sha512": "4f2543d85665e2b0910011e59628d723c11cabf152567553b2f03b85cc576334db3754416222c44d4305df745b46ac049f2a938aba59f887990f815696665b2b",
          "sha256": "ca574cf98efeba26deea211212a42427d2b9734245f6804daea7c587be129a81",
          "sha1": "9fb19d280991efb7012342671570345e2c74d695",
          "md5": "24e4bcebb644437e75147b2fe5894705"
        }
      ]
    }
  ]
}
