{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-forge-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-forge-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2.jar",
          "url": "numen-forge-1.20.1-0.1.2.jar",
          "size": 1291114,
          "sha512": "dde0d46b0240e50f23535516726733aa7c37adcdc33a2e51748888202fb17bbdf7449e9d43cca426c0b258d516c532789fa73279cc533555372697837b47cbe8",
          "sha256": "e0ae595532df1e7e1d30af047889d8d5909fe5e43573b8183cf18a14a9310413",
          "sha1": "12b7c016dc8d024fb254c560e28d7e4317343c0e",
          "md5": "fc01f9ce1a8dbc388ecada8fabb4c3fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.30_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2.jar",
          "url": "numen-forge-1.20.1-0.1.2.jar",
          "size": 1291114,
          "sha512": "dde0d46b0240e50f23535516726733aa7c37adcdc33a2e51748888202fb17bbdf7449e9d43cca426c0b258d516c532789fa73279cc533555372697837b47cbe8",
          "sha256": "e0ae595532df1e7e1d30af047889d8d5909fe5e43573b8183cf18a14a9310413",
          "sha1": "12b7c016dc8d024fb254c560e28d7e4317343c0e",
          "md5": "fc01f9ce1a8dbc388ecada8fabb4c3fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2-sources.jar",
          "url": "numen-forge-1.20.1-0.1.2-sources.jar",
          "size": 1064568,
          "sha512": "d7dd768bc1302f9f5ceb1af6a18c1e9d5ee92b67e5f992535aa079c62d61fb3d199ff9eab8380f308ce098074349c1d4a7e37265ba1a4e567ef1bff2d38b7b22",
          "sha256": "705cdd08db1a72c5e011d19eac4d4b29b7229e8ef4603fd4bf131e7bc0fdccf1",
          "sha1": "896e77c1a68c127c18e8dafae7d6a63fb86164bb",
          "md5": "cebcdba13c589c7f64e1bfdc59f05f0c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-forge-1.20.1-0.1.2-javadoc.jar",
          "size": 1485616,
          "sha512": "5db9f70a384491ff096df451c817e869243a7f0748161ca76ddf0e6dea229bfcf9a720ee3951d275640d76dde9f2308d0e8b7d88f30f1acc290a838ef126b58f",
          "sha256": "b09c5fc1d855878871eae04578bc58b68c0ac924309e1a672c667fd84f1a1a0d",
          "sha1": "9d2002e3985b0dd03f68db939880e7cc70195039",
          "md5": "7d7957602108a43fd564e7ff4de9741f"
        }
      ]
    }
  ]
}
