{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-forge-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-forge-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2.jar",
          "url": "numen-forge-1.20.1-0.1.2.jar",
          "size": 1291114,
          "sha512": "fcf3fef1d127900bcd4bfc35d2f76220fcaf5b8f8b79a54eb08753e9ffe257ae5870371b43ff9de6d24d742c7e7264fa06cf04c05e6f408e8cc2bc53d5343788",
          "sha256": "68528a65589adb9d94de7344e16d0fb6e7ccf6060592c7b8793c3b79c4298cfe",
          "sha1": "ab21dd3f8c657bbdb0eac8f025c863b6e48d5e25",
          "md5": "b0ba07f6a23c6cdc139987c96513b403"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.30_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2.jar",
          "url": "numen-forge-1.20.1-0.1.2.jar",
          "size": 1291114,
          "sha512": "fcf3fef1d127900bcd4bfc35d2f76220fcaf5b8f8b79a54eb08753e9ffe257ae5870371b43ff9de6d24d742c7e7264fa06cf04c05e6f408e8cc2bc53d5343788",
          "sha256": "68528a65589adb9d94de7344e16d0fb6e7ccf6060592c7b8793c3b79c4298cfe",
          "sha1": "ab21dd3f8c657bbdb0eac8f025c863b6e48d5e25",
          "md5": "b0ba07f6a23c6cdc139987c96513b403"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2-sources.jar",
          "url": "numen-forge-1.20.1-0.1.2-sources.jar",
          "size": 1064568,
          "sha512": "3c5f6226abdad7fd7d261253ed3e1cccec0362715e430920851b2a17ec5088cf3b0246f6784e4c5f2165237afba22d9ffeca52e55590efa731c89db8cc1ee266",
          "sha256": "d88aaab30a57ab0f9cf23febff83879693c089cb9622faac108ae9f5dc2b23db",
          "sha1": "b55bc7c65054ac38aacc1489b19d9e18ab7be930",
          "md5": "a3270a0e216fe6cab7d543e6fca48e21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-forge-1.20.1-0.1.2-javadoc.jar",
          "size": 1485616,
          "sha512": "fb3da2d15666fb28f6cf5037bca68ac817d2dd210dbcbf793840bdc6af18ba3b7d56e29d669f042eaf2451ef758b74862f0e48f81586158a4f5dadc16ce66ee1",
          "sha256": "5b1940cf52f358937a0efc1d2bc1ab59582227fa5abb751b4767c673db51b130",
          "sha1": "44a4a7457189620f0e4b2930e0ce2959f2e10ae1",
          "md5": "382cc2a0a948941c6d38b9b64d128a6d"
        }
      ]
    }
  ]
}
