{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.8",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.8-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.8-0.1.2.jar",
          "size": 1326096,
          "sha512": "51a2a7cc25c490350e2110a707c46ac8ae80fa8bf2267f55661b92b7ee25cc52a1375658d627f4aa08497bffa2bd5ae89dfeab8fcde10f517bcf0d429bcdbc3a",
          "sha256": "7f3e24318dde6352094abff37aa07181f8bfe666052e60dc1323a303609dbba2",
          "sha1": "3272c15d4cafe7f7618f6f1942c3892fdbbd11b9",
          "md5": "edbfc3707f6a5d957c73917e0e0afe21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.8-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.8-0.1.2.jar",
          "size": 1326096,
          "sha512": "51a2a7cc25c490350e2110a707c46ac8ae80fa8bf2267f55661b92b7ee25cc52a1375658d627f4aa08497bffa2bd5ae89dfeab8fcde10f517bcf0d429bcdbc3a",
          "sha256": "7f3e24318dde6352094abff37aa07181f8bfe666052e60dc1323a303609dbba2",
          "sha1": "3272c15d4cafe7f7618f6f1942c3892fdbbd11b9",
          "md5": "edbfc3707f6a5d957c73917e0e0afe21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.8-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21.8-0.1.2-sources.jar",
          "size": 1059560,
          "sha512": "fef6015473bc6a8f64d8727379611e9ebdb2a49de162a800cd83de3d6f7ff4b96f319010a388fcaf9b75d4294c730a02a25bd09430850c5f269d9a46c6b8766b",
          "sha256": "61560888d4d8f73b81bd79ba434d9bbb82f14b44f96374af89563c6ec952f6d4",
          "sha1": "59411372d6e8726cb7d0ad4f12c320b9f78cca59",
          "md5": "be5969f061f29fc03deb435437aee430"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.8-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.8-0.1.2-javadoc.jar",
          "size": 1570141,
          "sha512": "2eec66a2300c567f1ccbc094dd0fb40b6769fd388b9db44c6e0a45e8d864f2e9300147c96860306499095b8367c6df5387ddacf387691c233762b310810e670c",
          "sha256": "35b725ff3075a4f32d18ce1bc8e5927d5fcad53be4059b09decc0f4ff90b3279",
          "sha1": "d022d18e5c177bc619299dd0baadc0dc68623dd6",
          "md5": "43a88670005074705bd91389a2d04ae0"
        }
      ]
    }
  ]
}
