{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2.jar",
          "url": "numen-api-neoforge-1.21-0.1.2.jar",
          "size": 1323383,
          "sha512": "a4561534725e26f6caf8dc0c80d04e745b511ba2dc371d54248c69cc868683fbdb581a70e6a2939b55022604119c6fd15aabe87b832701820e66351d67bc7ea9",
          "sha256": "d2c0d0bd4c4574b5049b5adfde2b961ce5f534243b83528cb25b68cf80b1cef3",
          "sha1": "8828bec27d2200c01f7d37c9269699e8311af822",
          "md5": "97179fef6f0d81fb9606066762e8f964"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2.jar",
          "url": "numen-api-neoforge-1.21-0.1.2.jar",
          "size": 1323383,
          "sha512": "a4561534725e26f6caf8dc0c80d04e745b511ba2dc371d54248c69cc868683fbdb581a70e6a2939b55022604119c6fd15aabe87b832701820e66351d67bc7ea9",
          "sha256": "d2c0d0bd4c4574b5049b5adfde2b961ce5f534243b83528cb25b68cf80b1cef3",
          "sha1": "8828bec27d2200c01f7d37c9269699e8311af822",
          "md5": "97179fef6f0d81fb9606066762e8f964"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21-0.1.2-sources.jar",
          "size": 1054024,
          "sha512": "6d63799328a57f2f9684493687d7d2400446c49af20873c9704e2cab6bc66873bf1baafc133f6fa2b184f50735a9692f707be2d46291f8cf8a337358b8a81728",
          "sha256": "45f6bea50180e02be7d91af4651e95479cb71e564d3b2a2e9054e0ede3128711",
          "sha1": "16163fb7d174e845114b480c1351a46c9c1d39f8",
          "md5": "c51041b8dbf11d555728db49ceab0c3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21-0.1.2-javadoc.jar",
          "size": 1563186,
          "sha512": "54e67d2939fab45962a8dfa52096acc62a881975002a1171e008ba16fbdd92fcc0394ee6bde720731a4388d9a8881ca594231d7948d2ed511edd61a906903c12",
          "sha256": "3b861b33e9f8d9cdaf94522296740de1f03a4c64aa2867a109e40101903bc604",
          "sha1": "6d258b6f8fbbc728a94ba640e287335b6d2dcfe3",
          "md5": "f60de7cc9c20a21e9c49e60673f1c03c"
        }
      ]
    }
  ]
}
