{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2.jar",
          "url": "numen-api-neoforge-1.21-0.1.2.jar",
          "size": 1323384,
          "sha512": "8da206544bc91600e86b188930be8f91947a42bb060d0295e7439d30a82e8973e9efc666b785f4339e9a7e38da76da6bf928af791529073e19f847eded4db8a1",
          "sha256": "b02ddc69ae794478dc266e54262da40a8359609dfc1cb7c2cc02f98da02876ca",
          "sha1": "4b8af41c0635b35dd73e16c9b5226d6494a7cdf5",
          "md5": "08850783b24f8c4940203dbdcd9ede2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2.jar",
          "url": "numen-api-neoforge-1.21-0.1.2.jar",
          "size": 1323384,
          "sha512": "8da206544bc91600e86b188930be8f91947a42bb060d0295e7439d30a82e8973e9efc666b785f4339e9a7e38da76da6bf928af791529073e19f847eded4db8a1",
          "sha256": "b02ddc69ae794478dc266e54262da40a8359609dfc1cb7c2cc02f98da02876ca",
          "sha1": "4b8af41c0635b35dd73e16c9b5226d6494a7cdf5",
          "md5": "08850783b24f8c4940203dbdcd9ede2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21-0.1.2-sources.jar",
          "size": 1054025,
          "sha512": "4ff8a39d6746dab3a9a931fb623abe4473dedceb5a271b513762bfbd3be070c444230d489664603e28d3b9fe38472976abe549445d077b9b1eb251395a3a3157",
          "sha256": "7b2790ae5fb1d5a6d9328566aef1b7b0d6d55065742b818d62e67741ffd34f19",
          "sha1": "d17983ee62bbeac3a9ad7cdb0b5c53d4c33c259e",
          "md5": "af0229a8c80fc5c9d46b51863b46c3ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21-0.1.2-javadoc.jar",
          "size": 1563186,
          "sha512": "54e67d2939fab45962a8dfa52096acc62a881975002a1171e008ba16fbdd92fcc0394ee6bde720731a4388d9a8881ca594231d7948d2ed511edd61a906903c12",
          "sha256": "3b861b33e9f8d9cdaf94522296740de1f03a4c64aa2867a109e40101903bc604",
          "sha1": "6d258b6f8fbbc728a94ba640e287335b6d2dcfe3",
          "md5": "f60de7cc9c20a21e9c49e60673f1c03c"
        }
      ]
    }
  ]
}
