{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.5",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT.jar",
          "size": 542394,
          "sha512": "37c50d8f0577ccfccb9f99b9ed9d30362fe87b0e8c2be233844ce1ed2fcd2ab56dd90a9022282d72976ee1dd68be026cc6e4707be9b5b0cce45d0606784d48b6",
          "sha256": "0452198e2aa0c0e8e5839de708415e7606f18d547422ca4ed68216a3326b5b30",
          "sha1": "14768f0f99338895e298d4e69649f4ec5f7f97b6",
          "md5": "066a7ed987e0b2b4d5c3f0a888632a5c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.6+1.21.5"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT.jar",
          "size": 542394,
          "sha512": "37c50d8f0577ccfccb9f99b9ed9d30362fe87b0e8c2be233844ce1ed2fcd2ab56dd90a9022282d72976ee1dd68be026cc6e4707be9b5b0cce45d0606784d48b6",
          "sha256": "0452198e2aa0c0e8e5839de708415e7606f18d547422ca4ed68216a3326b5b30",
          "sha1": "14768f0f99338895e298d4e69649f4ec5f7f97b6",
          "md5": "066a7ed987e0b2b4d5c3f0a888632a5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT-sources.jar",
          "size": 464041,
          "sha512": "f12de7064bd1a6fb33a53888b71aaabf1153819cffb4ae9f55e246fa9314cf5d2fa1f525d51010fe656ddac30cda0f73711c9296d5677e3ade3eed249a2981df",
          "sha256": "8b9a66421b0ebd20a580cb660e624fe587834570534628018b598adfdfa5561b",
          "sha1": "583aacb78f6568f28d48ae45ac496cd86375fe62",
          "md5": "f9cd486937c574c4f39b7588f02e3d09"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.5-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 692674,
          "sha512": "a1fe7836bd55cf2cf4ffefab85b054d8ed55d63244426f3403e76cd21e39528974dadcdc389575c3e5757afe29ff190cc56cac40c4e91f70a4261115f329821b",
          "sha256": "aa611664eff2b972d1fba3c5614896c30897752744f59d06ec7171302bf1f511",
          "sha1": "37508bdfc085406f8822f3c4c9026af08e51b766",
          "md5": "77dcd8ea9f30c8c0ae89c36442a6903e"
        }
      ]
    }
  ]
}
