{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21-0.1.4.1.jar",
          "url": "numen-api-common-1.21-0.1.4.1.jar",
          "size": 1039859,
          "sha512": "fc2256028a7e7034ef87f1c7a8464a9242b461271eb469942ed6e84734cc70c0b62f0ec2c0271d237c06fdb9a6d4b320e3f694223caf9e24ecb2698209254a48",
          "sha256": "ea573e29ca0b998294d7adc30e9db557e0be7c286ae333bdf9f4a3584f159b40",
          "sha1": "189e0e8cc0fc4259f5847b49157123064d35e89f",
          "md5": "7058ef3cd2ca987807245909a25fcaee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.21",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21-0.1.4.1.jar",
          "url": "numen-api-common-1.21-0.1.4.1.jar",
          "size": 1039859,
          "sha512": "fc2256028a7e7034ef87f1c7a8464a9242b461271eb469942ed6e84734cc70c0b62f0ec2c0271d237c06fdb9a6d4b320e3f694223caf9e24ecb2698209254a48",
          "sha256": "ea573e29ca0b998294d7adc30e9db557e0be7c286ae333bdf9f4a3584f159b40",
          "sha1": "189e0e8cc0fc4259f5847b49157123064d35e89f",
          "md5": "7058ef3cd2ca987807245909a25fcaee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21-0.1.4.1-sources.jar",
          "url": "numen-api-common-1.21-0.1.4.1-sources.jar",
          "size": 784969,
          "sha512": "eeffbe18327973aa42cbc691aefdfe808cf7c579ed5c3bf66a585c269ad22f536b6f4701086bacfda804b6fd63677ad66efcde92f01dd47db567f9b995c2ef24",
          "sha256": "fb448972359ab212368748e69b33f8eda8e84f28ed2b62945d89385316aded7d",
          "sha1": "52254f69816c99a1e2f0cb134d89b428f4e69c2b",
          "md5": "b43945401d4c3ed407020681a1913d9a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21-0.1.4.1-javadoc.jar",
          "url": "numen-api-common-1.21-0.1.4.1-javadoc.jar",
          "size": 1524409,
          "sha512": "0ba114f02b0dd8ebcaa615873e19896bf93943e3fc68361d3066e5017109aedd46664ab77995460372196f80e1dc9efe16731f9e3c6cfd86890495aa4139699e",
          "sha256": "5f931cf538cfd50ede86b9c3c55d2d7a6737c790828cd07a3e04b68bc9349273",
          "sha1": "f33260cd94e74618c341f335f333d5de588f45e2",
          "md5": "b0eee6dcd7fd4764900b1759dfd434ab"
        }
      ]
    }
  ]
}
