{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.6",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT.jar",
          "size": 541532,
          "sha512": "6aa38f98a90f3a1178395958c44d8ac5ca289943845bc017229ad825721382429670ba4709c81609b9a3342b8876bf508033ce9c2e1edebc5d9aa7bd52ac6e8e",
          "sha256": "343601aec84251ac7714d518f809d6b12e4410b8b8d21dd45aa8353d8a1ab0fc",
          "sha1": "71bc23a357558d790bd35306d26d54f9866c300a",
          "md5": "fe86bf5cd0b5bd8828bf67224db53d52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT.jar",
          "size": 541532,
          "sha512": "6aa38f98a90f3a1178395958c44d8ac5ca289943845bc017229ad825721382429670ba4709c81609b9a3342b8876bf508033ce9c2e1edebc5d9aa7bd52ac6e8e",
          "sha256": "343601aec84251ac7714d518f809d6b12e4410b8b8d21dd45aa8353d8a1ab0fc",
          "sha1": "71bc23a357558d790bd35306d26d54f9866c300a",
          "md5": "fe86bf5cd0b5bd8828bf67224db53d52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT-sources.jar",
          "size": 464030,
          "sha512": "a454bc910c7fceaff81f5c7c53630189d6537c62d8ac70ca1c44db846a4463c1d0142841337e8d5dc377dcd5b3e5772196c2ecb0988df12732de30ebca7583e2",
          "sha256": "4e3152f4d768d7a054505e79d654bafa03ed6f67ce2fbb3e9d980ec72d4aeed5",
          "sha1": "7fe2bc5d88e98777c7c368f211ee8f8ed5399da2",
          "md5": "ee3ba01d739043b9dd10897832e0cb27"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.6-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 692243,
          "sha512": "1e94fc7aa1ebec9a5db84d6d8a06cf70a1669efd70377f18383653447079f4d0ba7f44a29486b09234b6ba2a3e9ece073221b6cddda453acbad3208ecd4d9e3d",
          "sha256": "b6ea47918c98158dc787100b1025af325dbda871b1da00a6d3f23e094d317511",
          "sha1": "f2f233ee366174be2cec87630616c84a7e033045",
          "md5": "4d2521369653dba6514533590cb65ffd"
        }
      ]
    }
  ]
}
