{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2.jar",
          "url": "numen-common-1.20.4-0.1.2.jar",
          "size": 1210903,
          "sha512": "90fc78ae3d7c8ee6eafc707ff5608a49696d3c0f2ee14260a1f7ed292b171b5a4bb376fe8f812c8a053d1eba49f3670f76607945a29bb20d36c8690426f3acdd",
          "sha256": "bf6c853b32471e2786185dd1dfe6e4d886debed61c619857413b0880d8f3268c",
          "sha1": "4d4147b4a23bcb76cb4b9d3b155175c4029737ae",
          "md5": "ceb575351f1a92e9273934e5abc1961a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2.jar",
          "url": "numen-common-1.20.4-0.1.2.jar",
          "size": 1210903,
          "sha512": "90fc78ae3d7c8ee6eafc707ff5608a49696d3c0f2ee14260a1f7ed292b171b5a4bb376fe8f812c8a053d1eba49f3670f76607945a29bb20d36c8690426f3acdd",
          "sha256": "bf6c853b32471e2786185dd1dfe6e4d886debed61c619857413b0880d8f3268c",
          "sha1": "4d4147b4a23bcb76cb4b9d3b155175c4029737ae",
          "md5": "ceb575351f1a92e9273934e5abc1961a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2-sources.jar",
          "url": "numen-common-1.20.4-0.1.2-sources.jar",
          "size": 1003033,
          "sha512": "f6d354a48660993be442f2e59022576f698b88fca5782776092b7a70d337a96f250e80572f7a77c2c3577c2fd468aef61a989bb79fcfc9d5694bc19583751d1b",
          "sha256": "36bc848137fce1f0fd89f8b34136ec864ad4aa48673a4ac57802880f8c3f3cb0",
          "sha1": "436374073e4fc25ffe1bf9e1da556e1c83d840e9",
          "md5": "c746976253463e052057f945e059a57b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-common-1.20.4-0.1.2-javadoc.jar",
          "size": 1428702,
          "sha512": "7b4711ba3a3b41a952af873b9dae827337d181aeac8eba70226c3ba45d9453c749e238e7cfcc3001f58780228d551936495b107858a9f9a3645b2bb0335997dd",
          "sha256": "2be4305b159209d243ffbe18d62a647d6dadfcb640d59b61b463ffcfe7a5514a",
          "sha1": "a10f4c6d2d7ef91f6109c97a674e6001989db8a2",
          "md5": "db109310f815f71bc970774cc316722c"
        }
      ]
    }
  ]
}
