{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2.jar",
          "url": "numen-common-1.20.4-0.1.2.jar",
          "size": 1210903,
          "sha512": "6dbdd30beb5b8e4f862770025072e41a72b47b5ec2a374ab5c27e13d9f89b8d561438af18e2329a4be1ba91cae4dab3a66848bf2006ec6efd3630c0c4d9546f3",
          "sha256": "bf8f56eda528be29c7bd52e0f9d4b5d3d31f201c7d47425a93a68ee1b5fe53f0",
          "sha1": "782bf581930bc2996381aeb4aec322355451d53f",
          "md5": "b14e64b4761e8501fe3b625102f1e5ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2.jar",
          "url": "numen-common-1.20.4-0.1.2.jar",
          "size": 1210903,
          "sha512": "6dbdd30beb5b8e4f862770025072e41a72b47b5ec2a374ab5c27e13d9f89b8d561438af18e2329a4be1ba91cae4dab3a66848bf2006ec6efd3630c0c4d9546f3",
          "sha256": "bf8f56eda528be29c7bd52e0f9d4b5d3d31f201c7d47425a93a68ee1b5fe53f0",
          "sha1": "782bf581930bc2996381aeb4aec322355451d53f",
          "md5": "b14e64b4761e8501fe3b625102f1e5ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2-sources.jar",
          "url": "numen-common-1.20.4-0.1.2-sources.jar",
          "size": 1003033,
          "sha512": "fc11b51b3513f4a24200b4045bd09d1483e7a4414d2586832170a0f7c9e2f4f20cae1c0f4f0fd8c4a98084ff412126dadad2256fb82c96d4f565ba94a0354706",
          "sha256": "719ae83f7b1daa4830a014b8e5adec46c03a77b0b806f1d51b60a1a0476642d3",
          "sha1": "3706c12ca7a837b675bf7f6b4fe5794811fd091c",
          "md5": "891834dab14190f2e94f1d41757a9a0a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-common-1.20.4-0.1.2-javadoc.jar",
          "size": 1428702,
          "sha512": "ebd7ffd4fa27924d43c36c3e8c181f05e7e193081f2cb7e9393e40cacbbf7a89d1975173e39bd6aa39895a0a00f9e14edc487cc175a96f10549c3f42071f361b",
          "sha256": "feaa98fde9ffbc3f7217669a94ac1f1ec087a7569f0b5e8e42a01edeccb0ccbb",
          "sha1": "6d9a6039bb8cbdf339c95163e0958afab88cf0c8",
          "md5": "9254cc5a93ef906fb7c37aa12eb4f6f4"
        }
      ]
    }
  ]
}
