{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21.10",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.10-0.1.2.jar",
          "url": "numen-fabric-1.21.10-0.1.2.jar",
          "size": 2468897,
          "sha512": "364229310d0d2cc683fdada79ab957db41e34a038858c36cc5781187f41188f485826deed1acb1624792cfb5b7c1e1fe492519d08180f80b2000aa630d84b54a",
          "sha256": "61951d2d84e98a5b926b7c3ca235a5db9fcd97b9dcc20bbdf94910fee308a680",
          "sha1": "abd8f55b2fcf87e9d1665280ade5c2aee1f3e51a",
          "md5": "3b3ecd62d92e4ded83ea0cf5cb555ae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.4+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.10-0.1.2.jar",
          "url": "numen-fabric-1.21.10-0.1.2.jar",
          "size": 2468897,
          "sha512": "364229310d0d2cc683fdada79ab957db41e34a038858c36cc5781187f41188f485826deed1acb1624792cfb5b7c1e1fe492519d08180f80b2000aa630d84b54a",
          "sha256": "61951d2d84e98a5b926b7c3ca235a5db9fcd97b9dcc20bbdf94910fee308a680",
          "sha1": "abd8f55b2fcf87e9d1665280ade5c2aee1f3e51a",
          "md5": "3b3ecd62d92e4ded83ea0cf5cb555ae6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.10-0.1.2-sources.jar",
          "url": "numen-fabric-1.21.10-0.1.2-sources.jar",
          "size": 1014984,
          "sha512": "d1c6f3df9ba69f02c8aca1a9c9ce39f2800081558b56e13e28016ab1f7374253dd58a85ef4c54f99aa89d7d1f10e1164c80452811a5fb82b65a46307c65f4feb",
          "sha256": "7faad79f310835885faa1ee16f1d71d981707fbcdecf414417492e166161c5db",
          "sha1": "5d15d1fbed2df176d42d5d59c48bf9a2e11b7bbf",
          "md5": "557813e94f69892e03ce492f1250c41b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.10-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.21.10-0.1.2-javadoc.jar",
          "size": 1483576,
          "sha512": "a09880e6bbab3b2aa5df81c92fe3a1ff045ed6fdfed3d809edaaa688bef66482be6f2d85d2111c06550574a784b43c81287480cdc87b53c81608ec709fa475e4",
          "sha256": "f18fbcd673eb2d41e26b40c951d54e31c28ca65265df90d377e71bf58be27159",
          "sha1": "d26e9b85d06222376907abbcce37aeb39e79f098",
          "md5": "d7015da0b1efadf99cdca9713c9ec21c"
        }
      ]
    }
  ]
}
