{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.2.jar",
          "url": "numen-fabric-1.21.4-0.1.2.jar",
          "size": 2464475,
          "sha512": "73e1a0c44e51393cde908a0c2dd3e1881647b9c7060e33d6b271c15708c52cc76d3f5acbb1b45e3e6a3302af4689394aa45aeb459550b3fc3c165f6f13868756",
          "sha256": "7cba0035bb4ca8636b8c6c0d954adc558d555781cbc832c0da01a9820ac4a4c2",
          "sha1": "1823bc1d5c5f64796b1747e5fadeca593b051ba2",
          "md5": "08c891bc7fb0ff55a1c9f27ffbdc375e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.117.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.2.jar",
          "url": "numen-fabric-1.21.4-0.1.2.jar",
          "size": 2464475,
          "sha512": "73e1a0c44e51393cde908a0c2dd3e1881647b9c7060e33d6b271c15708c52cc76d3f5acbb1b45e3e6a3302af4689394aa45aeb459550b3fc3c165f6f13868756",
          "sha256": "7cba0035bb4ca8636b8c6c0d954adc558d555781cbc832c0da01a9820ac4a4c2",
          "sha1": "1823bc1d5c5f64796b1747e5fadeca593b051ba2",
          "md5": "08c891bc7fb0ff55a1c9f27ffbdc375e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.2-sources.jar",
          "url": "numen-fabric-1.21.4-0.1.2-sources.jar",
          "size": 1013431,
          "sha512": "877d074b685879b9e6634176c31b1e445c5602e8333e57e6a9b13bb4c01845c2772813fb9c31f993e4efc390515552775c8035cde77c8d13b813f9c6c5cb3f15",
          "sha256": "e67a744101e26074cc074d3a2502edeb869a6adcfd423d4c93a297660ff41082",
          "sha1": "532f79e1a2ab68e68246a71c0ab764a89ff27321",
          "md5": "28801246b9b66befedf04380ed96dc1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.4-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.21.4-0.1.2-javadoc.jar",
          "size": 1483537,
          "sha512": "88e11fe0232f15eb2ecebe587980afdd626f5ab333a8f58d68b5747b3b2609666a0cd4a605fa0675247e8f3b7a14e41fbb71abdf7221a85d8850f13bd99fa4ac",
          "sha256": "92429ad6ea21bbea678ee9f2ec2a4bf128fc0d9870e53c9f26b5e1d15617d5aa",
          "sha1": "bce9f66e387a2e7a28dd640eeeab9a24cbb1e2af",
          "md5": "74be4810b9d3c3b881d74a9b29fc3865"
        }
      ]
    }
  ]
}
