{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-26.1.2",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.3.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.3.jar",
          "size": 1361729,
          "sha512": "8708b792870cd6c862f0d577cdc95f166c092ff1b8447af2f346fff94e43de33fb62d87ad4e8628d2ebb0a73deba3933926fe428ee16ca91113587effa2a7634",
          "sha256": "c50e7c5584fd4f4e305931ea912486c3e5cb7ef1e6a9f1b4408b48c0e39a9951",
          "sha1": "a66b5cfa8278cc1416b4eaab406df3b291c6af52",
          "md5": "c45641cb7e42ebcccfcf4b32308a9145"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.1.2",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.3.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.3.jar",
          "size": 1361729,
          "sha512": "8708b792870cd6c862f0d577cdc95f166c092ff1b8447af2f346fff94e43de33fb62d87ad4e8628d2ebb0a73deba3933926fe428ee16ca91113587effa2a7634",
          "sha256": "c50e7c5584fd4f4e305931ea912486c3e5cb7ef1e6a9f1b4408b48c0e39a9951",
          "sha1": "a66b5cfa8278cc1416b4eaab406df3b291c6af52",
          "md5": "c45641cb7e42ebcccfcf4b32308a9145"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.3-sources.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.3-sources.jar",
          "size": 1094861,
          "sha512": "8f57f78e586c849a76e2c580b6fed407bf97853abc32d3b15bb006062a3a79b7cc5e723e5d830d1272b9af8bed2fcf8453b227b0421820de2255d2a37a0336a0",
          "sha256": "e3d349e6a6709bab6cfda97f20dcf7fc6049ca1105541a365da4130da2e9762b",
          "sha1": "0256f10b24dc648c8588c36c6c582290c27c99ac",
          "md5": "a9153cadb6c7aa2d9c806b1eb8f9c418"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.1.3-javadoc.jar",
          "url": "numen-api-neoforge-26.1.2-0.1.3-javadoc.jar",
          "size": 5740519,
          "sha512": "b2e0f21ed99718c83a1b143aa63615ce37393ec9e666471681571c4bfe52bd2cce8f2b7567b74daf4587a576314e01a24ed29213b05d8b614945d4f1c688c0a1",
          "sha256": "7341ad8f515cb868a6cd2d9e1c488408ef13b4c166359821d1d2b4d5952bf660",
          "sha1": "7e0c7b2e83d374ea9c288b2618ed7bec154df9e0",
          "md5": "f98d61f2853f32cab153b7ac2b14d05c"
        }
      ]
    }
  ]
}
