{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.2",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "size": 909206,
          "sha512": "b7cd6c33992e5e9609007ba803b2044bf52556fab26355588e391f6e4db4d0b7ade3b633159c9bf962dbb62dd1fb4bd2c62ba9116093b1f8678b75b397e0a60f",
          "sha256": "9a9e91ed1ee259262cacd3aa37d715102cc28682abcc13201e62d049a10fb48e",
          "sha1": "5b3c0d3f32dce5223f6609e1a864a26c63d946af",
          "md5": "f2175d39155a4db5277030da77a1733a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.0+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "size": 909206,
          "sha512": "b7cd6c33992e5e9609007ba803b2044bf52556fab26355588e391f6e4db4d0b7ade3b633159c9bf962dbb62dd1fb4bd2c62ba9116093b1f8678b75b397e0a60f",
          "sha256": "9a9e91ed1ee259262cacd3aa37d715102cc28682abcc13201e62d049a10fb48e",
          "sha1": "5b3c0d3f32dce5223f6609e1a864a26c63d946af",
          "md5": "f2175d39155a4db5277030da77a1733a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-sources.jar",
          "size": 751866,
          "sha512": "a73ceddb6f007a9eba739cc21416870dc0a66ac21a7798ccf244f0b2420b8d96816b7d4ffc590f0fa1c14e17a5e5c471e812c2cd0e6ca642d01e9d8a65dd039b",
          "sha256": "7f212f04703153bf17a5bcf86aaa2f335c2621ea6b12932bdd4676d979cc3987",
          "sha1": "e413e4cfee392ee5994443297e6e45ba0d5332e1",
          "md5": "47c2738f9e30ede40902880d7eebc903"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "e2e6c17c6bed9d4dc76a10041fd39a8b052c30aa32872794c76f6447aad95d69a51fd1293e9eadb04581f99f3f9db4cb7865a8d6afd14a24d840c4b0316454cf",
          "sha256": "343789fcfcb83092e448d7dcbccd739db7d2e7306942657372dcba9757c470c3",
          "sha1": "63ed6c4b180018a388c61145e01bea4e5d8eda71",
          "md5": "a9581114705d2c414c336b976abf9a44"
        }
      ]
    }
  ]
}
