{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.2",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "size": 909020,
          "sha512": "5b0e3ee0fa15babcb1f2472e90a5862ebec9427c40b0b62ccf257d85158c4ae5cbdb979465d313f6bee7e8bb56cbc6dca292f7d0ca6e9f0d71e2b0cb09056aae",
          "sha256": "19adea342d7a6354de91839f372bdd3285aba5bf56cc8d3fc315951c74f70f2c",
          "sha1": "a1e12719f96a51f78a8677a39b4a62dd8c51ebc9",
          "md5": "4033c239091d04c4bb1a84a6e6951555"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.0+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT.jar",
          "size": 909020,
          "sha512": "5b0e3ee0fa15babcb1f2472e90a5862ebec9427c40b0b62ccf257d85158c4ae5cbdb979465d313f6bee7e8bb56cbc6dca292f7d0ca6e9f0d71e2b0cb09056aae",
          "sha256": "19adea342d7a6354de91839f372bdd3285aba5bf56cc8d3fc315951c74f70f2c",
          "sha1": "a1e12719f96a51f78a8677a39b4a62dd8c51ebc9",
          "md5": "4033c239091d04c4bb1a84a6e6951555"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-sources.jar",
          "size": 751205,
          "sha512": "09a87a97ea43d9916ed8079b1f9aaa9c1002c4d68fbede01f5ae0980f4b44e145827641c3cabd9762a95233be0ee7c94de627e46d46621830433dde71ace8418",
          "sha256": "40b7ed42d0d9519fc58af9a154ccacafdf6b7c28a7773d0864c7e3c5ddcb81b6",
          "sha1": "4756b4c5fd6df77b1f76785d6d8c37d2f34ac65a",
          "md5": "86ae29c57c258dbdc072f7e4c88db26e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.2-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "e2e6c17c6bed9d4dc76a10041fd39a8b052c30aa32872794c76f6447aad95d69a51fd1293e9eadb04581f99f3f9db4cb7865a8d6afd14a24d840c4b0316454cf",
          "sha256": "343789fcfcb83092e448d7dcbccd739db7d2e7306942657372dcba9757c470c3",
          "sha1": "63ed6c4b180018a388c61145e01bea4e5d8eda71",
          "md5": "a9581114705d2c414c336b976abf9a44"
        }
      ]
    }
  ]
}
