{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.4",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.4",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.3.jar",
          "url": "numen-neoforge-1.21.4-0.1.3.jar",
          "size": 2584415,
          "sha512": "918e88c1f48e86a582ef588a34e602eda41dec97bc344638b5173ddfc80e72af48a8b320c87c941a589983248d9907fa4c31756f8c4258b6160efd8fa814b56b",
          "sha256": "1bef71f5df7a83c3caa42b84ea5abe49eba33e4a3bbca5c06c62ba98a2b60b7a",
          "sha1": "a7ada2841822d528ab55f788971009c095cdb246",
          "md5": "1865f5c9b0fa200b6b40cb2a9439aacf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.4",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.3.jar",
          "url": "numen-neoforge-1.21.4-0.1.3.jar",
          "size": 2584415,
          "sha512": "918e88c1f48e86a582ef588a34e602eda41dec97bc344638b5173ddfc80e72af48a8b320c87c941a589983248d9907fa4c31756f8c4258b6160efd8fa814b56b",
          "sha256": "1bef71f5df7a83c3caa42b84ea5abe49eba33e4a3bbca5c06c62ba98a2b60b7a",
          "sha1": "a7ada2841822d528ab55f788971009c095cdb246",
          "md5": "1865f5c9b0fa200b6b40cb2a9439aacf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.3-sources.jar",
          "url": "numen-neoforge-1.21.4-0.1.3-sources.jar",
          "size": 1065431,
          "sha512": "a2edd68cbd5c7831c49ed7a604d6c63502218dd7823bb808952de3317d9e6ef9bcd81dada7189bb443769343ebeaa0ac19f5bbb7436527224e7ba05bffeeaf1e",
          "sha256": "042e0c0adeaee6ad8f0fd73afd8b75c67f511aa9f71f9544dfe46e26a3c27f0f",
          "sha1": "0349c1b5229062ea430ff6fba72a0a6a53e12159",
          "md5": "03a856b2720f564a018ddaf890c1baf8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.4-0.1.3-javadoc.jar",
          "url": "numen-neoforge-1.21.4-0.1.3-javadoc.jar",
          "size": 1524950,
          "sha512": "fbca77e6e0e3488534c1539317e3ea267a24bc8d7839ee94103ea88fa722a088c7745781c962c8dca2a073302227bbd795ea867606cae61bed0f4c2b89cb521a",
          "sha256": "51ec12e22f1098a41261ba75c148fc2c7ea401e51d3c76393e1364ee48861345",
          "sha1": "9e00d786dc9d426ddd3b4ec2065b5a1160b25848",
          "md5": "112928573a315a13d9f32c6ec6a6b046"
        }
      ]
    }
  ]
}
