{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-26.1.2",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-26.1.2-0.1.3.jar",
          "url": "numen-common-26.1.2-0.1.3.jar",
          "size": 1216832,
          "sha512": "7f20b5d3cf59362d6116b171a8ce48a4d1332ee265d621e90f854308a52f5e5290bde9fb994a5054cf156052cd0cbafd9785239ca960a67c43be037fa83df693",
          "sha256": "eb0ff71f09db38658d4d20c9f34d4279ce31e32725e053cf6f6c9156c5f408d0",
          "sha1": "7538370c1c26b4130e565acd7b5180be1d8e65e4",
          "md5": "993198b77059c94e59afe9e33c3e40fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-26.1.2-0.1.3.jar",
          "url": "numen-common-26.1.2-0.1.3.jar",
          "size": 1216832,
          "sha512": "7f20b5d3cf59362d6116b171a8ce48a4d1332ee265d621e90f854308a52f5e5290bde9fb994a5054cf156052cd0cbafd9785239ca960a67c43be037fa83df693",
          "sha256": "eb0ff71f09db38658d4d20c9f34d4279ce31e32725e053cf6f6c9156c5f408d0",
          "sha1": "7538370c1c26b4130e565acd7b5180be1d8e65e4",
          "md5": "993198b77059c94e59afe9e33c3e40fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-26.1.2-0.1.3-sources.jar",
          "url": "numen-common-26.1.2-0.1.3-sources.jar",
          "size": 1007416,
          "sha512": "ad4cc33bc4269cf421f9bb2fd3fb6d57f27f422109b23ae6b71d314e31732060a76911cbe70e54c7f88ed376e6f58452a27e5cee5b86111f00318d45f465b315",
          "sha256": "8dcc37f2f5926c185e07dba61ae153f48f2b45bb1980cebf5197998c996f70aa",
          "sha1": "df71683a162c75c7baa3545fdba37dee4ab65269",
          "md5": "31421fec24fc9f7dcbc53b7715abfa4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-26.1.2-0.1.3-javadoc.jar",
          "url": "numen-common-26.1.2-0.1.3-javadoc.jar",
          "size": 5596903,
          "sha512": "9ede3cd24397a38c7121c6680ba081ad2888197b77d7471bde6ba7095f1c76449974c3c049b0121187cb98785276b6d43c421fcc033a9e031c9602997ea6af66",
          "sha256": "3d86cefbdc1d8b34bc438d62d1212fa466ba3445a6fb9af136c00fd4cd8e1024",
          "sha1": "3643ea6d08789db3b089499ae2999bf9ace16d6b",
          "md5": "ae093177bdd54220d177234c95328d07"
        }
      ]
    }
  ]
}
