{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.1",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT.jar",
          "size": 925307,
          "sha512": "f2f364547791c5c3e2bf9bca95e44319f9cadb356e88daf205e475922e787cf6230392fb9156c6d756a1c996c56f3a062794f39139f0639a904edf5e8266213e",
          "sha256": "74715f75d5d4cec384eba67c0fb71f64019345974607a663b6befb843dad5ce1",
          "sha1": "2c30be4a285d842b686b23a6005d21f7b5608814",
          "md5": "4583a93d3481140646853cd3da78c754"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT.jar",
          "size": 925307,
          "sha512": "f2f364547791c5c3e2bf9bca95e44319f9cadb356e88daf205e475922e787cf6230392fb9156c6d756a1c996c56f3a062794f39139f0639a904edf5e8266213e",
          "sha256": "74715f75d5d4cec384eba67c0fb71f64019345974607a663b6befb843dad5ce1",
          "sha1": "2c30be4a285d842b686b23a6005d21f7b5608814",
          "md5": "4583a93d3481140646853cd3da78c754"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT-sources.jar",
          "size": 739815,
          "sha512": "c38e0c0b9233f4717ae3326d9c31de1fed45c2157cdc864645cf7a4b821253be38d3c2454444ab421a16a7c864f38fb943d9752e38bb10b1d90cdd9c8583b119",
          "sha256": "d4e60010876d1bd0b5343b2c7748c19a7a267b201e7c245dc1d97620927f33b1",
          "sha1": "5aad1ed05143198b2f3126841d79f9ad4dd96e84",
          "md5": "d23bb827ae7f4b474f21e9f5bdb9f3a4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
