{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.11",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT.jar",
          "size": 910638,
          "sha512": "f2843ee63808946eea4df8c18ec361e310d346e13f5041d8623a5b9fe13096016492a9b7ad48980f423487889f02da7a3d62052d8467b1955ae1d8c673d86b30",
          "sha256": "39d0287d3185a8e93266f54edb73d4ad5d0d0ace99c477ef2a43812db3227e5b",
          "sha1": "df042d6f04af9b503d5ea0848cf083383662712d",
          "md5": "91457a92b6667e050f3e775795551969"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.139.5+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT.jar",
          "size": 910638,
          "sha512": "f2843ee63808946eea4df8c18ec361e310d346e13f5041d8623a5b9fe13096016492a9b7ad48980f423487889f02da7a3d62052d8467b1955ae1d8c673d86b30",
          "sha256": "39d0287d3185a8e93266f54edb73d4ad5d0d0ace99c477ef2a43812db3227e5b",
          "sha1": "df042d6f04af9b503d5ea0848cf083383662712d",
          "md5": "91457a92b6667e050f3e775795551969"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT-sources.jar",
          "size": 732259,
          "sha512": "64af2e8fa51e66557130d0abdadf8150e9178e53e34e57282de5602f59f0fa6312b9b019dd4af824ac22c686e4c2d8f4b05078e9128d261283f1060ac134a8e2",
          "sha256": "0cc13a5bfc0c32e9d08a962d0c4634c59c626ec66758974e478fdf35dc30a09d",
          "sha1": "059702cebbb685aae98a6e52f0b360aa4d7fac3f",
          "md5": "4f17172217524d0473ea5716c7d656b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.11-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
