{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.5",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT.jar",
          "size": 975575,
          "sha512": "969959a4535d71e7da29cb51828a8d25876e163b6a551b7251b339c9356aebde070ab9375f3cf0cc5ccea3dbdef850a620162c53701408df0a9402fbae0e308f",
          "sha256": "e07f1c2829d12dbbde175c685fb882371d2b4198ede5068930d6fd81a5648827",
          "sha1": "87865aaf0ee38150205af94778caed1bb4a1430d",
          "md5": "9b4c987286bc08ce1d022ebfa5178117"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT.jar",
          "size": 975575,
          "sha512": "969959a4535d71e7da29cb51828a8d25876e163b6a551b7251b339c9356aebde070ab9375f3cf0cc5ccea3dbdef850a620162c53701408df0a9402fbae0e308f",
          "sha256": "e07f1c2829d12dbbde175c685fb882371d2b4198ede5068930d6fd81a5648827",
          "sha1": "87865aaf0ee38150205af94778caed1bb4a1430d",
          "md5": "9b4c987286bc08ce1d022ebfa5178117"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT-sources.jar",
          "size": 782352,
          "sha512": "7136993d8d9c8233de84658599442d7d2715d0cd119530492e635359696889569332ddf63ecdcf2f9c7496d72dc8d1bc13961e3d8a812d6ffc2bf61c3075861d",
          "sha256": "9c8bf7c1a7bfe326244ac0c0159a21348ed919c7039f11611b1cc6626fac2ea7",
          "sha1": "bdfe05af3f560bef9e5532e848391f86a780a619",
          "md5": "a3f0b615369377cd3e4a36a014dff4e0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-1.21.5-0.0.8-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
