{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.1",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.1",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.3.jar",
          "url": "numen-fabric-1.20.1-0.1.3.jar",
          "size": 2519357,
          "sha512": "48d0c1d76a74bb6338771db5b45231463094a24ef44f01ae799602749f1e69e9b5a41922f8d5b1f40435605a338bafda73a2b096af9dab70d1c2d54544734e9e",
          "sha256": "9174e18d051b563514ffd4ab90693b463b7d93f50b930760170045a1dea59d31",
          "sha1": "d45fdb4374b42864d823545d5e88892d3dbe71d6",
          "md5": "3ff161d8fc18e54e6a54458a79d8b793"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.1",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.3.jar",
          "url": "numen-fabric-1.20.1-0.1.3.jar",
          "size": 2519357,
          "sha512": "48d0c1d76a74bb6338771db5b45231463094a24ef44f01ae799602749f1e69e9b5a41922f8d5b1f40435605a338bafda73a2b096af9dab70d1c2d54544734e9e",
          "sha256": "9174e18d051b563514ffd4ab90693b463b7d93f50b930760170045a1dea59d31",
          "sha1": "d45fdb4374b42864d823545d5e88892d3dbe71d6",
          "md5": "3ff161d8fc18e54e6a54458a79d8b793"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.3-sources.jar",
          "url": "numen-fabric-1.20.1-0.1.3-sources.jar",
          "size": 1026223,
          "sha512": "d32e5ec45a71004305126a01b730c358c91e9e97864b42b1ecf7b57d85351e00de2148bba3d05fb09c214c8814ffb6a218b78b522a604414e2e123196ca82baf",
          "sha256": "5e0c1f601c72e978c05db1ffc54837ff6faeb0d6cff8c577709790b02cf0f730",
          "sha1": "65ca647abf56cf8698e57ca08e6cd0b789ca72f8",
          "md5": "66d71783ee683a6dc64f05ff8496c7a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.1-0.1.3-javadoc.jar",
          "url": "numen-fabric-1.20.1-0.1.3-javadoc.jar",
          "size": 1455320,
          "sha512": "f08f478e271e563cfd369f146434212b38a35dd24e4473c97a3faa709630d74b7181e3b9556c44436e980bb7100cc0db707b193c355a0fe4b9da2ebc4cf4b889",
          "sha256": "d106c769c2875094759f7e1399dc60b87bea4ad7864991e55b084aed70668b39",
          "sha1": "f7d80532cef14bbcd2fb7866cfbc3f38091736ee",
          "md5": "bca659f1da42478284f8fc86ae3e5417"
        }
      ]
    }
  ]
}
