{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-neoforge-1.20.6-0.1.2.jar",
          "size": 2550779,
          "sha512": "6e8adffe58e9faaf5c4b06d4100ddbc48ed85e17770a09f5447b5d532341aa0a74c7d9741ea6ecef7d73377955a99da075c7a35972cf8558a933f40817244447",
          "sha256": "096d38deac406b71c869cee021b5d61339c337236f3256963415fa903618ee6b",
          "sha1": "c188c22b6f3166db1fe030c659a3ccd593e1f79a",
          "md5": "30e558b3320a3f63540b4c2c5def20cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.20.6",
          "version": {
            "requires": "0.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-neoforge-1.20.6-0.1.2.jar",
          "size": 2550779,
          "sha512": "6e8adffe58e9faaf5c4b06d4100ddbc48ed85e17770a09f5447b5d532341aa0a74c7d9741ea6ecef7d73377955a99da075c7a35972cf8558a933f40817244447",
          "sha256": "096d38deac406b71c869cee021b5d61339c337236f3256963415fa903618ee6b",
          "sha1": "c188c22b6f3166db1fe030c659a3ccd593e1f79a",
          "md5": "30e558b3320a3f63540b4c2c5def20cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2-sources.jar",
          "url": "numen-neoforge-1.20.6-0.1.2-sources.jar",
          "size": 1064517,
          "sha512": "75bed694babdf486c79d60b48c3a8c759166d476940e75a358964752897a9dd1891f6f2da7f1552dbaf462f46de838e18f09ff87ff45f3c9b518443ace5750f0",
          "sha256": "3978f4218cbeb6b41339f5d196c849b97c8040528241c68b213298804b7490d4",
          "sha1": "179e952b5ea3ee9fa686ad213a5cf8ab048eec06",
          "md5": "42bd5da099dd0e27f2c03fe56aff3dd3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.20.6-0.1.2-javadoc.jar",
          "size": 1524539,
          "sha512": "e7a50f138b3cfe2483a414f6edc65c889e03f66d6cad850878ab37a3d7c737012efdaaee3550e05ec723cc9778255053de2e2049e985e3a069287884ef3b4116",
          "sha256": "2ea9292bc5a27d012f5e162a4b99d0cfa6939dfa97f01ab281772210ae16f978",
          "sha1": "7e2fe8afcaa3db874af8e9da0182f558ec362491",
          "md5": "82c8002d843f7676fbafc40fc14d3d70"
        }
      ]
    }
  ]
}
