{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-neoforge-1.20.6-0.1.2.jar",
          "size": 2550778,
          "sha512": "2daec2851d1b46662c3f0b28df2a5d61d1865769e2afdfe9fffb3bd73e31d1364b3037781941e433b959270b40d0cefdcd3af694a515bf8d812dda95e3a57085",
          "sha256": "99103fedac658ad50ebc970e7ee5dd09f0021c7235372c6a2c1e251792ab6d94",
          "sha1": "53a3574619a59d38143ebf8655807fd3cb571add",
          "md5": "7f108c201ea0ba155f76e50c5e23c5d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-neoforge-1.20.6-0.1.2.jar",
          "size": 2550778,
          "sha512": "2daec2851d1b46662c3f0b28df2a5d61d1865769e2afdfe9fffb3bd73e31d1364b3037781941e433b959270b40d0cefdcd3af694a515bf8d812dda95e3a57085",
          "sha256": "99103fedac658ad50ebc970e7ee5dd09f0021c7235372c6a2c1e251792ab6d94",
          "sha1": "53a3574619a59d38143ebf8655807fd3cb571add",
          "md5": "7f108c201ea0ba155f76e50c5e23c5d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2-sources.jar",
          "url": "numen-neoforge-1.20.6-0.1.2-sources.jar",
          "size": 1064518,
          "sha512": "0e4f53381df52fd4d0f68dd8159ecea8df6d0f02d8beaa30274cfe3540b489fa7fb3c9c8e25963ef85c71c8b4adfa420582afc906668181e28ce996098e29e06",
          "sha256": "36b984963855407217fde2caafb05a598d98bb95aeb5f3fccc9014d36f1cbc51",
          "sha1": "c30df432b5f5e6040ba2ea45ee9f952094620493",
          "md5": "eefe7c9dd118c87e1e62582e43d9a8b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.20.6-0.1.2-javadoc.jar",
          "size": 1524539,
          "sha512": "e7a50f138b3cfe2483a414f6edc65c889e03f66d6cad850878ab37a3d7c737012efdaaee3550e05ec723cc9778255053de2e2049e985e3a069287884ef3b4116",
          "sha256": "2ea9292bc5a27d012f5e162a4b99d0cfa6939dfa97f01ab281772210ae16f978",
          "sha1": "7e2fe8afcaa3db874af8e9da0182f558ec362491",
          "md5": "82c8002d843f7676fbafc40fc14d3d70"
        }
      ]
    }
  ]
}
