{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.3.jar",
          "url": "numen-api-fabric-1.20.1-0.1.3.jar",
          "size": 1357984,
          "sha512": "5c622bdd3819f2a63efc9698ecb42a8b46fdc52a6e85b967316071e5b71cb1c8822bfe4925ab894ccc7a7145a85c3488343ba81e6e9e34331d8fc90fe11a6090",
          "sha256": "b965149151d090594d6ff88358282c41a820bb780fc8c147f1f383aa3a9fbb21",
          "sha1": "92cd89e61545a4f69ffed33444d2aba1554e0144",
          "md5": "ccaffe4a79c6c68c8a5c025ecc826c53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.3.jar",
          "url": "numen-api-fabric-1.20.1-0.1.3.jar",
          "size": 1357984,
          "sha512": "5c622bdd3819f2a63efc9698ecb42a8b46fdc52a6e85b967316071e5b71cb1c8822bfe4925ab894ccc7a7145a85c3488343ba81e6e9e34331d8fc90fe11a6090",
          "sha256": "b965149151d090594d6ff88358282c41a820bb780fc8c147f1f383aa3a9fbb21",
          "sha1": "92cd89e61545a4f69ffed33444d2aba1554e0144",
          "md5": "ccaffe4a79c6c68c8a5c025ecc826c53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.3-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.1.3-sources.jar",
          "size": 1108359,
          "sha512": "06f4b21b988dc2b670f0a0f50669662ff8ee6694ed8cf1a0a75b5a5281efeea1f6a24a69ed67f61552edb3e132274731ac08bbe2976e6c8667d9e584eb5ebee2",
          "sha256": "65d830d77817bef3aa8ad423e287127c772cad237f14f73d7effba1062145ec0",
          "sha1": "4e786ba434424bf570b4f1411c139360884ab7e0",
          "md5": "6354a9ffc2f7b06c5cc8dcc631b1ef25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.3-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.1.3-javadoc.jar",
          "size": 1574910,
          "sha512": "ff97e3cf72a5c6b0b25db3a6e6ce077e44dc1a650c9b7b9435d2c76b94d73679560c5030c56b7e10ebe348bae5a1dcf48b4306f0e5a80aa1a45555bd32fc3b50",
          "sha256": "6dac78a8730204273ee76ed01275a3d0f166ef16736c0cd7aeb6ebe0e5b3c5bb",
          "sha1": "b35250a2ca285794ab9bc485e068062cb08d8230",
          "md5": "c82c52c2ba7f79dce9c8f803534728b8"
        }
      ]
    }
  ]
}
