{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2.jar",
          "url": "numen-fabric-1.20.6-0.1.2.jar",
          "size": 2462354,
          "sha512": "caa7239283f0735bd916c0c17c32a4d8e781fe1643c30a55ab2443a7c20bff9f6d2173a338abe2cec17a3f41f6a7e2490d1b2b947f40c1cf19ccbe21afdcdf70",
          "sha256": "05c66ca30602c59907c69b004908caf32650aafd75208bfdda69aa602003dd63",
          "sha1": "1db3c47a6c732a3598b63386542a1c3be438898c",
          "md5": "73f0afe02e9307c88f68924d01189f65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.6",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2.jar",
          "url": "numen-fabric-1.20.6-0.1.2.jar",
          "size": 2462354,
          "sha512": "caa7239283f0735bd916c0c17c32a4d8e781fe1643c30a55ab2443a7c20bff9f6d2173a338abe2cec17a3f41f6a7e2490d1b2b947f40c1cf19ccbe21afdcdf70",
          "sha256": "05c66ca30602c59907c69b004908caf32650aafd75208bfdda69aa602003dd63",
          "sha1": "1db3c47a6c732a3598b63386542a1c3be438898c",
          "md5": "73f0afe02e9307c88f68924d01189f65"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.6-0.1.2-sources.jar",
          "size": 1012821,
          "sha512": "ab118c64f325d798b00bd2aad23fae3c9933701845b672f46c4d9148934c22ac417d1b822d33fa38e57d780bee2f6bc6c95d64aabde97ae240600a400ca0f982",
          "sha256": "ef2473e2b34abc858307d0f669bc7bb2e8bb400c86cf5e695b0e9c0d969c1d75",
          "sha1": "fe2c3704fad5af7fe64e56206a3efd46a6930aba",
          "md5": "d89897964f6c6a2557e52d518af6ddb8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.6-0.1.2-javadoc.jar",
          "size": 1482999,
          "sha512": "ac058454a7592f7f92bb73de53b9e29de11071f7b052d9d8ea1a44db6fd5152f936cc40afaaf0f5079109d380abddefd6bacdc03274d67dd454a3d50e6bd579e",
          "sha256": "b5c84ce278511a54ee01a926c8414900b88c3d05f075899c3b96e4c9e649b440",
          "sha1": "c8bbe7f5d09484778aa9e14b041dec20b56974ef",
          "md5": "6b207420f89b5a133c6ce7f7407e4df2"
        }
      ]
    }
  ]
}
