{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2.jar",
          "url": "numen-fabric-1.20.6-0.1.2.jar",
          "size": 2462349,
          "sha512": "ab4ca3243d7e18678768716b4bbab6d3cf5a4173f68eabe00d38e6eb296c5018c86bc9a3a7fb0a82487e45076962647b7abc2395d6bf2705d267a4ce82628403",
          "sha256": "e09f14c0a6a4dadb1e59aacf68af7267b81ccd5d87c660d0002015230a92ee40",
          "sha1": "1499b9d6494766d6ea2afd4d6d1bef478828fca2",
          "md5": "7d59200f43f2980be0f1795e96bfd6f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.6",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2.jar",
          "url": "numen-fabric-1.20.6-0.1.2.jar",
          "size": 2462349,
          "sha512": "ab4ca3243d7e18678768716b4bbab6d3cf5a4173f68eabe00d38e6eb296c5018c86bc9a3a7fb0a82487e45076962647b7abc2395d6bf2705d267a4ce82628403",
          "sha256": "e09f14c0a6a4dadb1e59aacf68af7267b81ccd5d87c660d0002015230a92ee40",
          "sha1": "1499b9d6494766d6ea2afd4d6d1bef478828fca2",
          "md5": "7d59200f43f2980be0f1795e96bfd6f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.6-0.1.2-sources.jar",
          "size": 1012821,
          "sha512": "601981a68d56325da64b7b444b1248c7db0e9692cc8c8d60b8ce8474b5d1afc1477a0a54ff5dc028b5cbe19531d7cce074b7f5825d94a85177500781183a9103",
          "sha256": "cbd815b16adb61d683e52c09cb28813ddcf32a6652964e530d97cdbbd7263946",
          "sha1": "8ab04ad76f5588acc1a8480817bc75fea8a64dc3",
          "md5": "c7b72a73916d731af7e593d46f2bf4f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.6-0.1.2-javadoc.jar",
          "size": 1482999,
          "sha512": "ac058454a7592f7f92bb73de53b9e29de11071f7b052d9d8ea1a44db6fd5152f936cc40afaaf0f5079109d380abddefd6bacdc03274d67dd454a3d50e6bd579e",
          "sha256": "b5c84ce278511a54ee01a926c8414900b88c3d05f075899c3b96e4c9e649b440",
          "sha1": "c8bbe7f5d09484778aa9e14b041dec20b56974ef",
          "md5": "6b207420f89b5a133c6ce7f7407e4df2"
        }
      ]
    }
  ]
}
