{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2.jar",
          "url": "numen-fabric-1.20.6-0.1.2.jar",
          "size": 2462353,
          "sha512": "eb7c131ba7fd012263fc722894ccee974c6e382bc99ec9b9c72a60d2e9cbbabfa01ee8bde1a083f3c9080dd63a57ab3706e41f7a7588e611d63993ee81321b2b",
          "sha256": "82fdeacd3da8ac3db17919cad629b512cafe9eb9c330af6c79e7fd403e4516c6",
          "sha1": "40352e6528e463d2695337cddac22480758a650e",
          "md5": "e61c3c98778bb7b2c498b3d64d94d2b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2.jar",
          "url": "numen-fabric-1.20.6-0.1.2.jar",
          "size": 2462353,
          "sha512": "eb7c131ba7fd012263fc722894ccee974c6e382bc99ec9b9c72a60d2e9cbbabfa01ee8bde1a083f3c9080dd63a57ab3706e41f7a7588e611d63993ee81321b2b",
          "sha256": "82fdeacd3da8ac3db17919cad629b512cafe9eb9c330af6c79e7fd403e4516c6",
          "sha1": "40352e6528e463d2695337cddac22480758a650e",
          "md5": "e61c3c98778bb7b2c498b3d64d94d2b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.6-0.1.2-sources.jar",
          "size": 1012824,
          "sha512": "efd169bb4d37bec9d8be15c9a69f5e5925a350da969a3882b99f5cf3e5fbcdfab8b9f93afceb255ebbd5ccf9fb90e4d1282b1d616fae7d86686a506f718935b5",
          "sha256": "68e15f1a9b91d77741011bd70c72347cbf4abe416b1aa7c0bea4774d2917ab23",
          "sha1": "fab8e87d3f04ab0a85450241fe7223b0f3ab8a49",
          "md5": "ce121a201b447ffcb51fe8b10dfdd0c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.6-0.1.2-javadoc.jar",
          "size": 1482999,
          "sha512": "ac058454a7592f7f92bb73de53b9e29de11071f7b052d9d8ea1a44db6fd5152f936cc40afaaf0f5079109d380abddefd6bacdc03274d67dd454a3d50e6bd579e",
          "sha256": "b5c84ce278511a54ee01a926c8414900b88c3d05f075899c3b96e4c9e649b440",
          "sha1": "c8bbe7f5d09484778aa9e14b041dec20b56974ef",
          "md5": "6b207420f89b5a133c6ce7f7407e4df2"
        }
      ]
    }
  ]
}
