{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.8",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.8-0.1.4.1.jar",
          "url": "numen-api-common-1.21.8-0.1.4.1.jar",
          "size": 1038659,
          "sha512": "95f3758c921505f4457fd485915e6c9f18e7bb3aaecd75b7d45b26af48fb0107e1e2a73a562f4fec79bc03cd4386efa405560994a7fa1df9a34204fb7aa7e70f",
          "sha256": "4980e0623d987300d9a1fc48693689ea47f2d0c761abb2fed18285aa3e02580e",
          "sha1": "b48fd196452662570708998242ea5bbfb3f69901",
          "md5": "27a5d5b38700c109bc40e6fed1ef2574"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.8-0.1.4.1.jar",
          "url": "numen-api-common-1.21.8-0.1.4.1.jar",
          "size": 1038659,
          "sha512": "95f3758c921505f4457fd485915e6c9f18e7bb3aaecd75b7d45b26af48fb0107e1e2a73a562f4fec79bc03cd4386efa405560994a7fa1df9a34204fb7aa7e70f",
          "sha256": "4980e0623d987300d9a1fc48693689ea47f2d0c761abb2fed18285aa3e02580e",
          "sha1": "b48fd196452662570708998242ea5bbfb3f69901",
          "md5": "27a5d5b38700c109bc40e6fed1ef2574"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.8-0.1.4.1-sources.jar",
          "url": "numen-api-common-1.21.8-0.1.4.1-sources.jar",
          "size": 788317,
          "sha512": "7e5c8e0019831afe8d6dcd60ba20538343907b029b3abd0c04962dd58e4c7130f9d0193c174e1e2a50bb50f0758b2f6bc32a9701a5ebca61c5ce7bcba7e96b3a",
          "sha256": "66f9d886364642ea6b6de82e7ecbe83f669cff84747c2877f9ddc5fd8de40e4d",
          "sha1": "e739c1a58543c83bc8278beb10fc44a910d27709",
          "md5": "1cd2bf9ff57fe1292c67f14e387a4702"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.8-0.1.4.1-javadoc.jar",
          "url": "numen-api-common-1.21.8-0.1.4.1-javadoc.jar",
          "size": 1529520,
          "sha512": "ed14f832d7f18c3f3153295b18b74d353ecd24bdc452a7a2d1c113f9169be17c6d1cb3014e49b6962ed48cdeba7cf95ba4d108e295b7db76f97971afe6595a28",
          "sha256": "0529fdd076b551556bb7097661797e5733e6770b36201bc770a129ba071fec94",
          "sha1": "585dc4a17443c76437d392a5d93ec9fca6fcfd34",
          "md5": "abfaf5cb31a2cd97847188b7b0b0b802"
        }
      ]
    }
  ]
}
