{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.0.10.jar",
          "url": "numen-api-fabric-1.21-0.0.10.jar",
          "size": 1320013,
          "sha512": "9a957852a01a3fe2a414c28e33807fc9a39c813a4c0706a8e5ecb0fd90c424dc2eaa7b26efd64eef8089dfa25f0a2906986ee07bd7e9ad207f58f480ed59bdd1",
          "sha256": "d4a37292cf296af664dcdf67418ce22f7c196a96c8400e6cda2f03c8987e7872",
          "sha1": "c341e6e249ade3ed6419c87ad06d14eabacd315c",
          "md5": "9c6675ee0cf679c0e86d29049b2db21e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.0.10.jar",
          "url": "numen-api-fabric-1.21-0.0.10.jar",
          "size": 1320013,
          "sha512": "9a957852a01a3fe2a414c28e33807fc9a39c813a4c0706a8e5ecb0fd90c424dc2eaa7b26efd64eef8089dfa25f0a2906986ee07bd7e9ad207f58f480ed59bdd1",
          "sha256": "d4a37292cf296af664dcdf67418ce22f7c196a96c8400e6cda2f03c8987e7872",
          "sha1": "c341e6e249ade3ed6419c87ad06d14eabacd315c",
          "md5": "9c6675ee0cf679c0e86d29049b2db21e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.0.10-sources.jar",
          "url": "numen-api-fabric-1.21-0.0.10-sources.jar",
          "size": 1058401,
          "sha512": "f88b189e536877c3d5cb98b3560809ce8eceb7ecaaf19c7675080ae53268a419df6a68d76847fd8bfe3b1878bf9bb49ff473ed8ade7e7f558516fc3779ae3771",
          "sha256": "04c6637a847c133fc3c8da5331c5d184aad059ceb3336888d9ec41bdc9d0224a",
          "sha1": "c8c94c0fbcc778e0d79e1ecf5ec86df89ca1866d",
          "md5": "d639288ca2e41a45bdcc3c6a241fcfba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.0.10-javadoc.jar",
          "url": "numen-api-fabric-1.21-0.0.10-javadoc.jar",
          "size": 1565823,
          "sha512": "743511d86703198a8261e25880510fe3a9df4ad816dd217ea31598164ae17ab33b95f7fce6c3a99256bd37e0874ef69a533f48b75de6e1d3cb8298a656b0e2a4",
          "sha256": "5d44e5bb365f01159ea949e56f179a35801f89065dcf47e8318a995d24362321",
          "sha1": "4ccb3b6d890097c6d2b8ebceeea93d18bac254ee",
          "md5": "f15f1e9606388e00589465bc6d6f8e2b"
        }
      ]
    }
  ]
}
