{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.21.1",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.21.1-0.1.4.1.jar",
          "url": "numen-common-1.21.1-0.1.4.1.jar",
          "size": 1161420,
          "sha512": "106ca42633273239a7e5fd89abc86192ee6ee6bbaba902578e0a7ace182b5dd729f73c270ecc1ecbe62b7fd90369507dbdf2fe2ed8bcb6ef74f876c209dc4b36",
          "sha256": "26db7e8e053676f7fdb47b21a8ce6cafcac5945eed82dad0bd9d91cb7f22a189",
          "sha1": "da6737a6ddc0cfadd978de87e18345857716e04c",
          "md5": "7d0566f3c51f4bf56f3f4c7c0f4a0953"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.1-0.1.4.1.jar",
          "url": "numen-common-1.21.1-0.1.4.1.jar",
          "size": 1161420,
          "sha512": "106ca42633273239a7e5fd89abc86192ee6ee6bbaba902578e0a7ace182b5dd729f73c270ecc1ecbe62b7fd90369507dbdf2fe2ed8bcb6ef74f876c209dc4b36",
          "sha256": "26db7e8e053676f7fdb47b21a8ce6cafcac5945eed82dad0bd9d91cb7f22a189",
          "sha1": "da6737a6ddc0cfadd978de87e18345857716e04c",
          "md5": "7d0566f3c51f4bf56f3f4c7c0f4a0953"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.1-0.1.4.1-sources.jar",
          "url": "numen-common-1.21.1-0.1.4.1-sources.jar",
          "size": 874848,
          "sha512": "2493bff5494c023141a35fb1c0caf5eeabd710cf52a7c0285ae35361d7ea1cb7dccee1512febc4d3c49ee6ea809955b686a3b59ac0170db22df79ce67a14ed7c",
          "sha256": "64a71ef9419d9bbf97b0aceedaa2d3db5510f53bef396ef1b3360961bb784a7d",
          "sha1": "4a8bb44e089b719cecbb981f8c1066fbeabec30e",
          "md5": "22ee23ef880205e27650b793c043f9a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.1-0.1.4.1-javadoc.jar",
          "url": "numen-common-1.21.1-0.1.4.1-javadoc.jar",
          "size": 1571479,
          "sha512": "dffb23b753b142d2b9790de39336ed4b78e4150afcff96b49e0028508af39267069f2c1ea0d675c5ac69b23efd6f25a0cec616d9ae97b6bd9dabf6a2adaa61be",
          "sha256": "d7016096201a8b05b60a5812c4a2eb0d7bdcdea580c544bc1e10cca82f0ded6a",
          "sha1": "1255993672d70b5d6267d891af9e16c1f612824b",
          "md5": "dd05f5461425dc9aacc51c20ec2f2c47"
        }
      ]
    }
  ]
}
