{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-26.2",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.2",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.2",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.0.10.jar",
          "url": "numen-api-neoforge-26.2-0.0.10.jar",
          "size": 1326930,
          "sha512": "69c378333ba1b1b2664496cad5f3d3e09954f886de20e6dc7627dee81bd7fc71e8200e7202cd224169a1ce6b94b93858dfed6bc1d1bebb83ea805a4dbb74739a",
          "sha256": "a238847ff0a1b2c756726cc594b5e81fb6110421e3f7fe7c6834bb49b6175dd5",
          "sha1": "c0b487be886d651d874ddf3042cae705be2e80b3",
          "md5": "82262f8dcaa928580257debd237bb150"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.2",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.2",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.0.10.jar",
          "url": "numen-api-neoforge-26.2-0.0.10.jar",
          "size": 1326930,
          "sha512": "69c378333ba1b1b2664496cad5f3d3e09954f886de20e6dc7627dee81bd7fc71e8200e7202cd224169a1ce6b94b93858dfed6bc1d1bebb83ea805a4dbb74739a",
          "sha256": "a238847ff0a1b2c756726cc594b5e81fb6110421e3f7fe7c6834bb49b6175dd5",
          "sha1": "c0b487be886d651d874ddf3042cae705be2e80b3",
          "md5": "82262f8dcaa928580257debd237bb150"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.0.10-sources.jar",
          "url": "numen-api-neoforge-26.2-0.0.10-sources.jar",
          "size": 1060235,
          "sha512": "56269cf46588937dbae8db725a30558a1d97671680ebe54b7f90323ee7b35c89b608c1f7ea9758ce91c3114d118333fc01b13b8b9237d5fb6853e9edbaed3c67",
          "sha256": "20a46e4cf766f0789febcb049ae207874a829b9d6347b876cd81f5cc1172d361",
          "sha1": "dc745370606440288a06981b1adfcb53a6d493cc",
          "md5": "51a204caad54bac6deb06f8f316d0d6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.0.10-javadoc.jar",
          "url": "numen-api-neoforge-26.2-0.0.10-javadoc.jar",
          "size": 5694435,
          "sha512": "0d3ddaed716c3835eac9b35630b3d919886bc9d5ec0045776ad1e0fb7c4246378e19b49f4209ffe85ed1a3a9397e852dad526ef379ab78ed047b56a0692b022c",
          "sha256": "65723e97c652af82bd3ae0de37179472523fcb772a5dd5585f9454b2ec6a39a6",
          "sha1": "b632e60afcddd038803835ab3eabcc1fbd739b67",
          "md5": "bee5a2d760a15f8f51cbfe7f47546ac8"
        }
      ]
    }
  ]
}
