{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 910676,
          "sha512": "fd06f6e6a405a9ca9a42df3cfa626772a8708a70d629f7fb722ed06b59808f2094f4a552f906e383bb85877f9131ab578721c6fd8454b42c88e396b6af9c538a",
          "sha256": "3accaba2bbb644d3ea8c1365a808c2612d5a6edf6202c78dcfe7a590e890de73",
          "sha1": "12f9e227040882fa1ddbb85a9d557ca6368cd7a7",
          "md5": "44c8b7ac4ec936e914ce0ff16c206595"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 910676,
          "sha512": "fd06f6e6a405a9ca9a42df3cfa626772a8708a70d629f7fb722ed06b59808f2094f4a552f906e383bb85877f9131ab578721c6fd8454b42c88e396b6af9c538a",
          "sha256": "3accaba2bbb644d3ea8c1365a808c2612d5a6edf6202c78dcfe7a590e890de73",
          "sha1": "12f9e227040882fa1ddbb85a9d557ca6368cd7a7",
          "md5": "44c8b7ac4ec936e914ce0ff16c206595"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "size": 753634,
          "sha512": "d28ae6ade01c0af97f288c788d7608d0bb877b9051f2a24f97123ed3a0d3e92b7b81e479edae746e7c7642c249e816704e335773e2b8f379a7833bea99dfe327",
          "sha256": "86ead0b6f56a11479592734cbf1c616963c2de85845c8c2a3cb0aededc4e21fa",
          "sha1": "3dae3237640f9ee710aa5a172547edd2e6603b0b",
          "md5": "0f379b79755e74ad829298e63a0240ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "16648ec59146f8d6eb454f2d177fe7bc94dccbbc30c4c543e180a041962143cc612593154fca5ab2064133975874b8394acde503d4360d0e97c556dd02dd8e94",
          "sha256": "1d456ea2986cad45aa56f350bcd61a0802d731b0b82d0f96a7751da2208a3d4a",
          "sha1": "c47ae9aca25dca59d65dd1439dca8d7e4ea20ab5",
          "md5": "761fdbc0566aa99f76e887b07b9a4f3a"
        }
      ]
    }
  ]
}
