{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4.jar",
          "size": 2944273,
          "sha512": "0eba45b2fb6b0e706aadf27d6003a40bf8745270f85536c448654654586c63a988c1e2d9b44bdaa2225934479bd618344492dac5b1bc2ae9cb0d285a99ed88b7",
          "sha256": "f2a1c70e9d3441d1a8aa3a873cf173700c4651176b4b3285b95352dfd74a54b7",
          "sha1": "5c74e071ea3d42e247a7e2e64c8a8156cb4371fb",
          "md5": "f33c7c9ad2e244d29a0f6b2c9e298d2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.1",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4.jar",
          "size": 2944273,
          "sha512": "0eba45b2fb6b0e706aadf27d6003a40bf8745270f85536c448654654586c63a988c1e2d9b44bdaa2225934479bd618344492dac5b1bc2ae9cb0d285a99ed88b7",
          "sha256": "f2a1c70e9d3441d1a8aa3a873cf173700c4651176b4b3285b95352dfd74a54b7",
          "sha1": "5c74e071ea3d42e247a7e2e64c8a8156cb4371fb",
          "md5": "f33c7c9ad2e244d29a0f6b2c9e298d2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4-sources.jar",
          "size": 2061770,
          "sha512": "8565c80aaadf8173614ed460ed730f3ce3cad145b1525296022f5b9dc82fc4a541c857bf5492d83c34603bc5c2ed11f28c470a840b9f1371da74ebeef380e9e3",
          "sha256": "284aa1f8f0987bfe6e798dfa6e36b780947476553cba828451b4c393bab70377",
          "sha1": "b21de969308ed47a2a44ba6a2d74ad7ea9c8675e",
          "md5": "5ad1905c58d66f355b4e3d5208d33f83"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4-javadoc.jar",
          "size": 2494221,
          "sha512": "3b6dd498a554c0d32437777069a4552f4a494cf5f71b9ae60fcd02699053dd9b9ebdb779333510ce20341136aa7c7bb8246583554328e798137084009eb7e568",
          "sha256": "10366de5e4ca2c7f4fdb8f2ec7fa4b1cefeb1496240ded10a74e708ced98fd13",
          "sha1": "28effd9f268b01d7dfcd3493f37703118644cb05",
          "md5": "5c4ab8759f1d052626d89892edd8df37"
        }
      ]
    }
  ]
}
