{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-forge-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-forge-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2.jar",
          "url": "numen-forge-1.20.4-0.1.2.jar",
          "size": 1291915,
          "sha512": "7fe6f774739c2a6a23529ff9bad29a0989de114cec00621bd5c669bdb1c18f5aa539e4f3777b77f48eae36f356a8543ba2922b9b099a8b0131b8525f2dca7018",
          "sha256": "88a602acb39f98ba63cca7d724892ffbb56aa11de472e858ad57768fc2043fda",
          "sha1": "4c3fb278d9988d31b42e26603adfd5c72450af7f",
          "md5": "c2482c448266970819698f0874ee4c3f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.4-49.0.19_mapped_official_1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2.jar",
          "url": "numen-forge-1.20.4-0.1.2.jar",
          "size": 1291915,
          "sha512": "7fe6f774739c2a6a23529ff9bad29a0989de114cec00621bd5c669bdb1c18f5aa539e4f3777b77f48eae36f356a8543ba2922b9b099a8b0131b8525f2dca7018",
          "sha256": "88a602acb39f98ba63cca7d724892ffbb56aa11de472e858ad57768fc2043fda",
          "sha1": "4c3fb278d9988d31b42e26603adfd5c72450af7f",
          "md5": "c2482c448266970819698f0874ee4c3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2-sources.jar",
          "url": "numen-forge-1.20.4-0.1.2-sources.jar",
          "size": 1065661,
          "sha512": "4819e78787c86bd6a4abef08778d79e872f1d7297e263f030eb4778c3a3d0fa7c0181494d2083341218844b9416d0c0bf8d278c0cbdc769631ec6977b48c060f",
          "sha256": "1d43d0101d721c7867a1ed3ba22e3167912445e6334678aa878f74f7361d2ba5",
          "sha1": "900108355759bce741df0c878b850b4fc61c2d2c",
          "md5": "b1eca28a6d5dd14d6c61503dd61b926d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-forge-1.20.4-0.1.2-javadoc.jar",
          "size": 1486157,
          "sha512": "4004316b4eeaab50221da2f1b558226eda22c72e352dacef2e48de0fe7747e61426cc7c4ffe1ade2f958f63dfe302fe97aaeaea26a801561cb06f6962fd12727",
          "sha256": "68f5935cda7814fa929e92d5a387ecc1fd03b995585c6cfd7abf91699715480a",
          "sha1": "cc9dd8c01b3371387366c6f2d4497546ea623b57",
          "md5": "98a39ac8982c4a9d599fe08341b1f942"
        }
      ]
    }
  ]
}
