{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-forge-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-forge-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2.jar",
          "url": "numen-forge-1.20.4-0.1.2.jar",
          "size": 1291915,
          "sha512": "1e6abcffd5cabefdaf4d187d7aaa9f56b277a57fc0a31053b094a77c37f93613ca770b3a311a01eff74f8dc668b706698181dd2adb0b5a681bc4633eb04f60e7",
          "sha256": "79c6decdaf7f773fefd2ff94b2fabdcc423a2acad4de1027b021a0d15196697b",
          "sha1": "451c0477711d0ebc04eef8b4e916d413956c179a",
          "md5": "91c9efd010e57c5543026850b68baff7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.4-49.0.19_mapped_official_1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2.jar",
          "url": "numen-forge-1.20.4-0.1.2.jar",
          "size": 1291915,
          "sha512": "1e6abcffd5cabefdaf4d187d7aaa9f56b277a57fc0a31053b094a77c37f93613ca770b3a311a01eff74f8dc668b706698181dd2adb0b5a681bc4633eb04f60e7",
          "sha256": "79c6decdaf7f773fefd2ff94b2fabdcc423a2acad4de1027b021a0d15196697b",
          "sha1": "451c0477711d0ebc04eef8b4e916d413956c179a",
          "md5": "91c9efd010e57c5543026850b68baff7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2-sources.jar",
          "url": "numen-forge-1.20.4-0.1.2-sources.jar",
          "size": 1065661,
          "sha512": "316822999c5b89dc5b07b4f6e6b94fed123ea1655f8157dbc10d59a609aa10e8f44d640b1c1a035535d628cd52e2126a8a238de536867a2a95b23a33113684b6",
          "sha256": "e0f529824f6f3a24b19e1bebcfea04d1e08593c4873b78d0375512031e4f5572",
          "sha1": "1599b540231a9dba248a036103e641410d2be948",
          "md5": "406a78a7a9d6a4c1304b421550f44445"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-forge-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-forge-1.20.4-0.1.2-javadoc.jar",
          "size": 1486157,
          "sha512": "196148b85178f5e2b0b4a85f6ae4c479eaf51ba1b54411bce842f26e45f0ac35fa5f502e0c05f38021917eb17d72fdc2110c8acbe631673d8d80fc389b832b1b",
          "sha256": "958b805ce114c82b5f16614512111774ffe2420511b32cc6c42f79bc52da11af",
          "sha1": "f0f15fe068deac098c366798726099ecdf547c99",
          "md5": "5c95484eaf55c108086c4cd4bf5c5032"
        }
      ]
    }
  ]
}
