{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-forge-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.2-0.1.2.jar",
          "url": "numen-api-forge-1.20.2-0.1.2.jar",
          "size": 1323481,
          "sha512": "bd6a16f7bd26a1a3291f272aa70aea5ad6d29cdea255face0d7a850b0ecabca78841b5546cc798d13e8de69d2ff707ef1d9b8cd27604a274f668881ed6dd4645",
          "sha256": "a8c512a59e365111e3223405766446787403fc49020e8777948ac6bd1d785e5c",
          "sha1": "a9ef08c805939ea15119bf4ff708779be6dd6343",
          "md5": "b99ee751120dbc4a93cac805e89211d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.2-48.0.49_mapped_official_1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.2-0.1.2.jar",
          "url": "numen-api-forge-1.20.2-0.1.2.jar",
          "size": 1323481,
          "sha512": "bd6a16f7bd26a1a3291f272aa70aea5ad6d29cdea255face0d7a850b0ecabca78841b5546cc798d13e8de69d2ff707ef1d9b8cd27604a274f668881ed6dd4645",
          "sha256": "a8c512a59e365111e3223405766446787403fc49020e8777948ac6bd1d785e5c",
          "sha1": "a9ef08c805939ea15119bf4ff708779be6dd6343",
          "md5": "b99ee751120dbc4a93cac805e89211d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.2-0.1.2-sources.jar",
          "url": "numen-api-forge-1.20.2-0.1.2-sources.jar",
          "size": 1054588,
          "sha512": "ba54279a79936055285cf45f4b9cb6476fad787230fb659a6ca884a30c19058176367fae33954ad1b62dffb215744ca019330c9fd816789c2c757598bff6d91c",
          "sha256": "56e31f57fa5a6c4d1a9f60ab6cc83e842af94aa3b24f5381bf7eb019e883eb49",
          "sha1": "2431e4ec6bf257285596858bda89b6f5e14d00ce",
          "md5": "7182d2e110ea6b20a86bf40af14bcfa8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-api-forge-1.20.2-0.1.2-javadoc.jar",
          "size": 1516274,
          "sha512": "5c34aee1c1d4c34329ccc76c3252e367ec3f1baf154f4279d0903d932ba78b81b460aaecceb770e16b97d0cf4fffdbb509c693e925c726eb28d644129bb3df69",
          "sha256": "f9d781c4f7b00bf881d22e203586aaf1be450d8d66f0b4847b4c5f8910f9dcb9",
          "sha1": "f1beebdb3f996abbba34579e16120e1481018587",
          "md5": "d4c7d942589440369420719ea8420515"
        }
      ]
    }
  ]
}
