{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-ai-1.20.2",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-1.20.2-0.1.3.jar",
          "url": "numen-ai-1.20.2-0.1.3.jar",
          "size": 79427,
          "sha512": "4397a2596313fc516776618121bdbc80404d65b8b028942adfdebf0b330d515afa13d1fc5f2755d8ae333474b24bfb796445d9be46542fac71eca70afe25703b",
          "sha256": "f6d153c3f45caa229823b59e4be391f87d6ca201035953493dff821592969111",
          "sha1": "bbd76a96b2f53ea00effc4fea43b4063883117a3",
          "md5": "a73a1a5514ee49b7473acee9fba2c383"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-1.20.2-0.1.3.jar",
          "url": "numen-ai-1.20.2-0.1.3.jar",
          "size": 79427,
          "sha512": "4397a2596313fc516776618121bdbc80404d65b8b028942adfdebf0b330d515afa13d1fc5f2755d8ae333474b24bfb796445d9be46542fac71eca70afe25703b",
          "sha256": "f6d153c3f45caa229823b59e4be391f87d6ca201035953493dff821592969111",
          "sha1": "bbd76a96b2f53ea00effc4fea43b4063883117a3",
          "md5": "a73a1a5514ee49b7473acee9fba2c383"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-1.20.2-0.1.3-sources.jar",
          "url": "numen-ai-1.20.2-0.1.3-sources.jar",
          "size": 65211,
          "sha512": "205deaa3813027e7a25b505635afcb3454cd6e1c6d25963300bb5fd2fdfc869a73da165bc8d7d6ce49429850de6774b94222f701820a69529c0b602884e7b600",
          "sha256": "f26dec59354644e79f22b34b31c221634f7c926e068f9e5cdfcc7149fb81dd4d",
          "sha1": "b9a94ecfa7896b81e033102fbe19e821385f1879",
          "md5": "0602c7c9cb279652d6592184933dbf03"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-1.20.2-0.1.3-javadoc.jar",
          "url": "numen-ai-1.20.2-0.1.3-javadoc.jar",
          "size": 254335,
          "sha512": "c118b4d3532310d98e8b5c64c48eccd81385387f5453f27c001670f5d748c3cd4ed51b47841cfa0b706b1beee8dd7e1ab25a95f3a2e0474af922295169b0f70d",
          "sha256": "8da66b429fa3329e94fd7115a7524a95c499bec26d54150cf37fc87127630840",
          "sha1": "b5b1af61246aa2e99d5029c2d32222953d594b71",
          "md5": "2f0b1986739e873750d42f3aa1f7aed4"
        }
      ]
    }
  ]
}
