{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.11",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2.jar",
          "url": "numen-neoforge-1.21.11-0.1.2.jar",
          "size": 2567667,
          "sha512": "88c3e2c94cfcfde98f46725f22fcda32bf621150690d1f11278680db9563105bee290f8a43e64e154c3dfb7e10d74a2c45660d887ce8b327066211adb019b84b",
          "sha256": "7a9c12a28bfe4a5c32be10bba2c51768dec64dab37e6c4f4e5eba1a7975c8a15",
          "sha1": "96a0c214909f5a4d58ed238658a1011b6ba43133",
          "md5": "34680e1d18ea77efc3d9cbc1354a577f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2.jar",
          "url": "numen-neoforge-1.21.11-0.1.2.jar",
          "size": 2567667,
          "sha512": "88c3e2c94cfcfde98f46725f22fcda32bf621150690d1f11278680db9563105bee290f8a43e64e154c3dfb7e10d74a2c45660d887ce8b327066211adb019b84b",
          "sha256": "7a9c12a28bfe4a5c32be10bba2c51768dec64dab37e6c4f4e5eba1a7975c8a15",
          "sha1": "96a0c214909f5a4d58ed238658a1011b6ba43133",
          "md5": "34680e1d18ea77efc3d9cbc1354a577f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.11-0.1.2-sources.jar",
          "size": 1074371,
          "sha512": "fd08680e7fc307314f594e95649cf672b46c7e855a3822ed7260f815496d5789a97e1921dbc356fd9bb87985ee407a040f754da08cf8ba61f95b24ffa28db482",
          "sha256": "8fb070b3dcdd240896c095679523a945266c3e6e7a5fb488f310f3be7a14f0b7",
          "sha1": "c5f1282da74ee0d18c0caa97296f18b9784bc500",
          "md5": "e669f58c07040a96880c4a122a14994b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.11-0.1.2-javadoc.jar",
          "size": 1540113,
          "sha512": "61b09ffeef3be6b1e5087ac802f28374d41cc7c37a0b545398c9e6d06b9e020e06067af4d1f354a96287938e6fa54424de5e3729104158de7adeead16444cb4d",
          "sha256": "06c9efb5c4354a0b7e697b85f421a82966735820d284fc0fde1bdbe838527120",
          "sha1": "c90f40aec717993fba3a9088da2c4fb18c5bb4fa",
          "md5": "049efccb5e47a344ac64bdfce6643587"
        }
      ]
    }
  ]
}
