{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.11",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2.jar",
          "url": "numen-neoforge-1.21.11-0.1.2.jar",
          "size": 2567673,
          "sha512": "434917dcf68fbf192ad8cfb6fdf5580a17fa5bbce6713351a53a486be3fe1cabc27e899fbb6469c55ce20f242d82ba661ddfc4d330484a942fb8003ff1cc18cd",
          "sha256": "533f73645614dc830b4d98d9d41250efe968886f2ba4a7a93d3e9b6f47af799c",
          "sha1": "49092e0f73bbc3d32f53ebb51dd2bd4d17a5eaa7",
          "md5": "2f233cf3a6c649065ec3c2d33df01512"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2.jar",
          "url": "numen-neoforge-1.21.11-0.1.2.jar",
          "size": 2567673,
          "sha512": "434917dcf68fbf192ad8cfb6fdf5580a17fa5bbce6713351a53a486be3fe1cabc27e899fbb6469c55ce20f242d82ba661ddfc4d330484a942fb8003ff1cc18cd",
          "sha256": "533f73645614dc830b4d98d9d41250efe968886f2ba4a7a93d3e9b6f47af799c",
          "sha1": "49092e0f73bbc3d32f53ebb51dd2bd4d17a5eaa7",
          "md5": "2f233cf3a6c649065ec3c2d33df01512"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.11-0.1.2-sources.jar",
          "size": 1074370,
          "sha512": "33a05289d10061229711a17f10c91ca48c019b194a1cac713ce28082b4c900424e985210cb83dcfe25c2aefebe8f07504d6478dd1655453132d4cce4fce5384f",
          "sha256": "376edd4872bd99407ef23719d8865aa86c3e994e561fecdedea82d14444ed5f0",
          "sha1": "cada05b25d546d6a61ae92088081b29cddf13bd5",
          "md5": "e698d7fc26ce87efd878941d83a9927c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.11-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.11-0.1.2-javadoc.jar",
          "size": 1540113,
          "sha512": "61b09ffeef3be6b1e5087ac802f28374d41cc7c37a0b545398c9e6d06b9e020e06067af4d1f354a96287938e6fa54424de5e3729104158de7adeead16444cb4d",
          "sha256": "06c9efb5c4354a0b7e697b85f421a82966735820d284fc0fde1bdbe838527120",
          "sha1": "c90f40aec717993fba3a9088da2c4fb18c5bb4fa",
          "md5": "049efccb5e47a344ac64bdfce6643587"
        }
      ]
    }
  ]
}
