{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2.jar",
          "url": "numen-common-1.20.2-0.1.2.jar",
          "size": 1210899,
          "sha512": "d3f81b855c4f790b2c95284e063c7f11c9fc67f534c1e21e3bf5f2f11cf46b9385d03a6bf0662e5d017b5fa8e55a88c903466ffe4280097d084e37695ac781f5",
          "sha256": "ceeb96cf53c3ee339e5b0ba8e5d96da9d2d623fae6947239ed8335c93d44cb78",
          "sha1": "90f5463d552bee47964ee0c8da354d023bb1ddf5",
          "md5": "34b9a0f461acaaee1cd797f8bbb29e53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2.jar",
          "url": "numen-common-1.20.2-0.1.2.jar",
          "size": 1210899,
          "sha512": "d3f81b855c4f790b2c95284e063c7f11c9fc67f534c1e21e3bf5f2f11cf46b9385d03a6bf0662e5d017b5fa8e55a88c903466ffe4280097d084e37695ac781f5",
          "sha256": "ceeb96cf53c3ee339e5b0ba8e5d96da9d2d623fae6947239ed8335c93d44cb78",
          "sha1": "90f5463d552bee47964ee0c8da354d023bb1ddf5",
          "md5": "34b9a0f461acaaee1cd797f8bbb29e53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2-sources.jar",
          "url": "numen-common-1.20.2-0.1.2-sources.jar",
          "size": 1003150,
          "sha512": "ab504cfff38152e97d90634e5b16392a5719caf14ecfbbfc6a6005a0e0c7e7a849ae77fd5ed4215e39b75ab5227623c631b5bae6279ca395de83e7606899144c",
          "sha256": "f39e747dcdecdb156f04ca9f6481e37bb35baa75f7a222d1ab9fe390c2435903",
          "sha1": "2127d9d7eb470539882ef1c2c49fe04e0d5e8956",
          "md5": "a6be0cdae6595445bb74ce0be00dc955"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-common-1.20.2-0.1.2-javadoc.jar",
          "size": 1428702,
          "sha512": "2e437060ca785b67c9a6ecbfd01298bc30e71a708d6b933daa811824d6525c953d94d65b9d5463b358369b8bc4101b8e0934bc826d7c1ce6300defead1bc001c",
          "sha256": "6c8daeec8873ab1fee1c3ccd8122b8639ac63747bcb819eb719f4d2ea2355947",
          "sha1": "e65406700fd428c93cafcfa5bf1d756c6bafc739",
          "md5": "dbaa0913f84621b5b367c0cef889314e"
        }
      ]
    }
  ]
}
