{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2.jar",
          "url": "numen-common-1.20.2-0.1.2.jar",
          "size": 1210899,
          "sha512": "399d6e3d58c7f8cb0cd3779311f2e4ced5238bf4117c81692cea85508fc81c1bb82a863b999910ef3c28209043b5e59c10cb1bf3814d27716e87cdaa3c1e5b4a",
          "sha256": "925c37460ff75f03a85e372c60db0343d4f78fb15167ab02ff9fa9595f93d07e",
          "sha1": "efc430e5780e3278e43c367b9ef67556bd190e4d",
          "md5": "a7960dbdf3b7f51d46c427740d5570f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2.jar",
          "url": "numen-common-1.20.2-0.1.2.jar",
          "size": 1210899,
          "sha512": "399d6e3d58c7f8cb0cd3779311f2e4ced5238bf4117c81692cea85508fc81c1bb82a863b999910ef3c28209043b5e59c10cb1bf3814d27716e87cdaa3c1e5b4a",
          "sha256": "925c37460ff75f03a85e372c60db0343d4f78fb15167ab02ff9fa9595f93d07e",
          "sha1": "efc430e5780e3278e43c367b9ef67556bd190e4d",
          "md5": "a7960dbdf3b7f51d46c427740d5570f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2-sources.jar",
          "url": "numen-common-1.20.2-0.1.2-sources.jar",
          "size": 1003150,
          "sha512": "f81822dc0dac726e68e2178d826b39426c600a441b17337a960d49742926fa5d0a100be1ac6e9e3b195a72c403b69c7e8f6153c2809e42b3c19cf40de8c95450",
          "sha256": "39587fd37e27047e854e5636f54b02383d9494a13186a6faa841a14184c02c45",
          "sha1": "a163aa15282963725a0c6921f854fe1524085ce1",
          "md5": "0e3c16c91d27e99fe85aed9e039d6b97"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-common-1.20.2-0.1.2-javadoc.jar",
          "size": 1428702,
          "sha512": "6380d738f563412852f4baaf17e884e5713138ea668e6a846867e08fbdc5b8ac11def7ffc48ecdb77429f2aa784dd94b5106cfcf2c78a98739c55941c77508ba",
          "sha256": "832ad47408a1fe7c9b7be6d46d5195faff331d7cfc094c3a744085ee84a213f7",
          "sha1": "bb4bdd061b63721f5cb46a05087bea45d6236a0f",
          "md5": "18c6f8ae2d039c7ebf2932574fadebba"
        }
      ]
    }
  ]
}
