{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2.jar",
          "url": "numen-common-1.20.2-0.1.2.jar",
          "size": 1210899,
          "sha512": "a8df93fdf597f371e097fe5e40e4e1a3780fd2054716c853f832bafe43c04ba2bad302a1dbe19f85efbd53157aeb7846a8dba40b6cbecaa8fe51e7eb7f456623",
          "sha256": "dde3ddb81150c4046ee09585034076e207e3403fa9d0d52f2589a2e6b7bec4eb",
          "sha1": "0223fcb86f2b4d8f3e316d9474791308ec840f9f",
          "md5": "6a252788aaeee446ccdcdfc2566349c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2.jar",
          "url": "numen-common-1.20.2-0.1.2.jar",
          "size": 1210899,
          "sha512": "a8df93fdf597f371e097fe5e40e4e1a3780fd2054716c853f832bafe43c04ba2bad302a1dbe19f85efbd53157aeb7846a8dba40b6cbecaa8fe51e7eb7f456623",
          "sha256": "dde3ddb81150c4046ee09585034076e207e3403fa9d0d52f2589a2e6b7bec4eb",
          "sha1": "0223fcb86f2b4d8f3e316d9474791308ec840f9f",
          "md5": "6a252788aaeee446ccdcdfc2566349c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2-sources.jar",
          "url": "numen-common-1.20.2-0.1.2-sources.jar",
          "size": 1003150,
          "sha512": "2254c29727116b71d367fad37e292115f5c7f9eb3d06dbb1ddf190cc4187e4bee168b5f32729a048ac5261273c2940972f49305bfba78a74a8b1d9035b7643f6",
          "sha256": "ef67b173941609ea3cecebeec0729884c4e0981f7cc5d2598b4b1d14ed3f64a0",
          "sha1": "f25e4714d6430824ea96dc2283e43d81a142a91a",
          "md5": "aef4c7c25bd4f2ee543bd14e73fa7421"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-common-1.20.2-0.1.2-javadoc.jar",
          "size": 1428702,
          "sha512": "2c47953ee0ea28938d403becba724bb3517ed193ac21bacf40ce67485ebc7ac100bd098d05c0f21c4af61b93d95a0793a4dc5365058329127deebaababda0d79",
          "sha256": "21bdbc3ee8ac730615e30d7210f830d9abff824544947a5d68576a9ca48e197d",
          "sha1": "7d69222f87534966bd0c7e1fd1de9ede6c29b15c",
          "md5": "be00493651a8ec44252df66126c8e1d0"
        }
      ]
    }
  ]
}
