{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "size": 810347,
          "sha512": "8dafb8534ed58ab1c1d9e00e595a6173c4001b3e59c2a7ab25e2b8eaf3a784c820f912d70b32f1a2697275ba3f29d96ff7d31ed1951169bc73cc2c850a6345fd",
          "sha256": "200c2a66c001314cdf80321a0a99335badaafdb6fdd2d0c373176166737df661",
          "sha1": "34f2729c202cebf64ad426493dbe19d0454a454e",
          "md5": "1d1a4d20a3c979f3105ccf78841ef026"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "size": 810347,
          "sha512": "8dafb8534ed58ab1c1d9e00e595a6173c4001b3e59c2a7ab25e2b8eaf3a784c820f912d70b32f1a2697275ba3f29d96ff7d31ed1951169bc73cc2c850a6345fd",
          "sha256": "200c2a66c001314cdf80321a0a99335badaafdb6fdd2d0c373176166737df661",
          "sha1": "34f2729c202cebf64ad426493dbe19d0454a454e",
          "md5": "1d1a4d20a3c979f3105ccf78841ef026"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-sources.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-sources.jar",
          "size": 665165,
          "sha512": "1ea7e2f2e82657cbc87c876f9c1bf20dd59fa4e05771640363089ca633032e786d7aaf23d2a96e0f3ab2c24f426f931de5a2506b2120706c10286a123d759dff",
          "sha256": "350de1e73f54fe592e34b8a3f33851a5bf0c9e5aa2e4672d4a990425b67429b0",
          "sha1": "044f20dfc5157e71c9ffc95ed7199690fc18b610",
          "md5": "b16cb6ce22cd75c789f56828f64742f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-javadoc.jar",
          "size": 1077693,
          "sha512": "db6759a5fdc893983618457eb893ce6c4e48f7d67235298aef47edba7b13df464d1f6012155878a223d83019f146572b44a393e9fe511536bca4105828db93af",
          "sha256": "164df89d90b819c775805990e81031be0eea8302b97436e71cef8bb32519d530",
          "sha1": "514d966b3020165e949d3dbd97610de341190273",
          "md5": "5f4e185660bccd571bc3b552d301113d"
        }
      ]
    }
  ]
}
