{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "size": 680190,
          "sha512": "a754162d4c3e102fb44e3b978e2c57307976ccab343f2628e860b3f1c061ca789ce51ea75d0a7beb4c3b2970fd710d40383a29ea44e3a8df6d670db02828af64",
          "sha256": "9e172fcf1bda8595dc8f7dd28bd48cc5b6984a0a6c7d69269063ed00b3681036",
          "sha1": "9e44576a79b1e4d81279c2b6fb29bbfe1f516721",
          "md5": "206a3f451e079b7ed2930098f6f32f62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "size": 680190,
          "sha512": "a754162d4c3e102fb44e3b978e2c57307976ccab343f2628e860b3f1c061ca789ce51ea75d0a7beb4c3b2970fd710d40383a29ea44e3a8df6d670db02828af64",
          "sha256": "9e172fcf1bda8595dc8f7dd28bd48cc5b6984a0a6c7d69269063ed00b3681036",
          "sha1": "9e44576a79b1e4d81279c2b6fb29bbfe1f516721",
          "md5": "206a3f451e079b7ed2930098f6f32f62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-sources.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-sources.jar",
          "size": 562594,
          "sha512": "85fc5280f2549f1cb73df7c44a5047683f25005fdd3912293b3073f3fa07c4a2f00dbe7b6cbe832a5cd7ef68e48696c19cfaa805e817166dabfaec5434b0e97f",
          "sha256": "7b5f5b29e93d93623ab72f2d2d8d4ca156e61727f655ce872a25a25ee70995ed",
          "sha1": "12c2e14ba17790328b4b78c1a0e8271b55253635",
          "md5": "5cd367fb33f5170e1fd2c74fba8c3d7f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-javadoc.jar",
          "size": 836286,
          "sha512": "229545275f764a8e343d3cc1176d2039dbd9840ba396d6a2a6b2c2f40d4cc02a9ef563b0a681e1253bdd998b524d66d7d2711d4df6e3fbb56252893363aa7575",
          "sha256": "ab4119f76de95eee06c3603b8cfd053207ac35011f856773aaed88979fec25bd",
          "sha1": "553715814f6f4f068b59a1b976ec5d3a5f6d9a33",
          "md5": "67c503c5bd837eec7eef0ba8623c01c1"
        }
      ]
    }
  ]
}
