{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "size": 810403,
          "sha512": "694cef7cf690c309e491356dfdc654ff6216e9caeac9e433e715d394a00f888eef75337dbfa40e8c98889cbac2148ac226d7704ccaceb2d728691927bb63f9a3",
          "sha256": "71e6f0a80b7ebced8dcdafb2738a632177b24c1555f4bc54b5cbfef0eaf6872b",
          "sha1": "a6a312290ce6ea68e968e0eb1b4bb1b7aafd4dac",
          "md5": "4d462bcaa7eeb95e3914428143685f74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT.jar",
          "size": 810403,
          "sha512": "694cef7cf690c309e491356dfdc654ff6216e9caeac9e433e715d394a00f888eef75337dbfa40e8c98889cbac2148ac226d7704ccaceb2d728691927bb63f9a3",
          "sha256": "71e6f0a80b7ebced8dcdafb2738a632177b24c1555f4bc54b5cbfef0eaf6872b",
          "sha1": "a6a312290ce6ea68e968e0eb1b4bb1b7aafd4dac",
          "md5": "4d462bcaa7eeb95e3914428143685f74"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-sources.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-sources.jar",
          "size": 665322,
          "sha512": "3ec3b6a1d3f9f51e667412d14f94fe1d92c6fd56649e8d4c45b3b785521cde466d1c2de4db3cbfdb71b072d826068234f878f77f6dd1f4299417d101f4c3892e",
          "sha256": "883ba0b3676b866ffa4d0bba11cf61ad4d6ea702f7ad737b97ba8a81f0629398",
          "sha1": "c89cca33d743517231c518fb6583072e91e65acb",
          "md5": "36f9b720848cb7c495e265b46a5ca1e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.0.4-SNAPSHOT-javadoc.jar",
          "size": 1077693,
          "sha512": "db6759a5fdc893983618457eb893ce6c4e48f7d67235298aef47edba7b13df464d1f6012155878a223d83019f146572b44a393e9fe511536bca4105828db93af",
          "sha256": "164df89d90b819c775805990e81031be0eea8302b97436e71cef8bb32519d530",
          "sha1": "514d966b3020165e949d3dbd97610de341190273",
          "md5": "5f4e185660bccd571bc3b552d301113d"
        }
      ]
    }
  ]
}
