{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2.jar",
          "url": "numen-neoforge-1.21.1-0.1.2.jar",
          "size": 2567680,
          "sha512": "79360bb9635da7ee7a468700be93bb53187b5a75ad68f35da463f4034cb39b0fc49aeef66d93d549345848f2b5893d34c748d2ef1029b02fee41fecd65e1fa53",
          "sha256": "9d10f0c0cb847baebe714d39db54d4b214252b9f204040227e3ac165168de6b8",
          "sha1": "1bb4f9a2fe1c158f1e976b65cc2f887c86790f15",
          "md5": "beac8860f568b871506903df87060385"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2.jar",
          "url": "numen-neoforge-1.21.1-0.1.2.jar",
          "size": 2567680,
          "sha512": "79360bb9635da7ee7a468700be93bb53187b5a75ad68f35da463f4034cb39b0fc49aeef66d93d549345848f2b5893d34c748d2ef1029b02fee41fecd65e1fa53",
          "sha256": "9d10f0c0cb847baebe714d39db54d4b214252b9f204040227e3ac165168de6b8",
          "sha1": "1bb4f9a2fe1c158f1e976b65cc2f887c86790f15",
          "md5": "beac8860f568b871506903df87060385"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.1-0.1.2-sources.jar",
          "size": 1064618,
          "sha512": "f9a8ff406aa028e8088e6e0ad8081038e2aee272ee550d1318eeb7c5e3098b14fdb8ecb5460d4ec31c5234ebb4871450f2eee6040233b9314066b32e39ce99f7",
          "sha256": "f39ccee8964681b48aa3b586ddbfd087744c0417e3ccd125bb5de19359ea6c96",
          "sha1": "00c235434478c7c2822e043e6cb673a08e9465d8",
          "md5": "e6c01d4c9048a05cdf998cdd57d97d7c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.1-0.1.2-javadoc.jar",
          "size": 1524661,
          "sha512": "d3af1315209a3bb5b851c9ae3c420de43201c000ca8f7c8322f713bd9cbd17681bd00a2545297e9be1340ab58b13e7efec2395cc14fad7c7c733df4778126a11",
          "sha256": "05fd3f62e5de0e0c6e48f489e84eab75579e5e66a55b692420b46f39f177dc96",
          "sha1": "7008fc21ddc2a1bb91c08f62b46abb7938e91a15",
          "md5": "5193b95cc4b86f77e16a7f9e680d33b4"
        }
      ]
    }
  ]
}
