{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2.jar",
          "url": "numen-neoforge-1.21.1-0.1.2.jar",
          "size": 2567686,
          "sha512": "c42911509abc03cd325d5e5fb1a2156911a378521de2fc116fe1bec4489424696cf288fe27a32242c93eff921330cf884107c1b7d01b0156ac7e1a0be6ccba02",
          "sha256": "7cf184c26c5dd00b787a65455ae9e7ba1e98a5a558d5eac2640bfb6111751f3d",
          "sha1": "524a3382edabf23a8f90faef678f9e554aaae028",
          "md5": "c1bf18770c00cc0fed38b352752010ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.1",
          "version": {
            "requires": "0.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2.jar",
          "url": "numen-neoforge-1.21.1-0.1.2.jar",
          "size": 2567686,
          "sha512": "c42911509abc03cd325d5e5fb1a2156911a378521de2fc116fe1bec4489424696cf288fe27a32242c93eff921330cf884107c1b7d01b0156ac7e1a0be6ccba02",
          "sha256": "7cf184c26c5dd00b787a65455ae9e7ba1e98a5a558d5eac2640bfb6111751f3d",
          "sha1": "524a3382edabf23a8f90faef678f9e554aaae028",
          "md5": "c1bf18770c00cc0fed38b352752010ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.1-0.1.2-sources.jar",
          "size": 1064617,
          "sha512": "1e6ef523ea89b07e91a73e2c4171f3c20a853850b16863ae757bd723c3efbd028ff4c63afa491f28ab9ea33f02c312f198fe1751b552fd06bdf3f2b56da777be",
          "sha256": "3e36e05495c1fd509b2e6dc42c53625bf0604dee9e5b90e58afae42ae0fe0697",
          "sha1": "6e12a8cb0cb088744ea7c2f7646f55fa295741f8",
          "md5": "1222a722244643ce3df5898b68637360"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.1-0.1.2-javadoc.jar",
          "size": 1524661,
          "sha512": "d3af1315209a3bb5b851c9ae3c420de43201c000ca8f7c8322f713bd9cbd17681bd00a2545297e9be1340ab58b13e7efec2395cc14fad7c7c733df4778126a11",
          "sha256": "05fd3f62e5de0e0c6e48f489e84eab75579e5e66a55b692420b46f39f177dc96",
          "sha1": "7008fc21ddc2a1bb91c08f62b46abb7938e91a15",
          "md5": "5193b95cc4b86f77e16a7f9e680d33b4"
        }
      ]
    }
  ]
}
