{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-ai",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-0.0.9.jar",
          "url": "numen-ai-0.0.9.jar",
          "size": 77478,
          "sha512": "70b9a6117e52920f924fdef9c39340228786cbdf9c166d28b1a6fb9d99d445161cec5fc3c0714c37b97b7fa662cce0fd4426dfaff21717bc566fcc1dc75085ba",
          "sha256": "5cc689c70dae2d0881635e2475da53982bde74245b5fedba774a2d143b4ec993",
          "sha1": "66194617aa249a77dcb195a0687c607905417632",
          "md5": "336089cc60f3a835da08dba89b7a0420"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-0.0.9.jar",
          "url": "numen-ai-0.0.9.jar",
          "size": 77478,
          "sha512": "70b9a6117e52920f924fdef9c39340228786cbdf9c166d28b1a6fb9d99d445161cec5fc3c0714c37b97b7fa662cce0fd4426dfaff21717bc566fcc1dc75085ba",
          "sha256": "5cc689c70dae2d0881635e2475da53982bde74245b5fedba774a2d143b4ec993",
          "sha1": "66194617aa249a77dcb195a0687c607905417632",
          "md5": "336089cc60f3a835da08dba89b7a0420"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-0.0.9-sources.jar",
          "url": "numen-ai-0.0.9-sources.jar",
          "size": 62044,
          "sha512": "e7d3c5f82877a7b94e60c7a8e3b78f4074fc48393e55790198ea0bdf73434041374b1d3edc884462369da8ea09d504254b2145a80aac1fbcb10a3bfd448b0364",
          "sha256": "5f4bca31de27776ce0e3d17bb1d8e096b9a8d5e5cb54715498c03cec434a24ce",
          "sha1": "0dd78e4a49d7cc422a5591cd09d65e803dd78faf",
          "md5": "f9681ff56e1ddcf4cbad439cc734211a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-0.0.9-javadoc.jar",
          "url": "numen-ai-0.0.9-javadoc.jar",
          "size": 260374,
          "sha512": "d4fafaffc3c4b84e308e91847aca47de7a8ed00ea288f04ef8fffef761906742af3d2c3f52c8a95cd760c2101fa736dbbfce7676a2ed0d702fe59e3db362b93e",
          "sha256": "dababa448eb70d7442c5712f5a56a9345d9b41b79173520c3fcb29bbd953bd72",
          "sha1": "da8283cc4be0280dce786720e81f93a54fdd3f06",
          "md5": "959997dcb1ee3f455827e510e54cef1e"
        }
      ]
    }
  ]
}
