{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.8",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.3.jar",
          "url": "numen-neoforge-1.21.8-0.1.3.jar",
          "size": 2597140,
          "sha512": "581e75d49b735729913349bf89f182d1cdada33c2b03a7bb7bbe63d65bd3f8c87edb933523f8de902173703c76e89f0b13b0b9fe59660fec0fddfc62c14f5aa2",
          "sha256": "a10a716bb60df4bbf376f5a6d283d526b895905fb5af2ffc2f0e3e28937af809",
          "sha1": "0d1aedabeb28d18537531f1d93aad47b8af21460",
          "md5": "316bf890705661982c26cd81f0b7b14d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.3.jar",
          "url": "numen-neoforge-1.21.8-0.1.3.jar",
          "size": 2597140,
          "sha512": "581e75d49b735729913349bf89f182d1cdada33c2b03a7bb7bbe63d65bd3f8c87edb933523f8de902173703c76e89f0b13b0b9fe59660fec0fddfc62c14f5aa2",
          "sha256": "a10a716bb60df4bbf376f5a6d283d526b895905fb5af2ffc2f0e3e28937af809",
          "sha1": "0d1aedabeb28d18537531f1d93aad47b8af21460",
          "md5": "316bf890705661982c26cd81f0b7b14d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.3-sources.jar",
          "url": "numen-neoforge-1.21.8-0.1.3-sources.jar",
          "size": 1074128,
          "sha512": "0b974586d1519e74b5fffd41ed4a9cd1bdd144815e821086a8b15ab12fe87181913e5630608c9fc623ac02a43539ad704e35c631fb020dd0d8f8f59d67391842",
          "sha256": "32dfd4b18d636e890959b0ff1efcf583c7378d83b35f187899432de4212501d7",
          "sha1": "9b297edc88c231343b1ef9cdef7461d68a29ef63",
          "md5": "c350afeb844ce744504547e2cc093f5f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.3-javadoc.jar",
          "url": "numen-neoforge-1.21.8-0.1.3-javadoc.jar",
          "size": 1540288,
          "sha512": "76580b0a5871d9e426baac513fd725c4ea663352ffb478229bbf4195db46208332077c7adb7fee66f4a79b20101843e58440317406fd5d10cec1403c4288e24b",
          "sha256": "46e5fc39b8f76c57955a25812a8e77fac2687bb4c3ce7f450d9aabd1330df18e",
          "sha1": "53d25b600b825071b9f4c65232d46d419f008672",
          "md5": "d47a3de1d4a81fde5cb6dcec9af5b625"
        }
      ]
    }
  ]
}
