{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2.jar",
          "url": "numen-fabric-1.21.1-0.1.2.jar",
          "size": 2478656,
          "sha512": "d18ff10a439eb6598ed9e3c0fb10dd6fd76d4ceb95dfe93487c0e6a4687f97b90a17b9b73184ff694fd079add88a3042714222ecc999bf0b9036be01adea16be",
          "sha256": "38a30eed5986e1fa0ada069a32ec76f658c04621d96ea221c2255df7ccacf0ae",
          "sha1": "e4be1f783e86d77434a675dd831e698b9dfac522",
          "md5": "78c7d6e8bbd38538103a2177a7b7695a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2.jar",
          "url": "numen-fabric-1.21.1-0.1.2.jar",
          "size": 2478656,
          "sha512": "d18ff10a439eb6598ed9e3c0fb10dd6fd76d4ceb95dfe93487c0e6a4687f97b90a17b9b73184ff694fd079add88a3042714222ecc999bf0b9036be01adea16be",
          "sha256": "38a30eed5986e1fa0ada069a32ec76f658c04621d96ea221c2255df7ccacf0ae",
          "sha1": "e4be1f783e86d77434a675dd831e698b9dfac522",
          "md5": "78c7d6e8bbd38538103a2177a7b7695a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2-sources.jar",
          "url": "numen-fabric-1.21.1-0.1.2-sources.jar",
          "size": 1012848,
          "sha512": "bfc20a1fd34a17d9ca6d40b0626fb0df098d3be769bce6d6a894d788e7a469b894b8d3299cd0284ca9c0dd34b4a478a82df738d10ffc353e3525f76619c3f784",
          "sha256": "d16d3a4cda7d44a794a518346046928696e70fc59e553bd505526757d944a4e8",
          "sha1": "9981fa2f2bc0eb17957428dc4ef44253288f2523",
          "md5": "aa2208b2d6981f71c39ed403a4424eb4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.21.1-0.1.2-javadoc.jar",
          "size": 1483096,
          "sha512": "fd33b1e6ee7d6a07b73279c37cbd85efa268f96255ddb801a5780c99710f8ede710158b2c1b5d0c84d9d541b9a4a3e506edc8b21db21e8bb4f1ceecfb7494a76",
          "sha256": "8a622cd45afd656098dd2b009816b7dcb2bee20c0034ff3ef51aba3329f4b99b",
          "sha1": "61e0e72b1b8539e65a49ef3ab98062e24bbe65c5",
          "md5": "29ff033d8e72a9a3256850692f11e559"
        }
      ]
    }
  ]
}
