{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2.jar",
          "url": "numen-fabric-1.21.1-0.1.2.jar",
          "size": 2478660,
          "sha512": "866480d9140d47423accf87bb44d15777d985241d672fe15f9c1714bd49333286b73d245720d2cc13c363994a65db7cc28b0264a99507e70ceabb514f913a0dc",
          "sha256": "c9e459b8847ae0bb4cb7a16047ec4b2d35bbb810dd24b881e9756ba9c6a8dbec",
          "sha1": "a234e40b4e73b709519ad7f4615d70000a9bcb47",
          "md5": "afe0b419ce9915d6bc31fcd94b5362e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21.1",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2.jar",
          "url": "numen-fabric-1.21.1-0.1.2.jar",
          "size": 2478660,
          "sha512": "866480d9140d47423accf87bb44d15777d985241d672fe15f9c1714bd49333286b73d245720d2cc13c363994a65db7cc28b0264a99507e70ceabb514f913a0dc",
          "sha256": "c9e459b8847ae0bb4cb7a16047ec4b2d35bbb810dd24b881e9756ba9c6a8dbec",
          "sha1": "a234e40b4e73b709519ad7f4615d70000a9bcb47",
          "md5": "afe0b419ce9915d6bc31fcd94b5362e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2-sources.jar",
          "url": "numen-fabric-1.21.1-0.1.2-sources.jar",
          "size": 1012846,
          "sha512": "ddd30543aa2929c89488cb9493d1877028ec533305709bb56d8649628bfa0298a2d0fefabe852bf3ae1c35d30ebb7750ca6c001d8e41dd605d5beb4278d37089",
          "sha256": "3fdb5c3f47e00234124c947dbe99d92992ef7e179ef930514a3d192a9dc5b386",
          "sha1": "eb6fda362e038127af052c0cb12931a922f38ba3",
          "md5": "ddb735669e6b8d610a73818d6fb1917f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21.1-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.21.1-0.1.2-javadoc.jar",
          "size": 1483096,
          "sha512": "fd33b1e6ee7d6a07b73279c37cbd85efa268f96255ddb801a5780c99710f8ede710158b2c1b5d0c84d9d541b9a4a3e506edc8b21db21e8bb4f1ceecfb7494a76",
          "sha256": "8a622cd45afd656098dd2b009816b7dcb2bee20c0034ff3ef51aba3329f4b99b",
          "sha1": "61e0e72b1b8539e65a49ef3ab98062e24bbe65c5",
          "md5": "29ff033d8e72a9a3256850692f11e559"
        }
      ]
    }
  ]
}
