{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-26.1.2",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT.jar",
          "size": 913907,
          "sha512": "24554011bfa7397e1dd7e64cadae1585f817b1d4e35849d4f3fc0f9fd6b05de28870206bad611644b72a36dd4ee745c0f7e517c5a9a669896fd284740480877e",
          "sha256": "3ad25f993da73f69c749301a76d76775b114f0fcf46d3ab298edd0f9ee9aec7c",
          "sha1": "0b04ba4665662f94e30bd7bd0efeada7c47dcc93",
          "md5": "93f0ad58454303ea3343b48226d8a470"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT.jar",
          "size": 913907,
          "sha512": "24554011bfa7397e1dd7e64cadae1585f817b1d4e35849d4f3fc0f9fd6b05de28870206bad611644b72a36dd4ee745c0f7e517c5a9a669896fd284740480877e",
          "sha256": "3ad25f993da73f69c749301a76d76775b114f0fcf46d3ab298edd0f9ee9aec7c",
          "sha1": "0b04ba4665662f94e30bd7bd0efeada7c47dcc93",
          "md5": "93f0ad58454303ea3343b48226d8a470"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT-sources.jar",
          "size": 729222,
          "sha512": "e8516f05f69ca9b510fc6583a84fb4faf30696b22ca526a19fa3c737a8e37da92c8ad679c2265e468fbf8875932ea44135c67b67d3f282d524a2c6fb3b124cc8",
          "sha256": "419f44f4380cc56f2fcb4a893b88bb2c6056554e3dae1af3e59446ff6f14b0a6",
          "sha1": "e0ca3353fb17fd26efcfc8243ef6e1845aeccb75",
          "md5": "e0fff98a0b719652279db17fe8d4bd06"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-26.1.2-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
