{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.21",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.3.jar",
          "url": "numen-fabric-1.21-0.1.3.jar",
          "size": 2519756,
          "sha512": "0cfb7497b3797eb6a44e713c6e6d2e4ef2d803c3087c8056005b7acb81c9bd7da226294c60af4ac7d9580386c0d3c81a434939af61999399af7efecd40459ed2",
          "sha256": "114858aa47aa6f579d846e1add719efca353a5ef5105045a7f89b300e4f4fc83",
          "sha1": "a2582e3c271bdcd494efd54cb24916968e5c19ae",
          "md5": "49dd32e4d385c3d75f068c06e786a624"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.21",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.3.jar",
          "url": "numen-fabric-1.21-0.1.3.jar",
          "size": 2519756,
          "sha512": "0cfb7497b3797eb6a44e713c6e6d2e4ef2d803c3087c8056005b7acb81c9bd7da226294c60af4ac7d9580386c0d3c81a434939af61999399af7efecd40459ed2",
          "sha256": "114858aa47aa6f579d846e1add719efca353a5ef5105045a7f89b300e4f4fc83",
          "sha1": "a2582e3c271bdcd494efd54cb24916968e5c19ae",
          "md5": "49dd32e4d385c3d75f068c06e786a624"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.3-sources.jar",
          "url": "numen-fabric-1.21-0.1.3-sources.jar",
          "size": 1016898,
          "sha512": "2d33bb02984ead6fa2354386ac22902d8dbe7a357cedbb1043ee6a100fd4043d5ffa3723291c523701dd548b2e9521cb4bbbe4af56c9883394c1f91891eb5e2b",
          "sha256": "189a9b80d2b6a02c283d12169163d806590c9eb151898eba96d42a9370801447",
          "sha1": "835f70ecee9096a2d0d79efb7e80fb45a29c52b5",
          "md5": "09c5b5b72da2fb4da54ebe1d92409aac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.21-0.1.3-javadoc.jar",
          "url": "numen-fabric-1.21-0.1.3-javadoc.jar",
          "size": 1493935,
          "sha512": "6d01c6ef2fa6bc5c3ee585054e9b29b864b703d9e7521930bf63aa34e1e496598bf1afbcaadfa2f275f6e978544a18e083ecd712488355e822e21a6c33246335",
          "sha256": "d15b3c59595d00be7226005f2ab465b0d83855fba8474826b6c9230a97ce496b",
          "sha1": "2b7b2eb16f8b8fd53bb0bf164cefd596f5f12148",
          "md5": "4a00b57d606a260f2a9d322787402847"
        }
      ]
    }
  ]
}
