{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-26.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.1.2.jar",
          "url": "numen-api-neoforge-26.2-0.1.2.jar",
          "size": 1326928,
          "sha512": "046f7bc142df1156b61b01ab22e6aefe0b1a3a183d617afd1df953d14d9b17c56480b1f542ec030f4f9960937c79e2e0c940829677e9d7970907b32b8cd6c702",
          "sha256": "e28c2231b2a409682d8be55a621f8bb1a10726bf602ce0b63d95f27cfb1cd266",
          "sha1": "a223da9ae3547faf5f4f425c0ec9c7e484e5fe78",
          "md5": "5df9fac8b6506f2fc504b7592a801e40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-26.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-26.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.1.2.jar",
          "url": "numen-api-neoforge-26.2-0.1.2.jar",
          "size": 1326928,
          "sha512": "046f7bc142df1156b61b01ab22e6aefe0b1a3a183d617afd1df953d14d9b17c56480b1f542ec030f4f9960937c79e2e0c940829677e9d7970907b32b8cd6c702",
          "sha256": "e28c2231b2a409682d8be55a621f8bb1a10726bf602ce0b63d95f27cfb1cd266",
          "sha1": "a223da9ae3547faf5f4f425c0ec9c7e484e5fe78",
          "md5": "5df9fac8b6506f2fc504b7592a801e40"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.1.2-sources.jar",
          "url": "numen-api-neoforge-26.2-0.1.2-sources.jar",
          "size": 1060235,
          "sha512": "7b006244e97a8910bd7e19f549d47c4f51dc0e590f8f7d034135ce15bd762a593fd9628a6460f58dcbd7f62d3dbbdbe850ba57dd4976dd19a39c93a2a4b08567",
          "sha256": "aca641ee5915cff36ea7fb401dfbb6856b53587fdc75223dfb5f341fbf07c939",
          "sha1": "58638a62af86cba8f134f16f1d4e22b5df44ea7a",
          "md5": "6633c7376e492963fcbfb3e43f034c14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-26.2-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-26.2-0.1.2-javadoc.jar",
          "size": 5694042,
          "sha512": "1d9bda9a1df5651fcc38409a0a88beedb21db3cf11eaa62927a0e284c9191dc70cc9e3d3193a0d5d3ab9ae8f2eb29a0a23a9c0b4de5e1fd0780b5ad6b76078ef",
          "sha256": "cacee192d3412d52646b535e413fe909cd70ab5b5a3589b10fba7d695e8f4230",
          "sha1": "90303c282a06cfba1a8c51d0dc5095f28a2cf4fb",
          "md5": "804b5ec4191b511f702e0236bc027ecd"
        }
      ]
    }
  ]
}
