{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.10",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT.jar",
          "size": 909804,
          "sha512": "853159f504b28c7b3e454598e7faa7bca7ca105476b762b095d61449e0d99ee3f09d01bd1c88621151403d2360223bc4da37d74ad077952cf0ff6469cf382636",
          "sha256": "bfbb32da4de7c508e68246458421f86e7de6bd225b39f73dec08969469a52054",
          "sha1": "b1aead1e879a301a4eadf5b4bb00e30705aaf4b4",
          "md5": "e1d8b237f5937490186077398ca4ba23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.138.4+1.21.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT.jar",
          "size": 909804,
          "sha512": "853159f504b28c7b3e454598e7faa7bca7ca105476b762b095d61449e0d99ee3f09d01bd1c88621151403d2360223bc4da37d74ad077952cf0ff6469cf382636",
          "sha256": "bfbb32da4de7c508e68246458421f86e7de6bd225b39f73dec08969469a52054",
          "sha1": "b1aead1e879a301a4eadf5b4bb00e30705aaf4b4",
          "md5": "e1d8b237f5937490186077398ca4ba23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT-sources.jar",
          "size": 730954,
          "sha512": "d8a476046fc98ba6e801e87edcdc9c2b82b6d60768ee86ca5ba39bcafe9db067ef44bd03be35eb5906705c276530d1a6758d87576742d5c4115555bf8a75bbf7",
          "sha256": "d413a1c9b8682cacffb78d3041d676770a6dabf4b59665f4a013c8eba19ce55c",
          "sha1": "3a8f1076d368b05d230e8d75ee50a4f7a9828010",
          "md5": "33be07c8404ecda1b87df42e2098c2ed"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.10-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
