{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "size": 1322840,
          "sha512": "30d0280186365559f20f0561f0f085f75c69feef8af50ea020ae7eb0dd8a3db6d2c7472f435f082593c4ea0ffa9d8e653d394d96cabc570f9dccacfd3ea93334",
          "sha256": "40d7cbb4918baf981a8dbee936f4115f20aa8ec4028297158643c2eb6b5fb73c",
          "sha1": "8a56eec623cc5df60dfd7ab923264a1cd116e44f",
          "md5": "b15b563328514dd158dc0234182f8e60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "size": 1322840,
          "sha512": "30d0280186365559f20f0561f0f085f75c69feef8af50ea020ae7eb0dd8a3db6d2c7472f435f082593c4ea0ffa9d8e653d394d96cabc570f9dccacfd3ea93334",
          "sha256": "40d7cbb4918baf981a8dbee936f4115f20aa8ec4028297158643c2eb6b5fb73c",
          "sha1": "8a56eec623cc5df60dfd7ab923264a1cd116e44f",
          "md5": "b15b563328514dd158dc0234182f8e60"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2-sources.jar",
          "size": 1054128,
          "sha512": "f730211608a9f67a9de177ebd8a93705d5e8869d366bbdb1ff4bd73caafb3d6b737d2db3df5e8df32610edbeb0e3e1800c315366001fa2520ba713829f0e39ff",
          "sha256": "e926fec2278cd5f2c81ecbbcd7b77dfcbe6fae1316e5da36f5f80871593e4278",
          "sha1": "3e0f223edebbe53b26cc4b37e653e7866e68c0ef",
          "md5": "0276192306cb14a270df1340ed09f27d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2-javadoc.jar",
          "size": 1562321,
          "sha512": "66a87e6e3a068a961a549a8bee0564d5378152a1b842897e1aabb7152820e0b92613c7e46a17818625aae3196adbeccfd4c78129d511f0aac2d6e1ca0100979c",
          "sha256": "8be8e8f276beb6e47be4347b1b44792326105e3835b3d89562933a33f3b8732a",
          "sha1": "e245c132e010d62ca52ed38be6ba9a83f1749558",
          "md5": "1be86bc1619460cd0f5c065c389cb222"
        }
      ]
    }
  ]
}
