{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.20.6",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "size": 1322841,
          "sha512": "b7493d17000e227c72ad8aeeaa9d144d03f6331cadc2eae5b9962ef3aae96e0962d5c35379266f96016d7a03833b282dde2df1d81ff1eb8271099b854df571e2",
          "sha256": "5f931d88da876207db99e0df2f20c416795b386ad748208bf24e39d1623adf7d",
          "sha1": "f3582bbe53c028145d1aea75582b40badc05b61c",
          "md5": "dc00493f90787e206c96ebb20caf5426"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2.jar",
          "size": 1322841,
          "sha512": "b7493d17000e227c72ad8aeeaa9d144d03f6331cadc2eae5b9962ef3aae96e0962d5c35379266f96016d7a03833b282dde2df1d81ff1eb8271099b854df571e2",
          "sha256": "5f931d88da876207db99e0df2f20c416795b386ad748208bf24e39d1623adf7d",
          "sha1": "f3582bbe53c028145d1aea75582b40badc05b61c",
          "md5": "dc00493f90787e206c96ebb20caf5426"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2-sources.jar",
          "size": 1054129,
          "sha512": "ab1e3f7b9960d9fda72556fbd2bdb66453c60f56d561a409640e59e2cd708a348b505934652c8033dcd94a6a3c34ef07fb216ae127f8f045b39762ddaa12d2c9",
          "sha256": "d936db14c3873e2786c66f0bc837e4c99f946cc54d05b8b06db9d070f887223e",
          "sha1": "35520dcc6940452434f16b0e1b42d295c7dcdd8f",
          "md5": "a0f41e9cf7bbe42e78a892957981c658"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.20.6-0.1.2-javadoc.jar",
          "size": 1562321,
          "sha512": "66a87e6e3a068a961a549a8bee0564d5378152a1b842897e1aabb7152820e0b92613c7e46a17818625aae3196adbeccfd4c78129d511f0aac2d6e1ca0100979c",
          "sha256": "8be8e8f276beb6e47be4347b1b44792326105e3835b3d89562933a33f3b8732a",
          "sha1": "e245c132e010d62ca52ed38be6ba9a83f1749558",
          "md5": "1be86bc1619460cd0f5c065c389cb222"
        }
      ]
    }
  ]
}
