{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2.jar",
          "size": 579602,
          "sha512": "07dda623a02818fbb69d5a3aa29678b64b2199a7af25aabc63fc41432dac8097c990acbf0a70accf905c68a312589cb9dc1cf4199530b2d8974698e98098a7ee",
          "sha256": "846e6cc30d48221718269ce7bfd530b66d25075e8ab4a777e4db541cf5a7ac3e",
          "sha1": "6dfa1ea4e0741178915b3986d82bbade0ca2a664",
          "md5": "f502c258837ba099e295dd419df63f78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2.jar",
          "size": 579602,
          "sha512": "07dda623a02818fbb69d5a3aa29678b64b2199a7af25aabc63fc41432dac8097c990acbf0a70accf905c68a312589cb9dc1cf4199530b2d8974698e98098a7ee",
          "sha256": "846e6cc30d48221718269ce7bfd530b66d25075e8ab4a777e4db541cf5a7ac3e",
          "sha1": "6dfa1ea4e0741178915b3986d82bbade0ca2a664",
          "md5": "f502c258837ba099e295dd419df63f78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-sources.jar",
          "size": 490428,
          "sha512": "9548ce9351fee658eb8fda5cf8b8f33bd0092e8483c658713c308d0df1e53168142f83529035a596c2d5a524f5d4909ce4dcc55f26bf3623f46697268ccebdc1",
          "sha256": "ab74ee579bb2ead6576c02aaa5fed07c7538ae5ed7313540d694d37173c2937c",
          "sha1": "15141f2a9bc984fe899aa8259e78fdfaf92383ad",
          "md5": "bc75e6816244131f54389c65a9971cc4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-javadoc.jar",
          "size": 761707,
          "sha512": "af9311d6b5611f048e0a08d4e79ff6e0e15b0e7acead210b5212c8496487a1c83bfd4afee57c62815cd7d33b7d24664d9bb6eb94bd174072ecd9b57737a5f65a",
          "sha256": "d22fbc9a0146aee4b3833b87a5e640d183cf3238a0d9272323af34ce86bd1d0b",
          "sha1": "11f26880563ded5e04c8f44b2dc419ca7e2ae311",
          "md5": "c035444a1f3c88b20494fe41c9dba5ab"
        }
      ]
    }
  ]
}
