{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2.jar",
          "size": 548506,
          "sha512": "4f27f48282240d2e9973fd0a54643921c7b8f00c8dbe2a7a914e6e89bd9a66f68379396b128d645829ee11f9b1ab9a2b9cae073549bfc1dac0d16f47b73de9ea",
          "sha256": "7005aa29bb17ad51a451cec8dc51939984676643a71469780013d5fdf589d7bf",
          "sha1": "1bbe2fa5389c5475c3aa39854569cdeafd382494",
          "md5": "865cfe26f68b671b482a79b523de76d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2.jar",
          "size": 548506,
          "sha512": "4f27f48282240d2e9973fd0a54643921c7b8f00c8dbe2a7a914e6e89bd9a66f68379396b128d645829ee11f9b1ab9a2b9cae073549bfc1dac0d16f47b73de9ea",
          "sha256": "7005aa29bb17ad51a451cec8dc51939984676643a71469780013d5fdf589d7bf",
          "sha1": "1bbe2fa5389c5475c3aa39854569cdeafd382494",
          "md5": "865cfe26f68b671b482a79b523de76d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-sources.jar",
          "size": 469934,
          "sha512": "d4c7d7ff6f7d00717e753c7b34caf0de7421036af00d7ede76432e102a8ddffb1166fd9139231b541ea0002fce5dd4aba97e4c5ef14bc438bebd4f27b939831f",
          "sha256": "4ebcc203d5d4f4a37cbef9d15ec2cf2e20cca937296e7417bfd473fb0a89ab40",
          "sha1": "2d33b60c4ba64434e1df5da368ebf8b8018dd9e6",
          "md5": "3918507448ffd9448080f826f46f6168"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.2-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.2-javadoc.jar",
          "size": 701588,
          "sha512": "39bf559c824e5b932f82d8ef4af48304f0aa72f85041b3eeebaf8bf10c092d12a15bbc42a094ac28b2f017f9e099534fa67ec6433a1d605c3ff2e10af0b18822",
          "sha256": "8b504a765fb383a878d2fa9812ec1bc83db5a047812bb5e2a3c2d4c4db85deb5",
          "sha1": "ee7fc24b7d8966b2cf271373b1ef0734b46fc3b6",
          "md5": "a632468d22db79069908a024ed535068"
        }
      ]
    }
  ]
}
