{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.10.jar",
          "url": "numen-api-fabric-1.21.1-0.0.10.jar",
          "size": 1336326,
          "sha512": "325d624727f6b689d92fecc794714a402950c4ee327039b9635d3c47c5a7f7646943d4152a6f66ba16fb8f94fc2fa8e7158ea2b9e0310a21285e8bb8feb4c8d9",
          "sha256": "82211952dfaf84a6e308fd242f41f6d0241c6e6cc855cdeab331405db3d67ca0",
          "sha1": "9b5f6ec4b6f45b973dc3c96ac9e2f58598219d69",
          "md5": "0e76b2d9eee347d5591d4209682bc3b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.10.jar",
          "url": "numen-api-fabric-1.21.1-0.0.10.jar",
          "size": 1336326,
          "sha512": "325d624727f6b689d92fecc794714a402950c4ee327039b9635d3c47c5a7f7646943d4152a6f66ba16fb8f94fc2fa8e7158ea2b9e0310a21285e8bb8feb4c8d9",
          "sha256": "82211952dfaf84a6e308fd242f41f6d0241c6e6cc855cdeab331405db3d67ca0",
          "sha1": "9b5f6ec4b6f45b973dc3c96ac9e2f58598219d69",
          "md5": "0e76b2d9eee347d5591d4209682bc3b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.10-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.10-sources.jar",
          "size": 1069834,
          "sha512": "cb943ad51339a4206480d58e75d70603775bad9a88635543e77a4fb2c465ddfd8a9581f319c976abe51ccc48bd9689b9b1ae1b6117d7b330ab6670693478f896",
          "sha256": "cdeaf7729006dd2c4a84cb845702ccde12e4537af542a1274fb29c1f44fcd7b6",
          "sha1": "edd1718ab6e63973a01c443b23d24c8963f7802d",
          "md5": "0fe25af1886653997ade628c2e123b60"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.10-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.10-javadoc.jar",
          "size": 1567340,
          "sha512": "ee4bc239bd3f7a45376ec03bdb7ac8181e354cd4cd22df3d0d27c89f0130ae77a15c59b9a8a282cbb9d830ebf719acbf4ceed5b96983a330dd885b6c5a019695",
          "sha256": "4a33a27f706213170309b137997ffbbdbb40777fe028929683a2dcbab6e48e82",
          "sha1": "16fa988ab0833a96d700d4b047032c50bff7f5d5",
          "md5": "1b2c1bece3c24557073a746804a59b74"
        }
      ]
    }
  ]
}
