{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.20.6",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "size": 1322840,
          "sha512": "71e7bf518b1d97f53089d1287621f858a33f60e9ee17600ec931b96450ea43ab63c20b60ab0a06143779a919c19f8345bfdb5c0496326b73fd405d2d356699eb",
          "sha256": "bf4a94ad409d21e728a44b2222201b134292a5d88ec5ebf0e447d4d8e93bd1f2",
          "sha1": "f84046d1827a16d589ca4833fc9e191f74db2f09",
          "md5": "ab9974a2f76d7c7cce7554784340af22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "size": 1322840,
          "sha512": "71e7bf518b1d97f53089d1287621f858a33f60e9ee17600ec931b96450ea43ab63c20b60ab0a06143779a919c19f8345bfdb5c0496326b73fd405d2d356699eb",
          "sha256": "bf4a94ad409d21e728a44b2222201b134292a5d88ec5ebf0e447d4d8e93bd1f2",
          "sha1": "f84046d1827a16d589ca4833fc9e191f74db2f09",
          "md5": "ab9974a2f76d7c7cce7554784340af22"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10-sources.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10-sources.jar",
          "size": 1054128,
          "sha512": "68c75d1eff1f1b3184e12c3a74d256409182af7505a3610d1b519e804c7371463243b05ad4d2668ee0625ed367412ba3a3bcc598c6198fd274aab5311767e1ba",
          "sha256": "be740bdcb9e76a9d9b85f8847ab96ee57a18b0808f9973daa10f8ba787e65086",
          "sha1": "7100c66c88deeeeae4980667c699037cd66e7771",
          "md5": "013f4c2b07600129c8781f8a5ba20817"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10-javadoc.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10-javadoc.jar",
          "size": 1562711,
          "sha512": "2c1be7190830bb2e3eecbfa2bafc24bdf588fbb2748a63f545e0464c4b4b9b620a51016ccbeb8a15131cec88ef997e4a8ed98477f4b60d99bcaf48fffa9b17e9",
          "sha256": "b40f542dc0abfe1b851c26365b217f17536792aefea3e6ce75ed6bb431e30caa",
          "sha1": "16c1cbb90c1bd384ab8d846cd2274917d4ce61f0",
          "md5": "a0e78ec9011acba5d11b03fe354012c2"
        }
      ]
    }
  ]
}
