{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.20.6",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "size": 1322841,
          "sha512": "8a3bc27089c173de116297d63ce51b56be6c366973a624fb621eba48b0ed9fb57913cc9742868fed6389219edbcf25b0ea263ed0606fb03b36e300d28150072c",
          "sha256": "9d0adb084c7f40f90d3e5e0f94e9902cd26224da133c6ed2c9a13aa9fdf8f64b",
          "sha1": "803bebf114ef4289b74d0b43d82ec5244718c368",
          "md5": "99a3823899d7b5a793b5de417ca38ad9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10.jar",
          "size": 1322841,
          "sha512": "8a3bc27089c173de116297d63ce51b56be6c366973a624fb621eba48b0ed9fb57913cc9742868fed6389219edbcf25b0ea263ed0606fb03b36e300d28150072c",
          "sha256": "9d0adb084c7f40f90d3e5e0f94e9902cd26224da133c6ed2c9a13aa9fdf8f64b",
          "sha1": "803bebf114ef4289b74d0b43d82ec5244718c368",
          "md5": "99a3823899d7b5a793b5de417ca38ad9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10-sources.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10-sources.jar",
          "size": 1054129,
          "sha512": "896f83a40acde4971861b6dc38ad4d576ad11a11f0e06007266c35203e78e3fb61ed21fbad1041fec61f2a798d8a1ffda8bba6af61bbe316596ba53a1d9c532b",
          "sha256": "9556ad22f13e18ffbcc59f8e817874dd084e58d5d2730d63de794a7e374a3767",
          "sha1": "b4446822b326fd7a1361a9bb02c86f2d54789108",
          "md5": "bc3fc9a3231652f7d1a4fc7f6188f6db"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.20.6-0.0.10-javadoc.jar",
          "url": "numen-api-neoforge-1.20.6-0.0.10-javadoc.jar",
          "size": 1562711,
          "sha512": "2c1be7190830bb2e3eecbfa2bafc24bdf588fbb2748a63f545e0464c4b4b9b620a51016ccbeb8a15131cec88ef997e4a8ed98477f4b60d99bcaf48fffa9b17e9",
          "sha256": "b40f542dc0abfe1b851c26365b217f17536792aefea3e6ce75ed6bb431e30caa",
          "sha1": "16c1cbb90c1bd384ab8d846cd2274917d4ce61f0",
          "md5": "a0e78ec9011acba5d11b03fe354012c2"
        }
      ]
    }
  ]
}
