{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.6",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.10.jar",
          "url": "numen-api-fabric-1.20.6-0.0.10.jar",
          "size": 1319809,
          "sha512": "e1260f016b308278dc1514538e337ec9f98177b383527aad31e49e6a736387bc8ddb1a8d93215e1abbf2d164240cba3da8cc1b1e886a12f99523ba73ca3a99ff",
          "sha256": "b370ccda0d1f84efad4507268b6e3beb2d885a9803abd31b17ce7e506de3b585",
          "sha1": "7f679b3cc56cfdaf865442b95235f7ea6a1c7aca",
          "md5": "212935f87f941952aadd486bb0ec50f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.10.jar",
          "url": "numen-api-fabric-1.20.6-0.0.10.jar",
          "size": 1319809,
          "sha512": "e1260f016b308278dc1514538e337ec9f98177b383527aad31e49e6a736387bc8ddb1a8d93215e1abbf2d164240cba3da8cc1b1e886a12f99523ba73ca3a99ff",
          "sha256": "b370ccda0d1f84efad4507268b6e3beb2d885a9803abd31b17ce7e506de3b585",
          "sha1": "7f679b3cc56cfdaf865442b95235f7ea6a1c7aca",
          "md5": "212935f87f941952aadd486bb0ec50f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.10-sources.jar",
          "url": "numen-api-fabric-1.20.6-0.0.10-sources.jar",
          "size": 1058772,
          "sha512": "e0c12046e86dafa902bb4c7d41cdb47c305fc2239be5b5d1b311300c8c21bac15d3f7087c6a2a10900a1ba2a8f9481f2e02dabda06a3cbfa502d94dee45e4b94",
          "sha256": "f80a4e527d6f97484b5585733cd99f9ac34094d51549849405474724e1b670fb",
          "sha1": "4f8291b18a386d50782bf4f23f7e62ede2fcee92",
          "md5": "686fb75caec7b0541f7a916f6a4dad23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.0.10-javadoc.jar",
          "url": "numen-api-fabric-1.20.6-0.0.10-javadoc.jar",
          "size": 1565648,
          "sha512": "c2bbbf894ab47dd963809fa64ecd3727b9ff695bffb2f2d134f7d55879382fd6378cace479ba0e582cf34a628f7d204dadefd6cd60e36a3fc4baad7f18efb015",
          "sha256": "c6eaf2814b2b3e0f9a3a86947284db79ab6e5354e5dbe9bfc23b308af6e30777",
          "sha1": "bf297f079fd78f1c5346fd1fff3232b10ec089d5",
          "md5": "33a87e7218d6417921f4fb461f08839b"
        }
      ]
    }
  ]
}
