{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.2.jar",
          "url": "numen-api-fabric-1.20.1-0.1.2.jar",
          "size": 1323454,
          "sha512": "5bdd000214f2d5892c98b7e8c2410206e2a52af66ac425730ed18bdd69fca176940904bd2868d6e85f8c7affe3fa15b393aa17afb20a8d8e10712c8c55878f18",
          "sha256": "6f9afca6063218afe59e87af90c4d50750d832aef2100ef544dc345ca23fa5ec",
          "sha1": "8a07d01f6dfc16a83d02624409b37224ede48638",
          "md5": "8a3619f2e27fbf52ceb79bfb7801c46e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.2.jar",
          "url": "numen-api-fabric-1.20.1-0.1.2.jar",
          "size": 1323454,
          "sha512": "5bdd000214f2d5892c98b7e8c2410206e2a52af66ac425730ed18bdd69fca176940904bd2868d6e85f8c7affe3fa15b393aa17afb20a8d8e10712c8c55878f18",
          "sha256": "6f9afca6063218afe59e87af90c4d50750d832aef2100ef544dc345ca23fa5ec",
          "sha1": "8a07d01f6dfc16a83d02624409b37224ede48638",
          "md5": "8a3619f2e27fbf52ceb79bfb7801c46e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.2-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.1.2-sources.jar",
          "size": 1072734,
          "sha512": "925c086f7a584dbea4d709420944b0cedbe2ea584f0b7e846b76d3a9891adb37908478988f644b9f35b019b7f1bbdefa1454cc5503e8e3fb05816d02464c86ca",
          "sha256": "07b726d6dfada6adcd27e2b066c6942aacb67cd5d7d0186b3df94f130c8462c8",
          "sha1": "a0e1835ae0fa9b2362d692db6aafb18340027365",
          "md5": "afbb57925f3292d57578c5b081e75640"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.1.2-javadoc.jar",
          "size": 1529875,
          "sha512": "923eab539513f86c459229b80dc5c54b25263dde511fb16c406717bc5291660680f6ba2b0306b756ebccecd3e231911e0054cacacbf78b077e0ed92f55eeb2e3",
          "sha256": "b69fe376913afe0ed2ff6bd18e1be897e8575a26bb5b66186788a7940dbaa8e0",
          "sha1": "6fdd3f9505384e3c1b57c1dfc4fcd2567a8b3f66",
          "md5": "5fc6c99495f6d6a59e0385fe80225732"
        }
      ]
    }
  ]
}
