{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2.jar",
          "url": "numen-fabric-1.20.4-0.1.2.jar",
          "size": 2460142,
          "sha512": "ada2f99f3cd79b9b448c9c77dbc349838e74bfc0ff8eb5b289fdb64e1edaae30e8b0a398cc61ebc3656816c3dc3f7ebe206422dce40767fa11898d77b5c1a6e5",
          "sha256": "0023865bc9d93dadba628f83cf0f3b4ba73b1a6526d1317bf084fab76b5959b7",
          "sha1": "fd0c901a2be83836af781c26a595338905102db6",
          "md5": "a10f22b67184cc24e6277ff9c6f1c376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2.jar",
          "url": "numen-fabric-1.20.4-0.1.2.jar",
          "size": 2460142,
          "sha512": "ada2f99f3cd79b9b448c9c77dbc349838e74bfc0ff8eb5b289fdb64e1edaae30e8b0a398cc61ebc3656816c3dc3f7ebe206422dce40767fa11898d77b5c1a6e5",
          "sha256": "0023865bc9d93dadba628f83cf0f3b4ba73b1a6526d1317bf084fab76b5959b7",
          "sha1": "fd0c901a2be83836af781c26a595338905102db6",
          "md5": "a10f22b67184cc24e6277ff9c6f1c376"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.4-0.1.2-sources.jar",
          "size": 1022185,
          "sha512": "10ff6775c9d12b1440edeea77e5e2925fe7e212cd65016724d30d90f82561a3a729c678401543f137b083c62643201a0767e8424c3f2de6786af23eb5dfc951d",
          "sha256": "643aae6b0ca5fde1fb73143dc329410f9bbdb432fa228d590189417a38e16574",
          "sha1": "cae86a8a76b1b6005ae2aa7038a9252085c58bec",
          "md5": "175a4763c9243eb9b4b67a103baab07c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.4-0.1.2-javadoc.jar",
          "size": 1445093,
          "sha512": "9a60b5c0eb45eed49c4e2f43261c001b03f6e068503fff24758401fae163782bb9fc08e58575746e6c0d55587181813daf8ecf56bd196aacd7a09c3f5f7c12f6",
          "sha256": "580390424d9fe18c91329cc81f30ef88e6293e8ae9856e466c86703624c11e4a",
          "sha1": "7529a6124cef56d23a10627b63bf0352c300b5c7",
          "md5": "d6661ceab8a9eccfff3c15c0cb83c0c4"
        }
      ]
    }
  ]
}
