{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2.jar",
          "url": "numen-fabric-1.20.4-0.1.2.jar",
          "size": 2460141,
          "sha512": "0367f7dd76c4202a2f51c0d0b0aee08736c591568f7be32dd595506f2b9ff1a1c8c3e9aa7376a58d4375742d73390539c6f0bb99248c144b12758e24c5fbfd8c",
          "sha256": "068384bd9d5b6290dee164fa5f213821fa26521262be8389997742dc69c92511",
          "sha1": "ad705359cb190f22bd83dd2a743c3282b47fe29d",
          "md5": "fffd884c59cca4e0e9486be8318262f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2.jar",
          "url": "numen-fabric-1.20.4-0.1.2.jar",
          "size": 2460141,
          "sha512": "0367f7dd76c4202a2f51c0d0b0aee08736c591568f7be32dd595506f2b9ff1a1c8c3e9aa7376a58d4375742d73390539c6f0bb99248c144b12758e24c5fbfd8c",
          "sha256": "068384bd9d5b6290dee164fa5f213821fa26521262be8389997742dc69c92511",
          "sha1": "ad705359cb190f22bd83dd2a743c3282b47fe29d",
          "md5": "fffd884c59cca4e0e9486be8318262f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2-sources.jar",
          "url": "numen-fabric-1.20.4-0.1.2-sources.jar",
          "size": 1022183,
          "sha512": "7b5992c9487484133c606404fad1d0b069c36bb44aedb141c01d3e082be07941ee24c0acaf9277cae27a12be0d45d427c54fc5a7495fb6e67cbc80baab02f8a2",
          "sha256": "62ec54d19c64497ad496a7f1344f8a2dbea0fb66d17605da415d8ecce30382f8",
          "sha1": "ce91c8fd0cf130ef385bafda81dcfa1c6e69e969",
          "md5": "16e7a349787088352ce8ac19e36a3ea0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-fabric-1.20.4-0.1.2-javadoc.jar",
          "size": 1445093,
          "sha512": "22a2dd0982d4684b2ce116c4df26d2db70b8a4603952834fde319247640029a03274778b277c45272166cf59d9c129326dcf13331c5002801ffdbbe2ff2fc665",
          "sha256": "c5ad8a38eadf5990b58a5cca0006e1b14e3dcbf5b489af4a2b45e33f8c5c21a2",
          "sha1": "f1f590dfd4370763a467f97ec99d35b4831ee1a6",
          "md5": "36b3d1c0921a5cc8b04b578a3475569b"
        }
      ]
    }
  ]
}
