{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.4",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT.jar",
          "size": 907075,
          "sha512": "625ec6dab94844d6aa88a058d94b91abf07d777d9b1e0b97273948743c3aab1b4dc6ba7f03e2016fdac2108b6081218570884697e17824a4b3d754248f09379a",
          "sha256": "8260e66b566412182d24cb7a1d8e9e5b42eea2cb1e62373d62e74846716cdcf9",
          "sha1": "46de7867d1b1ee888798819bbd13854882db2c43",
          "md5": "737adaa995166edd57de850e83213066"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.117.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT.jar",
          "size": 907075,
          "sha512": "625ec6dab94844d6aa88a058d94b91abf07d777d9b1e0b97273948743c3aab1b4dc6ba7f03e2016fdac2108b6081218570884697e17824a4b3d754248f09379a",
          "sha256": "8260e66b566412182d24cb7a1d8e9e5b42eea2cb1e62373d62e74846716cdcf9",
          "sha1": "46de7867d1b1ee888798819bbd13854882db2c43",
          "md5": "737adaa995166edd57de850e83213066"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT-sources.jar",
          "size": 729018,
          "sha512": "91d8e38d591fa1cb524070de9a8e3931e5be47a7f363602dc90f5b2ec6924e27d801503652728fe36e576221b4a16fc715fd0bbfaa8fec9f2ad41352e273010d",
          "sha256": "bcb1636c1f4e9491ad5b6337c1724cedc31d2f143d1eaa1a7a3f11c91dc17ffa",
          "sha1": "546bf255a5161bca53bddb2a210b267150eddc55",
          "md5": "7d5b6be324c392ae5a2324db324d52b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.4-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
