{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.1.2.jar",
          "url": "numen-api-common-1.20.1-0.1.2.jar",
          "size": 535620,
          "sha512": "6fe2842ccf608763745f6635df902d93bb637e012fdc483280ad926fbdd39c44398b959c71bf721d2857001fd69a28320929dde0b0e8d2ad30f47e6e3aba7daf",
          "sha256": "ceb7392dfead455e410861bb6a9b7852c0b29f253903a82d6f42f019844f515d",
          "sha1": "7fd4ac7292cebe18fcb7cddf10afbae4132b69b8",
          "md5": "b850817eeb5ea73d8932eb69f900ded8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.1.2.jar",
          "url": "numen-api-common-1.20.1-0.1.2.jar",
          "size": 535620,
          "sha512": "6fe2842ccf608763745f6635df902d93bb637e012fdc483280ad926fbdd39c44398b959c71bf721d2857001fd69a28320929dde0b0e8d2ad30f47e6e3aba7daf",
          "sha256": "ceb7392dfead455e410861bb6a9b7852c0b29f253903a82d6f42f019844f515d",
          "sha1": "7fd4ac7292cebe18fcb7cddf10afbae4132b69b8",
          "md5": "b850817eeb5ea73d8932eb69f900ded8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.1.2-sources.jar",
          "url": "numen-api-common-1.20.1-0.1.2-sources.jar",
          "size": 496516,
          "sha512": "ff6d260e641c40f7975a403f3130209c70e5e9f2ba968a7022a7006c447d8a14fa8e6a7912ed5e4186b17d6409a6f2d7a9b17f4e47945c44d5378f068100bf86",
          "sha256": "22edaea9e7168bba4c6e190fec4fd39a0b83c4b705249be1bca3cb3e0af2eaa6",
          "sha1": "778636cca9272c96a6bb6ee4ff8b0c749204ae66",
          "md5": "eb81e3ed6143a833d1d2848aa70182cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-api-common-1.20.1-0.1.2-javadoc.jar",
          "size": 692670,
          "sha512": "25ddedcf2f47abad1b5a1a33ac92e873b369f2479a8fa9701e7941a34bd73abcc782987030f3bcdb93689a316b1d4a5297e8ff0bf6322c17c875d9e7f9589f33",
          "sha256": "8e44f10cf29d41b208f9e08ced29b185b269d274897660c039e4c5976c0e2c02",
          "sha1": "a7c275e3cc0db17fb6b51a31aae3734b2795af26",
          "md5": "69e7d3699072a7fc9baeb7679ca23a04"
        }
      ]
    }
  ]
}
