{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4.1.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4.1.jar",
          "size": 2944832,
          "sha512": "9a7870ee84409b6ccc7ed5283b03696e4536ec8e1585d372f3b1e1af97de5fd36638a6aa7fba571c8af10fe8de8daf55a0e35711736c6ef85e258ca7458f130a",
          "sha256": "6a1fc8348aeed53cd7c4638d1f359cd23cf6f6a0fc9cc762438072aa5e4e3eb2",
          "sha1": "6e5ba63e991f0b9942ba1f59631c15e727a4a198",
          "md5": "ce10b3630785a8c67c36009fa925b407"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4.1.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4.1.jar",
          "size": 2944832,
          "sha512": "9a7870ee84409b6ccc7ed5283b03696e4536ec8e1585d372f3b1e1af97de5fd36638a6aa7fba571c8af10fe8de8daf55a0e35711736c6ef85e258ca7458f130a",
          "sha256": "6a1fc8348aeed53cd7c4638d1f359cd23cf6f6a0fc9cc762438072aa5e4e3eb2",
          "sha1": "6e5ba63e991f0b9942ba1f59631c15e727a4a198",
          "md5": "ce10b3630785a8c67c36009fa925b407"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4.1-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4.1-sources.jar",
          "size": 2062521,
          "sha512": "d48a35030287b49b3d6ae0b4bd00451cb1b3495faa85543642f2de8c7db09cd3c5896179ecba9006f5027859087f8d8bc49401a343ca9181b79ac319da0a4dbc",
          "sha256": "e16241e417de48a2167fe7a84397d544f063a7c9b68b633ed5bd2663b6a2a190",
          "sha1": "f46b6e9effe3aaadfc765622bc0426651eb33198",
          "md5": "fce477534db23490925aed867fcba755"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.1.4.1-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.1.4.1-javadoc.jar",
          "size": 2495310,
          "sha512": "c46cee8c0bcc82a4a4a2cfce0bdd72d689e5ae97b9445ed25107274a92c13bf7416b2e2e4fc2d1254f5a050786437ef691a5fe85919194914795915f08531374",
          "sha256": "4af1534a52343448f58ac68d123112c7fd8f4e80163f603f58d365e5068838ed",
          "sha1": "0bc11870e0e5c48d33ab684294edebd5d9fa29b5",
          "md5": "0d97c602d47b325db0f2ab90a9f4e632"
        }
      ]
    }
  ]
}
