{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.5",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.5-0.1.2.jar",
          "size": 1324004,
          "sha512": "da1b317b85a0825f0a67cf7fd961207adcab87b21687a484277c4940be4631a3309e87c9f82cbff45a1e4fafaf8208e78fa902dda91bf58fbd120e8484bf5435",
          "sha256": "0ebce2f4932c74f02da935a7c56701898234df6b5fcfee402622c51ec79998f0",
          "sha1": "cfa2a52a7228d56170a64a1a190106df4fe08a0b",
          "md5": "8e569d208b0368bf74fea9c07b30b96a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.5-0.1.2.jar",
          "size": 1324004,
          "sha512": "da1b317b85a0825f0a67cf7fd961207adcab87b21687a484277c4940be4631a3309e87c9f82cbff45a1e4fafaf8208e78fa902dda91bf58fbd120e8484bf5435",
          "sha256": "0ebce2f4932c74f02da935a7c56701898234df6b5fcfee402622c51ec79998f0",
          "sha1": "cfa2a52a7228d56170a64a1a190106df4fe08a0b",
          "md5": "8e569d208b0368bf74fea9c07b30b96a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21.5-0.1.2-sources.jar",
          "size": 1056746,
          "sha512": "7a1940d4b48c01c1014d18922b86067d8342fc0b71f6cd875e57253048c8af8bbdab7b401204b0c2830394662e7baa647ebc3799dfec0809be8001f5afd4a773",
          "sha256": "b54bb9de96a01a8afa800a4418f8c2ce2d3497859cc94f990466eaa4d3e1dfaa",
          "sha1": "63158d8f450bd4e3ee235b06268cb21ecdd4ebb6",
          "md5": "ae22b4f97cf99eab565245c6d9e54a8e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.5-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.5-0.1.2-javadoc.jar",
          "size": 1564954,
          "sha512": "982bbe991eac746b49494b6b9eb1931060c1113db5984c09c453046cca693c7bec9274759b6498a5e43bc406afe4af507756a099ae4a8686e7cfd578216e53a1",
          "sha256": "084b7a6428983eef8a36bd9b1e3def1ac71077a995bdb21d1036f1b0864c2a6a",
          "sha1": "26b77b99f79324ddd888585427c39ff09f696809",
          "md5": "6c267b3156bafdeedc35441422d72ac4"
        }
      ]
    }
  ]
}
