{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.10",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.10",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.10",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.10-0.1.3.jar",
          "url": "numen-api-common-1.21.10-0.1.3.jar",
          "size": 549936,
          "sha512": "c7419a708ba73ae83c3f6686c2cb212fea2355ccc23769bc17146a898597d44cd594da27dd52ac9c6015d7f42dc349ec192a3837f364b0da557d00669c2c16db",
          "sha256": "9f08de2c0de19e9ca21f8c8ca56a933b3f71c4fa0dc761dae4bbac4ee0334b52",
          "sha1": "02f7e686265975735e67807ce005b5e92dcc6484",
          "md5": "d7a3c67ba3dbcbffb3dec4e5c0b2e78c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.10",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.10",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.10-0.1.3.jar",
          "url": "numen-api-common-1.21.10-0.1.3.jar",
          "size": 549936,
          "sha512": "c7419a708ba73ae83c3f6686c2cb212fea2355ccc23769bc17146a898597d44cd594da27dd52ac9c6015d7f42dc349ec192a3837f364b0da557d00669c2c16db",
          "sha256": "9f08de2c0de19e9ca21f8c8ca56a933b3f71c4fa0dc761dae4bbac4ee0334b52",
          "sha1": "02f7e686265975735e67807ce005b5e92dcc6484",
          "md5": "d7a3c67ba3dbcbffb3dec4e5c0b2e78c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.10-0.1.3-sources.jar",
          "url": "numen-api-common-1.21.10-0.1.3-sources.jar",
          "size": 508853,
          "sha512": "14e19d5331839a93005b53fe8d5eb97a3cdf30d9dc6b1fd0b71678698d08beafd5ca3eaef5f929f5f70ade4b1b635256b7fa1f968c805127a7cde2b76eaa4a47",
          "sha256": "26e074264feacd0c6f6fb3c30dd7833d8c2f3f227cf96d92112ab4770125558e",
          "sha1": "221a14b813ccc8da30cb2245ce821e576a4a236c",
          "md5": "ff333e023fdebd281371fd3c1bd2bd57"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.10-0.1.3-javadoc.jar",
          "url": "numen-api-common-1.21.10-0.1.3-javadoc.jar",
          "size": 750600,
          "sha512": "e735ff45106b340e0cf9d3f865421b20447ca86b27ce6f8534c1b05c571a82edce2bb05cadce7b798145b78d7b43afd9338e01663e9dc158ec477b1b80343ddd",
          "sha256": "cafa9c7658722cfbe66da35448d64bfc4b3b418088eeee241811dd28cfa17972",
          "sha1": "ea8e6ab375ff462c2e7914461b0f1f2e858c1f04",
          "md5": "f93954eb7b87717e83ade941d661a1b6"
        }
      ]
    }
  ]
}
