{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.21.8",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.21.8-0.1.4.1.jar",
          "url": "numen-common-1.21.8-0.1.4.1.jar",
          "size": 1162910,
          "sha512": "6137abd8d5b3a5f3610f076eea57a3184353183a0828a66e36d7cc3fe4b7401fc5bf27fce3ade2f402cee662ea54e188ac28a0d02fee0322e10571ee3bbce0cc",
          "sha256": "39ea41cd417fd8be94ad1d5995b066851c4a1d07cf6b6a001a215650d1199e5b",
          "sha1": "b16cf42db8c86517a6be3a604e72cdb297a8213e",
          "md5": "88ce74039308e7d593467a74f6994399"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.8-0.1.4.1.jar",
          "url": "numen-common-1.21.8-0.1.4.1.jar",
          "size": 1162910,
          "sha512": "6137abd8d5b3a5f3610f076eea57a3184353183a0828a66e36d7cc3fe4b7401fc5bf27fce3ade2f402cee662ea54e188ac28a0d02fee0322e10571ee3bbce0cc",
          "sha256": "39ea41cd417fd8be94ad1d5995b066851c4a1d07cf6b6a001a215650d1199e5b",
          "sha1": "b16cf42db8c86517a6be3a604e72cdb297a8213e",
          "md5": "88ce74039308e7d593467a74f6994399"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.8-0.1.4.1-sources.jar",
          "url": "numen-common-1.21.8-0.1.4.1-sources.jar",
          "size": 876608,
          "sha512": "4c3946d358f1f8c16ad0c1b2ec211d4a32fff3cfddc8e954061435cbf540014a9cc1609287761414eabbd1f84a91c6ba80036a20d09cfb5210163e566de5ca0e",
          "sha256": "1223a1183bc6f1d5cb5d2119f0647fdaa23d3e0ff9427f0c410a5dbf9febd6b0",
          "sha1": "2e14e34cc2a37da1f10c31c5917559e54262e797",
          "md5": "4986cf721bd35b51799abcc84e6b3703"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.21.8-0.1.4.1-javadoc.jar",
          "url": "numen-common-1.21.8-0.1.4.1-javadoc.jar",
          "size": 1571711,
          "sha512": "061e0c9895b3af73fffa7601795a2783c028296a7fe307c8a234dfbc44d2ed80cc48c128b31c4f461f101587c19851bface5b9eeafa1ee763900caac75f65568",
          "sha256": "f38ae34f3ffb11c9b00460c63a965384b550dc7be6f678d2b8ce891bebdb1bca",
          "sha1": "c5ac308e11dfb3e1f4939176f27109069135ab15",
          "md5": "49e6165806ba5475fc1ae15af7c968ab"
        }
      ]
    }
  ]
}
