{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.2",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.3.jar",
          "url": "numen-api-fabric-1.20.2-0.1.3.jar",
          "size": 1353109,
          "sha512": "48e512e072cc04f459fa01cdabb9baf4994d8453513096bdd5cd93f9d0b27d4bcb15431d03ef96bc74978eb95692da234c269b3974e9044575920f3366dfc5a4",
          "sha256": "90ba1315583a4f9e1470b15414b0984c47e669bfa314d2e88f9d0dde5df0f5b0",
          "sha1": "619335283f54aadd1881dc21c34db9a728fd7e91",
          "md5": "c67e0a8809fcc21b25e5aa8a96400a1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.0+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.3.jar",
          "url": "numen-api-fabric-1.20.2-0.1.3.jar",
          "size": 1353109,
          "sha512": "48e512e072cc04f459fa01cdabb9baf4994d8453513096bdd5cd93f9d0b27d4bcb15431d03ef96bc74978eb95692da234c269b3974e9044575920f3366dfc5a4",
          "sha256": "90ba1315583a4f9e1470b15414b0984c47e669bfa314d2e88f9d0dde5df0f5b0",
          "sha1": "619335283f54aadd1881dc21c34db9a728fd7e91",
          "md5": "c67e0a8809fcc21b25e5aa8a96400a1d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.3-sources.jar",
          "url": "numen-api-fabric-1.20.2-0.1.3-sources.jar",
          "size": 1104320,
          "sha512": "32a57468067df5ac58516f9f783661e11b73dc19f851154345c502737c3a6a2f7bdcab8310fd8aad7b1a86c53a76313156c752d597f70361a5d4936c3948a664",
          "sha256": "6ef46e333728609f3f5068d8624ee58362b7a58c7dbb39c3bcee6f8bd35533d7",
          "sha1": "fd0a162b19013c38678b61dff286c9ed285d5404",
          "md5": "4b591e5d4960190252e7b050f01529a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.3-javadoc.jar",
          "url": "numen-api-fabric-1.20.2-0.1.3-javadoc.jar",
          "size": 1563566,
          "sha512": "26cdeb3e2eefb00d630fb1cb2b51904bbd8723ca153b7ebde63f775ea2b16dc04094a8bd235c30e1de8977227504ccbd075cf0743d74f17f163e39db2b3bd480",
          "sha256": "961e103cb1665f56dd6b5376c8f4bffb87be412fe203e6469f9eb6369d90ae3c",
          "sha1": "81bb093292768c845c5c084b50cc7bddcdaa52d1",
          "md5": "9f56f09b34845af24941838cb7f6ebe2"
        }
      ]
    }
  ]
}
