{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-26.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2.jar",
          "url": "numen-neoforge-26.2-0.1.2.jar",
          "size": 2568777,
          "sha512": "e11ea114245d54d3e0cc9f56547c4082310c0f5dbebc3b4bd515efeafcc4e1e01dfa3ff392e5dd770f2f9129c93edd2cb39f203fea795890725531e22fc8181b",
          "sha256": "83cbc0ed0dd4c4dca6a5bc82664994a9bad2f66d0f228a24b1cdcf90a961fb2c",
          "sha1": "612e20deb0cc81b76a6af43dbd71917ddd49ceb6",
          "md5": "af66b2f99ee0d1c77d4c2757f5501d2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2.jar",
          "url": "numen-neoforge-26.2-0.1.2.jar",
          "size": 2568777,
          "sha512": "e11ea114245d54d3e0cc9f56547c4082310c0f5dbebc3b4bd515efeafcc4e1e01dfa3ff392e5dd770f2f9129c93edd2cb39f203fea795890725531e22fc8181b",
          "sha256": "83cbc0ed0dd4c4dca6a5bc82664994a9bad2f66d0f228a24b1cdcf90a961fb2c",
          "sha1": "612e20deb0cc81b76a6af43dbd71917ddd49ceb6",
          "md5": "af66b2f99ee0d1c77d4c2757f5501d2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2-sources.jar",
          "url": "numen-neoforge-26.2-0.1.2-sources.jar",
          "size": 1075831,
          "sha512": "e7230b2839493be51af5bf77a624deb15ec1c8db6ec20a304d6e51265be270ebdc442ca8d91662a6175dcb29fade3b590cd641339e42be5273447b615376d504",
          "sha256": "bdf87cf205c6d786c443b29addeb3a294bfdba2de878dab11a4a9332c780de1e",
          "sha1": "6a3a0383cca473de5ff9489c4c4d25723052f3ba",
          "md5": "8b68119bf97d8b82068ede42a3a3ac5f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2-javadoc.jar",
          "url": "numen-neoforge-26.2-0.1.2-javadoc.jar",
          "size": 5665832,
          "sha512": "ab1d1159ead136f6c748edd6557facda6bdfc0998ed7e6672d2927caa8ca3d89a8fcf2bf43d9300e1903f093fe37390c4e087bf600aa8aa55a4009c6554e49ce",
          "sha256": "5493b886d347db998b5d0f2b08724efc4647135e154b0080db9b5944fb87d770",
          "sha1": "a67df0c4e83bde97ffa96780fd0143c8b9d34f01",
          "md5": "7298ef6149b52ed095d323d2970bc7ad"
        }
      ]
    }
  ]
}
