{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-26.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2.jar",
          "url": "numen-neoforge-26.2-0.1.2.jar",
          "size": 2568781,
          "sha512": "4dc0b1581737495c6f0972078ff3dec6a8f387cfd07042aa2a953fbbec6514df5cff3dbfac62212bd8eb90d122d73bcbab78d61fb7f4a73e24de2deefe75241e",
          "sha256": "bfbe202d4592571213b3aa4278b71fa127adf4eb46f8d38febaed32fbcbdb87e",
          "sha1": "8913e6da78f21084adae0e1bbb69b8140284b8e2",
          "md5": "fa141903ff62531fe6b8a0be3d907bc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-26.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2.jar",
          "url": "numen-neoforge-26.2-0.1.2.jar",
          "size": 2568781,
          "sha512": "4dc0b1581737495c6f0972078ff3dec6a8f387cfd07042aa2a953fbbec6514df5cff3dbfac62212bd8eb90d122d73bcbab78d61fb7f4a73e24de2deefe75241e",
          "sha256": "bfbe202d4592571213b3aa4278b71fa127adf4eb46f8d38febaed32fbcbdb87e",
          "sha1": "8913e6da78f21084adae0e1bbb69b8140284b8e2",
          "md5": "fa141903ff62531fe6b8a0be3d907bc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2-sources.jar",
          "url": "numen-neoforge-26.2-0.1.2-sources.jar",
          "size": 1075829,
          "sha512": "ef50661fe375f12eddeb7c6ee3e17f4a251c89cac65eb6df473612827a9bcf075596d31990a772f4cb74ebd8ca093248e721ce8068f2b7202a81f0b567a8bcfd",
          "sha256": "5920bd081b8dba5910827bebb11093b44a354ed1ddb3f2e19098de72019f79fe",
          "sha1": "8d8fa6ebe1eae19e1c9df331d294cc717d3801a6",
          "md5": "8a37ef4bd4890b64dbff63726294c0b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-26.2-0.1.2-javadoc.jar",
          "url": "numen-neoforge-26.2-0.1.2-javadoc.jar",
          "size": 5665832,
          "sha512": "ab1d1159ead136f6c748edd6557facda6bdfc0998ed7e6672d2927caa8ca3d89a8fcf2bf43d9300e1903f093fe37390c4e087bf600aa8aa55a4009c6554e49ce",
          "sha256": "5493b886d347db998b5d0f2b08724efc4647135e154b0080db9b5944fb87d770",
          "sha1": "a67df0c4e83bde97ffa96780fd0143c8b9d34f01",
          "md5": "7298ef6149b52ed095d323d2970bc7ad"
        }
      ]
    }
  ]
}
