{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.20.4",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.3.jar",
          "url": "numen-api-common-1.20.4-0.1.3.jar",
          "size": 545200,
          "sha512": "499c1d697d02109035c088f4cf4fbac35e131051b04c5b31a5816d9c36377dfda11ea3cc7e8e9a76b71b34c997d07303d50c8d1dfd6037989acaa552a021bc16",
          "sha256": "e1b875833c611f76d0d92baa1589b883e64e000ab8881dcbfb0b705a609938ab",
          "sha1": "475c3e902aa4fce0d79c73c9503acabe8fce331d",
          "md5": "76aefa8ba4a4f76b0c2250751bd9e2e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.3.jar",
          "url": "numen-api-common-1.20.4-0.1.3.jar",
          "size": 545200,
          "sha512": "499c1d697d02109035c088f4cf4fbac35e131051b04c5b31a5816d9c36377dfda11ea3cc7e8e9a76b71b34c997d07303d50c8d1dfd6037989acaa552a021bc16",
          "sha256": "e1b875833c611f76d0d92baa1589b883e64e000ab8881dcbfb0b705a609938ab",
          "sha1": "475c3e902aa4fce0d79c73c9503acabe8fce331d",
          "md5": "76aefa8ba4a4f76b0c2250751bd9e2e3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.3-sources.jar",
          "url": "numen-api-common-1.20.4-0.1.3-sources.jar",
          "size": 506543,
          "sha512": "f957e11c5027f24a20d6d470e679abe6a306c5a5b9a15daa7da55bdff890e17944e95298775faa8f9a87a0ecb3b16f36f7997a48785678d6852bb2beea76cd64",
          "sha256": "8765a0491e8e9e561b3896fadbcb16acba3c6c4ffaa01b564c2da34349cf1221",
          "sha1": "9a6987a9c3d4d27c6ea4394f1ac403ad66ed6589",
          "md5": "57929731d49a44d3d152d16f7920a8ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.20.4-0.1.3-javadoc.jar",
          "url": "numen-api-common-1.20.4-0.1.3-javadoc.jar",
          "size": 719538,
          "sha512": "877592b57ebeb44bc29499235420dc105d443b7b1f4173e0f8bd6c648581f940a06e614f1f1a900e82b93e0e92f79380254104c8c71dc783e2ecfbbc89e19a5c",
          "sha256": "2f2857bb2eabbb41dd951d72eb5590257c67f86d099cf5aa92bd1fdc340cae09",
          "sha1": "cfee4007d479c2be645113e9f68fe71b5a3771f0",
          "md5": "028e9b0cc958d8cafb378b38d4c51109"
        }
      ]
    }
  ]
}
