{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.10",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-neoforge-1.21.10-0.1.2.jar",
          "size": 2567141,
          "sha512": "7f8de59943d97678d15731c6ac981a2a4c8e556fa5b0a81c75e1485bbce44c0715a1cbc2fb6ad30981d066cf82c96b37eec040f030e9fc37aae1f35dd83169fc",
          "sha256": "f520e6172a7942d51dbfb056a4fc547811d2c84bae97e54bfb3b40914766a578",
          "sha1": "66e76fe124c8eb6b3c14c5b81da342ded9ed1298",
          "md5": "8c83d2626389f96fe1a7691bf9d7d0fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-neoforge-1.21.10-0.1.2.jar",
          "size": 2567141,
          "sha512": "7f8de59943d97678d15731c6ac981a2a4c8e556fa5b0a81c75e1485bbce44c0715a1cbc2fb6ad30981d066cf82c96b37eec040f030e9fc37aae1f35dd83169fc",
          "sha256": "f520e6172a7942d51dbfb056a4fc547811d2c84bae97e54bfb3b40914766a578",
          "sha1": "66e76fe124c8eb6b3c14c5b81da342ded9ed1298",
          "md5": "8c83d2626389f96fe1a7691bf9d7d0fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.10-0.1.2-sources.jar",
          "size": 1074200,
          "sha512": "16c58c4b4a5270a0ec1645702484e6e51328f0b973597f4687dc22094ad6c5d4dcb5a0ff6bbc68448ba4915e24dbc7b56a08d29e63814d8c0a9be7685f66d823",
          "sha256": "bd06a60915f61aae100145a10619becc306d34a92863e6b3daa9f354ca48db52",
          "sha1": "0c864b16ff21987178e2d9a22b59e211d8760855",
          "md5": "8f6de07264e38134ffa3c5b928a95821"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.10-0.1.2-javadoc.jar",
          "size": 1540125,
          "sha512": "9b2525aff5a9c68279404bdd94523d352b7100f96f21674df1da7fe7f90c9ee420d7ce3560c4c6a341976b8d1d02583fb1dde2b7a1135c53cf8bb6317f58ae65",
          "sha256": "6b34b3503410bfdc0922ee08b6cb68d31af37f6f512402b6aa475a048057bf8b",
          "sha1": "532c1e95ae821aea734e9cd53870d59ba18da8bb",
          "md5": "0f6ec28b58b362167865183611fca108"
        }
      ]
    }
  ]
}
