{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.10",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-neoforge-1.21.10-0.1.2.jar",
          "size": 2567144,
          "sha512": "1d63c5295020133c6bec069cce5240bf19a049cee0cac0502211c103ad51d2e47891a2550101d6e03f586edeb1e1ca24a55f7b81fc9b3e473c2b18b8c9560b87",
          "sha256": "ec797e1560ad720c6b4745e1191a73d2dcb89728d5841f8fae1360750d5307e7",
          "sha1": "673f8f5bf1e021a14a02c12f8854c07ddcdfd633",
          "md5": "92445c7bc8d878354109ed89f8a62e6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-neoforge-1.21.10-0.1.2.jar",
          "size": 2567144,
          "sha512": "1d63c5295020133c6bec069cce5240bf19a049cee0cac0502211c103ad51d2e47891a2550101d6e03f586edeb1e1ca24a55f7b81fc9b3e473c2b18b8c9560b87",
          "sha256": "ec797e1560ad720c6b4745e1191a73d2dcb89728d5841f8fae1360750d5307e7",
          "sha1": "673f8f5bf1e021a14a02c12f8854c07ddcdfd633",
          "md5": "92445c7bc8d878354109ed89f8a62e6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.10-0.1.2-sources.jar",
          "size": 1074202,
          "sha512": "aa0d8e3b9882077a5f6292b28c9c44599de95d7f612224aca5f68ee9d4c86f2e6f1720301386bd8abf50656656982ea39ce7dc1818fa74afe398bac8f7acdfb6",
          "sha256": "da3bc0d560b6214db2ac8d63040b306a6b4a6d5d106beaf396ea0376d5ec35b9",
          "sha1": "fc8acc5cfc9adde81fb3be217195860d38e69283",
          "md5": "3785b60b3e29e28652869c4ecc2c7ea7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.10-0.1.2-javadoc.jar",
          "size": 1540125,
          "sha512": "9b2525aff5a9c68279404bdd94523d352b7100f96f21674df1da7fe7f90c9ee420d7ce3560c4c6a341976b8d1d02583fb1dde2b7a1135c53cf8bb6317f58ae65",
          "sha256": "6b34b3503410bfdc0922ee08b6cb68d31af37f6f512402b6aa475a048057bf8b",
          "sha1": "532c1e95ae821aea734e9cd53870d59ba18da8bb",
          "md5": "0f6ec28b58b362167865183611fca108"
        }
      ]
    }
  ]
}
