{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.10",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-neoforge-1.21.10-0.1.2.jar",
          "size": 2567139,
          "sha512": "2b83e0fe107d331b2124b88c40b2df8905348447a58c8b2d4c112ba72dd172de640ff5852c23748cff12758230734b9b6a69337a343bc343fbdbabd5ef165412",
          "sha256": "50df170aa3414feaeda52fcdb4698cdd0a7f6b3919fdf00a432fe1f3580fd7e3",
          "sha1": "9d47409d0680608f2b71a43ce758908c07736471",
          "md5": "adfade83c67e452136045abcad614042"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.10",
          "version": {
            "requires": "0.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-neoforge-1.21.10-0.1.2.jar",
          "size": 2567139,
          "sha512": "2b83e0fe107d331b2124b88c40b2df8905348447a58c8b2d4c112ba72dd172de640ff5852c23748cff12758230734b9b6a69337a343bc343fbdbabd5ef165412",
          "sha256": "50df170aa3414feaeda52fcdb4698cdd0a7f6b3919fdf00a432fe1f3580fd7e3",
          "sha1": "9d47409d0680608f2b71a43ce758908c07736471",
          "md5": "adfade83c67e452136045abcad614042"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.10-0.1.2-sources.jar",
          "size": 1074201,
          "sha512": "b0f010269a1b29b4ed6bce192381d775dffebf8ebf1215cf7c47530b88aa6d075c54b316175bc213a071211c5de72ebcba61a48d82fa052c6d4e51679cebf746",
          "sha256": "c32197ba59d86591c4506e23cf19546287cd936376262ddd03c947fe90b188d2",
          "sha1": "b28a0adbd721c68c3c68ba7e1097af2c4d180d15",
          "md5": "431d3dd25dc418d074be4deae0bbc87b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.10-0.1.2-javadoc.jar",
          "size": 1540125,
          "sha512": "9b2525aff5a9c68279404bdd94523d352b7100f96f21674df1da7fe7f90c9ee420d7ce3560c4c6a341976b8d1d02583fb1dde2b7a1135c53cf8bb6317f58ae65",
          "sha256": "6b34b3503410bfdc0922ee08b6cb68d31af37f6f512402b6aa475a048057bf8b",
          "sha1": "532c1e95ae821aea734e9cd53870d59ba18da8bb",
          "md5": "0f6ec28b58b362167865183611fca108"
        }
      ]
    }
  ]
}
