{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.4",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.4",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.1.3.jar",
          "url": "numen-api-fabric-1.21.4-0.1.3.jar",
          "size": 1353854,
          "sha512": "7a3400b46059b73aac988c9b6deac9af915c9a72f8004aea22de997da027e10624515560fab749e3996bb098f95a26bb74875721d4a0fe9d8a85aff5921412d6",
          "sha256": "36abac8e19dbb97c5699084361fa727b71a119824e68e7c9825d03e002792f0c",
          "sha1": "55720ef8c100c7fd1cd5592c2dec0a8c50d8562f",
          "md5": "5f307a1016518be55ea358cc3a94e996"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.4",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.117.0+1.21.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.1.3.jar",
          "url": "numen-api-fabric-1.21.4-0.1.3.jar",
          "size": 1353854,
          "sha512": "7a3400b46059b73aac988c9b6deac9af915c9a72f8004aea22de997da027e10624515560fab749e3996bb098f95a26bb74875721d4a0fe9d8a85aff5921412d6",
          "sha256": "36abac8e19dbb97c5699084361fa727b71a119824e68e7c9825d03e002792f0c",
          "sha1": "55720ef8c100c7fd1cd5592c2dec0a8c50d8562f",
          "md5": "5f307a1016518be55ea358cc3a94e996"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.1.3-sources.jar",
          "url": "numen-api-fabric-1.21.4-0.1.3-sources.jar",
          "size": 1094439,
          "sha512": "2ce74ae00caa7e6b76a0a264221f189e4ec1cca72eb04763c999ec2267f9df4ca0609d5c1c7dd51b327aa1c1ed9e212c9522a345704a3bd2907f8cfed49837d2",
          "sha256": "8b16bd4d859f7940890663c70a93ba6ba1a78f5d97a46e80ad41af47f8cae5c1",
          "sha1": "f0f56fb508fc260c5004793ec9406fc1969bb660",
          "md5": "ef08970aa21a7b2e163f501e73805ea5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.4-0.1.3-javadoc.jar",
          "url": "numen-api-fabric-1.21.4-0.1.3-javadoc.jar",
          "size": 1613052,
          "sha512": "398ead082ac0fc2e18995fa591252b6c14ebabae4df858cdb3acfdb75a380c49757c524e4c8662c038cac249520456239639c7778c95b73009b646501b5c406a",
          "sha256": "3f48c8fb655dbbf8c12385b90c1bf8320dac75739b5bef412b634e8a307d01c0",
          "sha1": "7c953903789e67dc9b6147f41b348753890295e5",
          "md5": "380430beceb4fede2434bcafcc9c0a1d"
        }
      ]
    }
  ]
}
