{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.4",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4.1.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4.1.jar",
          "size": 2940473,
          "sha512": "8b461d950fe5a41f4536842d0db58acdfcccf42d214f224762c8e4ba0da2aa6f34f34e3d90abb1954d64f45a11c6a60b3dc2e40d1fdae6ae065dab049fa68761",
          "sha256": "f48359bd87210c09374faa1bb27f41cb0c404b9445f4bb29054f0624d6002d11",
          "sha1": "b9ad7d378423a44937de74e98cf94a02084ee11d",
          "md5": "7a0e6664af07d4810341f0691d3c6b88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.4",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4.1.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4.1.jar",
          "size": 2940473,
          "sha512": "8b461d950fe5a41f4536842d0db58acdfcccf42d214f224762c8e4ba0da2aa6f34f34e3d90abb1954d64f45a11c6a60b3dc2e40d1fdae6ae065dab049fa68761",
          "sha256": "f48359bd87210c09374faa1bb27f41cb0c404b9445f4bb29054f0624d6002d11",
          "sha1": "b9ad7d378423a44937de74e98cf94a02084ee11d",
          "md5": "7a0e6664af07d4810341f0691d3c6b88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4.1-sources.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4.1-sources.jar",
          "size": 2058661,
          "sha512": "b1ee2076ebffc5d9967ea8b6acdd90b00b11722c6756b75157425b2fbcb8b842e6200c24c4f744e40108b2e148a979700af2097e76dd0bfd9be5a125f7c4048a",
          "sha256": "f0b7987882c1356e9017b07c499312e8738a1be0166bbd3e26214a33d3c8db9e",
          "sha1": "2ed5406fee50acad1c20d4d51813816d58c7b2cf",
          "md5": "94c2ce385ed9cb26c15d42dbeeef04df"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4.1-javadoc.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4.1-javadoc.jar",
          "size": 2483884,
          "sha512": "87f9be898fc3e7a6f2d4c4ef21ea0e7ac512d80d84a1406a37ca069718502e21ad9110f98d423eb2a3458643483f1c896a4132d196049891d18c1ac405bdf53b",
          "sha256": "da14f286fac982299e0a620783d290e1df1a16fbf06f125262df9454edc7291d",
          "sha1": "06eb096da8de9bf6ac010397b0494fa6538a09bd",
          "md5": "01b63de64838b624d2023d69310019d7"
        }
      ]
    }
  ]
}
