{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.2.jar",
          "url": "numen-api-fabric-1.20.2-0.1.2.jar",
          "size": 1318538,
          "sha512": "824b082798211c81fa8bbd1e08758eeb90abc3bf3b673fc1e7eeeb510322250189467c5af66197349d8367c981373f7667b41aa5bc2807090e2d9c40a6346cff",
          "sha256": "2358fe79c6d316801bb091cc5655f9164a518397aec82caabcc292d01671cef2",
          "sha1": "d9129217270cfa77ec22b2bf52deb370ab712c15",
          "md5": "3b36e7325b0d553a497462a6640e94cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.2",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.91.0+1.20.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.2.jar",
          "url": "numen-api-fabric-1.20.2-0.1.2.jar",
          "size": 1318538,
          "sha512": "824b082798211c81fa8bbd1e08758eeb90abc3bf3b673fc1e7eeeb510322250189467c5af66197349d8367c981373f7667b41aa5bc2807090e2d9c40a6346cff",
          "sha256": "2358fe79c6d316801bb091cc5655f9164a518397aec82caabcc292d01671cef2",
          "sha1": "d9129217270cfa77ec22b2bf52deb370ab712c15",
          "md5": "3b36e7325b0d553a497462a6640e94cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.2-sources.jar",
          "url": "numen-api-fabric-1.20.2-0.1.2-sources.jar",
          "size": 1068747,
          "sha512": "e7f2e1350fc82a4a3079c6428b1d8e66a56d330c37d7bdeb8a87dabe577e7ee223255d91d28b084c2c50cee221a5475b79e34f5a9b8517851f479f827c213ffe",
          "sha256": "f62ad5ee08fb087cebb275c184f106c7dcdbcda8f02b80a5b602636dfe29423c",
          "sha1": "1a80b1040f4795b53575f100212cd04e0703dbab",
          "md5": "da73cccc6c673df0e9586eb34a8cfbcc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.2-0.1.2-javadoc.jar",
          "url": "numen-api-fabric-1.20.2-0.1.2-javadoc.jar",
          "size": 1518583,
          "sha512": "43ad59cf7c6ba2457d953bd86d4823bc524607a2e860efdd61236598976239c9d4ce19abcc108cbf5ba3a0c97ac8ef5ab6ea0fb4fafdb92a706996b723d89e69",
          "sha256": "4b533bed4916c3cac798c75dbe81a2d1d38a35a71021fbedc74992cf8138ceba",
          "sha1": "4dba406644f78296a03425d831ab0ed458ab9a4e",
          "md5": "06200f5a24bb566580bb56464ff92758"
        }
      ]
    }
  ]
}
