{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-forge-1.20.1",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 912266,
          "sha512": "1737493585925349a98a1679a991cd20a5160d6a542006510a51163c9116c7174bfa2016d9fb1dd3e43d68c1e7a60eb1778566ab65ff932f34bd52650fc25cde",
          "sha256": "9c9b1a6e143e5d49615c3b96c33c3f33853606235f405fd9fdb9e3b393bf2ae1",
          "sha1": "578bdbcf9cd5dd7ebe77bcf8adeabc37d8111128",
          "md5": "d99c5cfadaf6297bc0f0a0c767acdc4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.30_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 912266,
          "sha512": "1737493585925349a98a1679a991cd20a5160d6a542006510a51163c9116c7174bfa2016d9fb1dd3e43d68c1e7a60eb1778566ab65ff932f34bd52650fc25cde",
          "sha256": "9c9b1a6e143e5d49615c3b96c33c3f33853606235f405fd9fdb9e3b393bf2ae1",
          "sha1": "578bdbcf9cd5dd7ebe77bcf8adeabc37d8111128",
          "md5": "d99c5cfadaf6297bc0f0a0c767acdc4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "size": 725529,
          "sha512": "439b6b6accd378510e5222c66125a1a7dc231b586105882b85c38a1cd652ddd80d9d33c9601f657b720cba70c8141253c531e1caa6d312e70ec1e0e1486cd889",
          "sha256": "cf54c5fa91cdfaeac74ed6d09c80f8ad043d6960e34af53635b7e69525ae1799",
          "sha1": "ea166184daaca5c1af6c02350d87dea4892e409b",
          "md5": "1f8d6ee007491d30485dffd9e18614ad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "2f6980ec8c8ea5ab11fead434d47f28921bf40b779501b2715891325f737721e1328a67e8c9c25192f37277e68af8e4989dbd7542600db8a949ab822c4ebc778",
          "sha256": "fd88e238dcba72a5f0ca34e98df5582e0eb1ffef29b49f3456a2efa018105730",
          "sha1": "59fa7debff6b7ff8ef092a08d2dedac097a5ac52",
          "md5": "164417947296d7688df3627b18f05601"
        }
      ]
    }
  ]
}
