{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-forge-1.20.1",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 912972,
          "sha512": "45602648fe534cdc73f5a6f301b357cb9229fc08438f1145fb6ebfef7b7d165d5b2058c204859c79904baf3e049677d5cb4bdb321960cc3567d8969d252a10dc",
          "sha256": "0729ef933d5789885fe594b4eed79c243db7fd562b5fcf4e3bff812a06d657cc",
          "sha1": "7dc848f7a6c2c6195224dc30bc064dce432f0b15",
          "md5": "de3e46586b0c1d34da62c89466ffa692"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.2.30_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT.jar",
          "size": 912972,
          "sha512": "45602648fe534cdc73f5a6f301b357cb9229fc08438f1145fb6ebfef7b7d165d5b2058c204859c79904baf3e049677d5cb4bdb321960cc3567d8969d252a10dc",
          "sha256": "0729ef933d5789885fe594b4eed79c243db7fd562b5fcf4e3bff812a06d657cc",
          "sha1": "7dc848f7a6c2c6195224dc30bc064dce432f0b15",
          "md5": "de3e46586b0c1d34da62c89466ffa692"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-sources.jar",
          "size": 726235,
          "sha512": "38ff2b02ceb52eb63222314bbf9a42404eaf7590ae20dd25f71e0ae617444b3f6cb5ed15f38a398ebf319845b4da9a40a880ef5d6a8bfffb606fee99dc3f606d",
          "sha256": "01acd7c37f04781773e6b4174a8fba59ccdbb8a9eee2ee9b7812cba8e07a97ca",
          "sha1": "9374bbdb6ef00628bae686f55702fc2c731289bc",
          "md5": "9010765928899a0239ad4e420560e41c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "forge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-forge-1.20.1-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "2f6980ec8c8ea5ab11fead434d47f28921bf40b779501b2715891325f737721e1328a67e8c9c25192f37277e68af8e4989dbd7542600db8a949ab822c4ebc778",
          "sha256": "fd88e238dcba72a5f0ca34e98df5582e0eb1ffef29b49f3456a2efa018105730",
          "sha1": "59fa7debff6b7ff8ef092a08d2dedac097a5ac52",
          "md5": "164417947296d7688df3627b18f05601"
        }
      ]
    }
  ]
}
