{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-26.2",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-26.2-0.1.3.jar",
          "url": "numen-common-26.2-0.1.3.jar",
          "size": 1215308,
          "sha512": "8f49728e5efdc9c74013ad64bbd824fd3d2103bf70a6a771de1088ef9d8d30bd7aaf380db1fd631f8632d36f36beddc617696d87b0de04dba0ce242ea98665fc",
          "sha256": "88ca87e46a49f715191e5bb86d9e3e19bb1e9b86432119d4e56a17c3ada65847",
          "sha1": "597386216ec78d1cbce72ec3b6374f85add9d361",
          "md5": "a3f1b31250ee7155a6cbf647dc30b7ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-26.2-0.1.3.jar",
          "url": "numen-common-26.2-0.1.3.jar",
          "size": 1215308,
          "sha512": "8f49728e5efdc9c74013ad64bbd824fd3d2103bf70a6a771de1088ef9d8d30bd7aaf380db1fd631f8632d36f36beddc617696d87b0de04dba0ce242ea98665fc",
          "sha256": "88ca87e46a49f715191e5bb86d9e3e19bb1e9b86432119d4e56a17c3ada65847",
          "sha1": "597386216ec78d1cbce72ec3b6374f85add9d361",
          "md5": "a3f1b31250ee7155a6cbf647dc30b7ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-26.2-0.1.3-sources.jar",
          "url": "numen-common-26.2-0.1.3-sources.jar",
          "size": 1005152,
          "sha512": "ae6437c2a7445aed13a5591b703e779e1119be40e5939f668f35666077a0a532f6b2024ddf2356a9ba907bffcba608c66a0836368d47ca4a9e623678a0731480",
          "sha256": "5eb0b4853955843199df27e5547d7a99b444ab1d8e1964e118beb6bda17d7ef7",
          "sha1": "41484d4ea579b49e9e2bb164da738f3cdb7d16c1",
          "md5": "6117a4f6a313c68fc8f093a11b6b484a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-26.2-0.1.3-javadoc.jar",
          "url": "numen-common-26.2-0.1.3-javadoc.jar",
          "size": 5589194,
          "sha512": "1ffee3490e7618f8956aaf8388a9773f180ef1fadb382891f6950ef9717004478d513a56d0e6da4a9bf8fcde8f4b49c2cb1bf4b5658696f2941928b4ee7c9dfc",
          "sha256": "68f210fb48a2fa764d882a2595e2e7f1323f904e6405d462602dd98ec995bda6",
          "sha1": "a447fc8e4208470317b0b51c77f1849f01d5ee69",
          "md5": "45c4c60e9091be00a473e5bc5055ece7"
        }
      ]
    }
  ]
}
