{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.3.jar",
          "url": "numen-api-neoforge-1.21-0.1.3.jar",
          "size": 1357007,
          "sha512": "37bc772d9d346d248c8feec137afeb510245c45c3d81ea96abe60110cd04bb0969a1654f0d856268187ccf09a8d9a6be31914508f113ebf3eee9bb2e4a0af5c4",
          "sha256": "91786e78042c8d65cc1456ce45e20950a79b8cef99868b5a6d367239bc4f443a",
          "sha1": "dddebf3b11e1bb958755ec7004d3c4bf2a8a57d9",
          "md5": "d15b583f79c69141dea855ccc9de065d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.3.jar",
          "url": "numen-api-neoforge-1.21-0.1.3.jar",
          "size": 1357007,
          "sha512": "37bc772d9d346d248c8feec137afeb510245c45c3d81ea96abe60110cd04bb0969a1654f0d856268187ccf09a8d9a6be31914508f113ebf3eee9bb2e4a0af5c4",
          "sha256": "91786e78042c8d65cc1456ce45e20950a79b8cef99868b5a6d367239bc4f443a",
          "sha1": "dddebf3b11e1bb958755ec7004d3c4bf2a8a57d9",
          "md5": "d15b583f79c69141dea855ccc9de065d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.3-sources.jar",
          "url": "numen-api-neoforge-1.21-0.1.3-sources.jar",
          "size": 1088838,
          "sha512": "a705e6eb6793a49710958f5c3848621a1643a79fe84d5ccd391fa5bf683927b798bb3996238e9e525b09dba97700eac863aec36ab7566f2a6d5f59eaade38faf",
          "sha256": "2e3812384b940d1ca40cc0d37dd633f50ac3c6b218f1c045d4e89236e0e3155c",
          "sha1": "050939015250b9143622112b94701748065a9052",
          "md5": "113c6960ab1ff1065e6767ccd6e79f80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.1.3-javadoc.jar",
          "url": "numen-api-neoforge-1.21-0.1.3-javadoc.jar",
          "size": 1609629,
          "sha512": "ef75209c8a83246b67bb92e47f665ab744fb192af768fd988ed8e87722afef95e87f6a7f3bd88c54cea35a49b8cbe3429fdc4ebfb6d3ea0940caf7aa8ab1d557",
          "sha256": "7b7a7655bbaafe362079f5d9eee0a867702eff81db384d2891a36e0e2f0ebb40",
          "sha1": "d7690df00d7303fefa3d6efe9d121a77a162170f",
          "md5": "a0a3e8831e76cd6a1b87d7e8ed17d38e"
        }
      ]
    }
  ]
}
