{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.8",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.4.1.jar",
          "url": "numen-neoforge-1.21.8-0.1.4.1.jar",
          "size": 4350538,
          "sha512": "c987f7855f9390f0970bd554ee2b2e687046c625b50c7e37c71363ad3928ca57a7882daa4e652e240df924182eb6f11d67b616edb6154de913a6f33edb1c207e",
          "sha256": "2994a1101ac93f18022c98c8be4c5cf6a4a61f298e70b8892d0627b1bb922ddf",
          "sha1": "29c6ba365b9839bfb5257978fe34f1b995e17f85",
          "md5": "2a6e6c67e94460ad735a7a369c739920"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.4.1.jar",
          "url": "numen-neoforge-1.21.8-0.1.4.1.jar",
          "size": 4350538,
          "sha512": "c987f7855f9390f0970bd554ee2b2e687046c625b50c7e37c71363ad3928ca57a7882daa4e652e240df924182eb6f11d67b616edb6154de913a6f33edb1c207e",
          "sha256": "2994a1101ac93f18022c98c8be4c5cf6a4a61f298e70b8892d0627b1bb922ddf",
          "sha1": "29c6ba365b9839bfb5257978fe34f1b995e17f85",
          "md5": "2a6e6c67e94460ad735a7a369c739920"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.4.1-sources.jar",
          "url": "numen-neoforge-1.21.8-0.1.4.1-sources.jar",
          "size": 1118595,
          "sha512": "2d4592ea62d77af06d175317a11c0590ac56b348fcd31e808ddda21e9e5701f075f9fe6dd10fac144604a42a56db985ec77e3480f51de6f044e2810148ed7e67",
          "sha256": "09f8f9abfbda29ac53ae5012b7f198753ebe6b6f2461b0a4e3096bb9f87f72bd",
          "sha1": "fa9e98008f35462ed9b4e0ad9359fb9cc2f0a844",
          "md5": "a3d316ed73b6f3030ab75815fe61783c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.4.1-javadoc.jar",
          "url": "numen-neoforge-1.21.8-0.1.4.1-javadoc.jar",
          "size": 1853881,
          "sha512": "659625765fbab6b02f5177f08220b2824dafca28d6a0b8268897b2d2a890da1dd4bba76b5a2f900bddb7499b1772bc5e69db79c6780a969bfa0e6cc65f703a98",
          "sha256": "7f9fe99a28562b3b6bd3d91fbe3de799cad8efee5e562e800b17fd6992643e90",
          "sha1": "d1ecf00de3539174d77aa460959a7bd57abd9acb",
          "md5": "b56820bde720128867cf3376dfc0fbd1"
        }
      ]
    }
  ]
}
