{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT.jar",
          "size": 970178,
          "sha512": "ff12e4e4369d20b7d3d96c434c6cb2bab26778d2ce7e3861e80e8e04c1b37046bf381b186811d9f4142f17713b19d798e2582d2098ebfd9bbf14e4e6a2049348",
          "sha256": "2282af2960851d6981fdcb1a7b53671af6d7b865dd601ab7cf473288aaeba70e",
          "sha1": "12a6fe00cbf3fc16642cd54bb99d7463961d06f1",
          "md5": "bf0e22a4c9aa50d0c32503e4b1af17d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT.jar",
          "size": 970178,
          "sha512": "ff12e4e4369d20b7d3d96c434c6cb2bab26778d2ce7e3861e80e8e04c1b37046bf381b186811d9f4142f17713b19d798e2582d2098ebfd9bbf14e4e6a2049348",
          "sha256": "2282af2960851d6981fdcb1a7b53671af6d7b865dd601ab7cf473288aaeba70e",
          "sha1": "12a6fe00cbf3fc16642cd54bb99d7463961d06f1",
          "md5": "bf0e22a4c9aa50d0c32503e4b1af17d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT-sources.jar",
          "size": 783296,
          "sha512": "09d3ba3af249c66b944ec0ff5dfff58d391a3fd4945be9462a334da32d2007835642248475cf643c9677dd62799931b85937ae652a22deb3b5e515c2f8cc1a8b",
          "sha256": "4bab1bae7e30a65c630032248726a3231fc31408644632dbfe6ee7dc9c4afe9c",
          "sha1": "b8eed744ade689a2d3634b1e7681768f3c7f73d2",
          "md5": "60760c031d42e9d1030d3668958f4d2e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.8-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
