{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-common-1.21.1",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.1.4.1.jar",
          "url": "numen-api-common-1.21.1-0.1.4.1.jar",
          "size": 1039860,
          "sha512": "4f80bf225276d1d7a60cae1adbdcdcf4ad7750cf89eeba5b3b468ccda3770f98e1851815258bc8e5e4a5b080cc6d37438a36bb7cf51882677f9f62c519dba883",
          "sha256": "cb41c086254463d56b080d71f6f6c130b5936508f861fa3b7752c1298629060d",
          "sha1": "f3f5d2e6933aa7dd121f8e32d1c19ca0109f1be6",
          "md5": "2396f711e913b8f0f448d116614330bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.21.1",
          "version": {
            "requires": "0.1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.1.4.1.jar",
          "url": "numen-api-common-1.21.1-0.1.4.1.jar",
          "size": 1039860,
          "sha512": "4f80bf225276d1d7a60cae1adbdcdcf4ad7750cf89eeba5b3b468ccda3770f98e1851815258bc8e5e4a5b080cc6d37438a36bb7cf51882677f9f62c519dba883",
          "sha256": "cb41c086254463d56b080d71f6f6c130b5936508f861fa3b7752c1298629060d",
          "sha1": "f3f5d2e6933aa7dd121f8e32d1c19ca0109f1be6",
          "md5": "2396f711e913b8f0f448d116614330bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.1.4.1-sources.jar",
          "url": "numen-api-common-1.21.1-0.1.4.1-sources.jar",
          "size": 784969,
          "sha512": "eeffbe18327973aa42cbc691aefdfe808cf7c579ed5c3bf66a585c269ad22f536b6f4701086bacfda804b6fd63677ad66efcde92f01dd47db567f9b995c2ef24",
          "sha256": "fb448972359ab212368748e69b33f8eda8e84f28ed2b62945d89385316aded7d",
          "sha1": "52254f69816c99a1e2f0cb134d89b428f4e69c2b",
          "md5": "b43945401d4c3ed407020681a1913d9a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-common-1.21.1-0.1.4.1-javadoc.jar",
          "url": "numen-api-common-1.21.1-0.1.4.1-javadoc.jar",
          "size": 1524409,
          "sha512": "0ba114f02b0dd8ebcaa615873e19896bf93943e3fc68361d3066e5017109aedd46664ab77995460372196f80e1dc9efe16731f9e3c6cfd86890495aa4139699e",
          "sha256": "5f931cf538cfd50ede86b9c3c55d2d7a6737c790828cd07a3e04b68bc9349273",
          "sha1": "f33260cd94e74618c341f335f333d5de588f45e2",
          "md5": "b0eee6dcd7fd4764900b1759dfd434ab"
        }
      ]
    }
  ]
}
