{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.2",
    "version": "0.1.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.4.1.jar",
          "url": "numen-common-1.20.2-0.1.4.1.jar",
          "size": 1160632,
          "sha512": "7b59c648e5536cf1c0b60a51c60f231c3fe55332121ab8bb964e9e60e14c9cfea10eb113c2182a62cc0c8e2d8512e19a5d5b48487c875cd5bad4dc49e417ec12",
          "sha256": "47088ed691817056d7fe62cbd8074266f620d1d2d00655c0d4d60f5f4e63ec9d",
          "sha1": "0d04b71378b19f868941eb6b4f38e3b49b975281",
          "md5": "db8ff44fcf7f2853d364becccb5ce1df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.4.1.jar",
          "url": "numen-common-1.20.2-0.1.4.1.jar",
          "size": 1160632,
          "sha512": "7b59c648e5536cf1c0b60a51c60f231c3fe55332121ab8bb964e9e60e14c9cfea10eb113c2182a62cc0c8e2d8512e19a5d5b48487c875cd5bad4dc49e417ec12",
          "sha256": "47088ed691817056d7fe62cbd8074266f620d1d2d00655c0d4d60f5f4e63ec9d",
          "sha1": "0d04b71378b19f868941eb6b4f38e3b49b975281",
          "md5": "db8ff44fcf7f2853d364becccb5ce1df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.4.1-sources.jar",
          "url": "numen-common-1.20.2-0.1.4.1-sources.jar",
          "size": 875263,
          "sha512": "8a18dfe84681685262bd3f1a9cfb38849e77646164eb0a77aff2505f27b05517cb216c66aee60dae58eba07d4bd545cd61b9b89fba68ea63b5c442f2667e69c4",
          "sha256": "18cc0860870ee54fd68cfaeb82f025a249f90862bfdf0ea64ead91eb64b43302",
          "sha1": "43155cd68166fdf122c169eec8c34b8b1d0db604",
          "md5": "396b7d7e0e9fdc0ee5f0566d4eea5ea5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.2-0.1.4.1-javadoc.jar",
          "url": "numen-common-1.20.2-0.1.4.1-javadoc.jar",
          "size": 1533615,
          "sha512": "accc6c7c5aaf30a729aadff84cbef5bd0dd32c685eb1f9be2df731d85b31a5a6ad741e0b98a552eac048e910ace785fed7b81f7bd764267c7ff58056b9b38105",
          "sha256": "b5b8b28b9ae37712ceef00473e264f36bfa6017502d6aa108d0e4e038278ca0e",
          "sha1": "02e13ce7393656ea39f657486c5023f4c0c1ddbd",
          "md5": "a626d204d5bb7d78bbcd2ae20bd83bc1"
        }
      ]
    }
  ]
}
