{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.8",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2.jar",
          "url": "numen-neoforge-1.21.8-0.1.2.jar",
          "size": 2566549,
          "sha512": "92781b23415812bf57de342e2cae97b45c2187b6bbe3a08f990061785d743e19fe3ed57e032cc8cf99c682e6cbf372cad2e98af63b6d1f0a8a7aabf91fba4338",
          "sha256": "ae76a49987168bcdd198b99034486ad5db0752d0744e7bee211327ab8bbc3deb",
          "sha1": "7a898a254413ccd35256c82aa08529b3fbeab119",
          "md5": "be0be79c04a2671d179cc610cd62da01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2.jar",
          "url": "numen-neoforge-1.21.8-0.1.2.jar",
          "size": 2566549,
          "sha512": "92781b23415812bf57de342e2cae97b45c2187b6bbe3a08f990061785d743e19fe3ed57e032cc8cf99c682e6cbf372cad2e98af63b6d1f0a8a7aabf91fba4338",
          "sha256": "ae76a49987168bcdd198b99034486ad5db0752d0744e7bee211327ab8bbc3deb",
          "sha1": "7a898a254413ccd35256c82aa08529b3fbeab119",
          "md5": "be0be79c04a2671d179cc610cd62da01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.8-0.1.2-sources.jar",
          "size": 1074007,
          "sha512": "8577ca14a27706b872674e07b7df9eca53e15a8ae570c6d442278a5b7054e6d0780472fb62d185300e26e90a54e76d08d7bcc65ad4d914a58c96ddf0daf2fb62",
          "sha256": "5aad5f1139b8482020fcee5899a539d5145d89631247966026f85b1699dce41a",
          "sha1": "46593d26e84bffc33d26588486f83ca80418cb83",
          "md5": "33c1b8efccd1c104df8a74bb29c5f2e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.8-0.1.2-javadoc.jar",
          "size": 1540281,
          "sha512": "72edf3d0dd6c5532da8ada966cdf50b1ccd035d090dadce033747705f871f70f4ccaf25abeae325fef07e0c6071db56be563dd4c5ad78725943b715616bafeae",
          "sha256": "ccf39794fd42ebaf59a9be73e5124a418832389ee8c0535fe6e3bb450f4c3def",
          "sha1": "58d21dc4fbfe5b2fd0d26b2653eed076d8872450",
          "md5": "70883f90a814c8d70f0cf1a6048bb77e"
        }
      ]
    }
  ]
}
