{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.8",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2.jar",
          "url": "numen-neoforge-1.21.8-0.1.2.jar",
          "size": 2566550,
          "sha512": "82eb509e35745d755b3a8177a524c6dc436ef669004f0ec3109c8abd8a3f3a46d1c89a76de8a8fac86f6b3a890133bfac965cd0f9758b74a48ef9dc10932cb71",
          "sha256": "dde709fde200926e127f2edbc45a0910c342a8d85ff533c4669bfdd2131a2d8a",
          "sha1": "6d5c86294c05d0bad6829efe9a18687cf6436350",
          "md5": "f418a8d78a9a15c0cf16811f68ced752"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.8",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2.jar",
          "url": "numen-neoforge-1.21.8-0.1.2.jar",
          "size": 2566550,
          "sha512": "82eb509e35745d755b3a8177a524c6dc436ef669004f0ec3109c8abd8a3f3a46d1c89a76de8a8fac86f6b3a890133bfac965cd0f9758b74a48ef9dc10932cb71",
          "sha256": "dde709fde200926e127f2edbc45a0910c342a8d85ff533c4669bfdd2131a2d8a",
          "sha1": "6d5c86294c05d0bad6829efe9a18687cf6436350",
          "md5": "f418a8d78a9a15c0cf16811f68ced752"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.8-0.1.2-sources.jar",
          "size": 1074008,
          "sha512": "c32ab6ab0c3ea23ba7c2795c260fd7f07ee88c9c82a445331517faf9afdf92450d97074d5345d52c3b3e18ff84a5e2a254df05f1932a7487df5d25f9335bdb31",
          "sha256": "d7e27f44a00ea170b33c2d13a3c4c9ecf9d95bebf98f9d7e7ce54ed3db20d8cc",
          "sha1": "9e49592454cb1d4630701a58aa22e96959b89ad3",
          "md5": "9818d1708d9802a35788917dbdad3a30"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.8-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.8-0.1.2-javadoc.jar",
          "size": 1540281,
          "sha512": "72edf3d0dd6c5532da8ada966cdf50b1ccd035d090dadce033747705f871f70f4ccaf25abeae325fef07e0c6071db56be563dd4c5ad78725943b715616bafeae",
          "sha256": "ccf39794fd42ebaf59a9be73e5124a418832389ee8c0535fe6e3bb450f4c3def",
          "sha1": "58d21dc4fbfe5b2fd0d26b2653eed076d8872450",
          "md5": "70883f90a814c8d70f0cf1a6048bb77e"
        }
      ]
    }
  ]
}
