{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT.jar",
          "size": 545194,
          "sha512": "e87fb6076aca27997ee2dcc934f00cdadde2411bb77f5e26d4fd8de42262b84aa0f3d6f050a94dba71f1df65de24b50c3858339f8dda983cd76f9bb57eaecbd5",
          "sha256": "f605dc8403f41be664820ff63229f0a48960e58be4f545e4e75e1450408e68f7",
          "sha1": "128923579f25d658aa3dbb8392d1be2a371453b9",
          "md5": "13c5f0ce6de31425500a1175f2151f70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT.jar",
          "size": 545194,
          "sha512": "e87fb6076aca27997ee2dcc934f00cdadde2411bb77f5e26d4fd8de42262b84aa0f3d6f050a94dba71f1df65de24b50c3858339f8dda983cd76f9bb57eaecbd5",
          "sha256": "f605dc8403f41be664820ff63229f0a48960e58be4f545e4e75e1450408e68f7",
          "sha1": "128923579f25d658aa3dbb8392d1be2a371453b9",
          "md5": "13c5f0ce6de31425500a1175f2151f70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT-sources.jar",
          "size": 480563,
          "sha512": "5ad4ec60967a18cc853dd464e868d2743ca91e5c068085bd8144c1265a34f8d383f1002d07e3826b39007a6a135fe995cf4c74fdbaa289f0811b8a17cfe59220",
          "sha256": "e6b8605ad785acf5060e59c0b1b48c887bf50d4a5304447dfcb7d84d21117555",
          "sha1": "f998ad841c661a4821e0bdbf6c9c48907ead901d",
          "md5": "9546e6c1fab3df4a4fd06c8e47e7d048"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.0.1-SNAPSHOT-javadoc.jar",
          "size": 669420,
          "sha512": "db6fd0c8302272fc12d4b83fa71a7727d7fb2c515594319e90b6d77dc21d4277ce389d08732d9b30a541afd542a1645ef7d2bc26b189f973a22cbd0d610a1ff8",
          "sha256": "8ef03dd8a38b1382e1fa33ce2417f46dcf0f58cfa15502ef0194d9fd92dbe23e",
          "sha1": "bad466e24150cfb1b0cbb63952a70b1ca9c1dada",
          "md5": "f7c1338afaf7456c67d294cd308a51f8"
        }
      ]
    }
  ]
}
