{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.9.jar",
          "url": "numen-api-fabric-1.21.1-0.0.9.jar",
          "size": 1336327,
          "sha512": "c18cd20a173eff9d4f43cabe1cf93c60a44f0c4fcce5ad85a9910021fef5ae0cea364fa66e2fcef619409cc84e35d452ef65405a9af816c21a30a0958872b278",
          "sha256": "edd3012757871780c16751c7c984b787ef76f000586416301a747964143e85fe",
          "sha1": "955dc9c36a7c16d337ea778e4afd20c5688d4e95",
          "md5": "c61f43d526db93ff0ab19e1e6cbc50aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.9.jar",
          "url": "numen-api-fabric-1.21.1-0.0.9.jar",
          "size": 1336327,
          "sha512": "c18cd20a173eff9d4f43cabe1cf93c60a44f0c4fcce5ad85a9910021fef5ae0cea364fa66e2fcef619409cc84e35d452ef65405a9af816c21a30a0958872b278",
          "sha256": "edd3012757871780c16751c7c984b787ef76f000586416301a747964143e85fe",
          "sha1": "955dc9c36a7c16d337ea778e4afd20c5688d4e95",
          "md5": "c61f43d526db93ff0ab19e1e6cbc50aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.9-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.9-sources.jar",
          "size": 1069835,
          "sha512": "b60cc708284380910f007ae2ad1f1e8ab9f90f2ef539c639d0ad522a3a0cf2fda9473092ecbd25f580d5420f0d411ae842f265c4b398adb384e837df398fe286",
          "sha256": "13e653ec599bef5076a30e3c5e776cbef03cdc6f375f048d94c43b100d27ecfd",
          "sha1": "995c73e7249cda9fcb12559ea386925792f01249",
          "md5": "85a29d69322904f9a1eaee6b2eee6848"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.9-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.9-javadoc.jar",
          "size": 1567132,
          "sha512": "c9485f93096b3df7d542a08a26b28bced7094fd7767b0ddcb2bcae214306f39263d5bf4009c72b41b78404f517082bcf14b3a0d4b76eae336cfb93229c3ce9d1",
          "sha256": "a49617647b9808924b2bc9cdf46628b9e439855b0b6f0e0420d220f44486705b",
          "sha1": "4dce37ceac528bed19525aefe1defc85c2415b10",
          "md5": "7e32d45d015d7d063f248ee434745281"
        }
      ]
    }
  ]
}
