{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.10",
    "version": "0.0.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT.jar",
          "size": 913358,
          "sha512": "5a5622b0761bb0f1d1bd5879372d570df8563f36ae218fc5d492e5a2399f5d9e1a7b745aa89c197a45d7fdbc9350a1a9350058128ba47698ebedcebd2f78a849",
          "sha256": "6cb97c4f7dd0de4076205e72e39d5035aec2c688ce60f5f91fdda405e9e779c4",
          "sha1": "6035892b8e05aa7b32ea32cdb74329e843214ade",
          "md5": "7dd4347f5133802352e585a9b52ee3f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT.jar",
          "url": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT.jar",
          "size": 913358,
          "sha512": "5a5622b0761bb0f1d1bd5879372d570df8563f36ae218fc5d492e5a2399f5d9e1a7b745aa89c197a45d7fdbc9350a1a9350058128ba47698ebedcebd2f78a849",
          "sha256": "6cb97c4f7dd0de4076205e72e39d5035aec2c688ce60f5f91fdda405e9e779c4",
          "sha1": "6035892b8e05aa7b32ea32cdb74329e843214ade",
          "md5": "7dd4347f5133802352e585a9b52ee3f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT-sources.jar",
          "url": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT-sources.jar",
          "size": 728938,
          "sha512": "fec8dbda78e7cbc7053f164cc1a6d21aee2c61273e2c36560d1f1a3d22ed8350a71954ecb030dc6903c7142b8c60e57a6369857053f5838eb8c71375f1f69351",
          "sha256": "09667e923291157045460aeb23bb44241a6bbb02d65270761915a1b7390e42ef",
          "sha1": "d147c4a2b8dc7af3818992d10b68f87d98176385",
          "md5": "a22a7a9f1851dd56bc63e4b2c34bd5f1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT-javadoc.jar",
          "url": "numen-api-neoforge-1.21.10-0.0.7-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
