{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.4",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4.jar",
          "size": 2939907,
          "sha512": "183689ab47a186c13c4deeceb2863b80127834a745b5da56b638d739e217ab0387862de665542f0fbbeff42b7e27de7ba7bf9a29649226181564eb5d8586aa72",
          "sha256": "2ce9cbd895dc1ea6e02c89f742bdaf3aa17b28dc15c9547e2af674c861e5e774",
          "sha1": "e3e33398902009f44da29baff352056294da0d88",
          "md5": "2f13c711efd2997a4f452e3d28db4944"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-agent-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-lua-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-pathing-1.20.4",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4.jar",
          "size": 2939907,
          "sha512": "183689ab47a186c13c4deeceb2863b80127834a745b5da56b638d739e217ab0387862de665542f0fbbeff42b7e27de7ba7bf9a29649226181564eb5d8586aa72",
          "sha256": "2ce9cbd895dc1ea6e02c89f742bdaf3aa17b28dc15c9547e2af674c861e5e774",
          "sha1": "e3e33398902009f44da29baff352056294da0d88",
          "md5": "2f13c711efd2997a4f452e3d28db4944"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4-sources.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4-sources.jar",
          "size": 2057906,
          "sha512": "2e6c680ea65d69a47e2ef16f748a8e498d682174a938bbe124530aa3fd0846cd2f3cf9c022f2c573672b474e9081b91a62992b2a1e91b005040061420f44ce21",
          "sha256": "79f1719f6b02b4cd403a750f7da64e52df32cfaf299be656eb959fb701673dd1",
          "sha1": "1274243fdc810359347d3b2988a593dbc680e5f0",
          "md5": "865bf68d68139b9ba28764c4a5b28237"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.4-javadoc.jar",
          "url": "numen-api-fabric-1.20.4-0.1.4-javadoc.jar",
          "size": 2482797,
          "sha512": "6f611102e0d5103dce50e17645933524e2a4e8cc50413881b57352b143451eb22a5d4335b4f0699e50dd4666ba6fc080fca99513cca683960ec7b2c5c4bbc052",
          "sha256": "d7e17bc9453b4477918397c7eeeb51562b3597aeaf8580cffc37f3967e00d34d",
          "sha1": "a68c5d88af3118319677704d39aef563f349c6a9",
          "md5": "5adeaac6fe581bbcd8f58ee07daeff93"
        }
      ]
    }
  ]
}
