{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.1",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "size": 553387,
          "sha512": "8451ed748d5afc1e9cacd0c45c394c8462f578b2a9039ce5da26036292e1fb1e4d789beec396f0f653417b1661ac0a4765c705665e75071380ca81aab741f0c6",
          "sha256": "5fefc98f72ccd5a0d51790a75b69068aa1b9e9d095b67c7d586e241be7dafd1e",
          "sha1": "200dcbc52e4c850000aafcb42ce343a427f7d1ca",
          "md5": "89efce42d133977651ef965ad012335d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "size": 553387,
          "sha512": "8451ed748d5afc1e9cacd0c45c394c8462f578b2a9039ce5da26036292e1fb1e4d789beec396f0f653417b1661ac0a4765c705665e75071380ca81aab741f0c6",
          "sha256": "5fefc98f72ccd5a0d51790a75b69068aa1b9e9d095b67c7d586e241be7dafd1e",
          "sha1": "200dcbc52e4c850000aafcb42ce343a427f7d1ca",
          "md5": "89efce42d133977651ef965ad012335d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2-sources.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2-sources.jar",
          "size": 470776,
          "sha512": "b73f670086f687f5959c7e395a07d74d2c99600ea7eb1182e269b5909aa6fba177f5dff09ea90702cbec303ab42585e98230f0d9b00c8c092da37728f8872484",
          "sha256": "313c5583ee4f75302a55bff3ebfd42524b46abc5e46679413cce807bdf53688a",
          "sha1": "bb7fa73dddd684a7c460c60831c8c7374c65d917",
          "md5": "c6d47edd095af43a70cc37bb0f24ef5e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2-javadoc.jar",
          "size": 699957,
          "sha512": "fdf507d689c74e83e54c937a70d89a08fbf97759160cd044db5672adb7d4c2452f91163d45cc077e581c800a4d53bc32b2e2e31033955905512d5a4cc13bff28",
          "sha256": "7adec3813c27330b36ee93e63f1b752fb4102f12444da92ba16d7673b3468269",
          "sha1": "83665ac8541f5f1468304793b80d0afa86ac76ee",
          "md5": "62df44dab96d6d3a3a7f952315c26629"
        }
      ]
    }
  ]
}
