{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.1",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "size": 585415,
          "sha512": "f97bcfa91cd245442b4e04d5396920bb63cb80c69a98d779c46175b210738315b4fe8ed6faeafe1f234fa123e579fd2163577727fe43bb8917bef0a688075eb7",
          "sha256": "56e203317ed1742325331ef86e77df46e3dbd8c3104099846480076a81c71e8a",
          "sha1": "9b328829c4d999afb7cc394391e2df1f9acc0aee",
          "md5": "e4ee23915e42d13d517f3bca238df306"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2.jar",
          "size": 585415,
          "sha512": "f97bcfa91cd245442b4e04d5396920bb63cb80c69a98d779c46175b210738315b4fe8ed6faeafe1f234fa123e579fd2163577727fe43bb8917bef0a688075eb7",
          "sha256": "56e203317ed1742325331ef86e77df46e3dbd8c3104099846480076a81c71e8a",
          "sha1": "9b328829c4d999afb7cc394391e2df1f9acc0aee",
          "md5": "e4ee23915e42d13d517f3bca238df306"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2-sources.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2-sources.jar",
          "size": 490837,
          "sha512": "282e8c03ebbb878c8a0e24a0939c4689ec6ec7315061b869c227e12b1d10601078f6119af5732606a2b2769c06a54323fdc925074fdbd7f45d404d425eb0b956",
          "sha256": "c8254316ff021d973342339667809c302fd9422577326319409204f99f17f34c",
          "sha1": "35ea4ed95e0443925c343232661fa7fb5cc122fd",
          "md5": "fe070338d28c84ca64e7d237c8394f1d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.1-0.0.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.1-0.0.2-javadoc.jar",
          "size": 759907,
          "sha512": "759ba4ecf5b3081e4c593e5ceb61d496cce2033f83736160fd6a104034eff7b29a86365ee38913b0446277e231cdf90087fbbdc365c421e8526af88556fcec8f",
          "sha256": "edf8ae5053e6ece801b193560245495c61ea21bda58ff7d25d5e5c6d1beced29",
          "sha1": "3c06b6010233089760f1bef4e68691fe9dd6a3ba",
          "md5": "0d3f0d949cdbf687cb53cfcebffc4c34"
        }
      ]
    }
  ]
}
