{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.0.10.jar",
          "url": "numen-api-neoforge-1.21-0.0.10.jar",
          "size": 1323386,
          "sha512": "680487a3739d7ab13dbe43a3ba89d5758753ab2fbb6f899ed5579571b35b96d2ad41149edad13b932afa8a26774031aed8fa405ac3359beb0c121fcebcaf2e13",
          "sha256": "f1c8ac45ec3becdb0f6a88da55bc647184bea2f3905bd2a19e6fce1bf5e8a743",
          "sha1": "4582c17f514b2719c09762eb304f02c5ffa3ec33",
          "md5": "fc15fb55300cdfc6f84df22b0c64cf06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.0.10.jar",
          "url": "numen-api-neoforge-1.21-0.0.10.jar",
          "size": 1323386,
          "sha512": "680487a3739d7ab13dbe43a3ba89d5758753ab2fbb6f899ed5579571b35b96d2ad41149edad13b932afa8a26774031aed8fa405ac3359beb0c121fcebcaf2e13",
          "sha256": "f1c8ac45ec3becdb0f6a88da55bc647184bea2f3905bd2a19e6fce1bf5e8a743",
          "sha1": "4582c17f514b2719c09762eb304f02c5ffa3ec33",
          "md5": "fc15fb55300cdfc6f84df22b0c64cf06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.0.10-sources.jar",
          "url": "numen-api-neoforge-1.21-0.0.10-sources.jar",
          "size": 1054025,
          "sha512": "1d11f756b3bb01bf863232b57a732ac065e54f9f996721837af72c3cad511e14555fbb7a7e568b96c9b6687617c2781b5198f9d80afada69571cec72b11a2746",
          "sha256": "3de08d8e8ed7889590a18cfb877bdebd6060d3cf952cf7ab708a08c451301814",
          "sha1": "84901297d97d2725627995ffe84785e9563358d1",
          "md5": "999020063f182c3b53c79e7dc7e29dc9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21-0.0.10-javadoc.jar",
          "url": "numen-api-neoforge-1.21-0.0.10-javadoc.jar",
          "size": 1563579,
          "sha512": "1e154b24a50ef14312e0141cc0f68519b0bd86b5602f16d95c225bbf39e356e3ea2ce895fa9638e60375d95fdd05f0920c1e27ba9c9bcb2d40ecb5dcdfed772d",
          "sha256": "d4f6a8a73b4d11809c877eda3b6d3b6804675ae064a519c54836c6736c4eade1",
          "sha1": "1c238b1a6d01dcc77bef1b16acbb4b230914b32c",
          "md5": "a8b11c9b671dfd11e401b372bf8b164c"
        }
      ]
    }
  ]
}
