{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.11",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.11-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.11-0.1.2.jar",
          "size": 1326952,
          "sha512": "e116081815eb1eeb981489f42d8444beb8d0cb3307715ff884afbdc9e16427f911829daed00d75bf3e8f633a187c04f2beb68b7b73aea5c0b2c11fc84ce1118b",
          "sha256": "c7627deeb44cd45647e0bd434e3e30705edbb020c3889d6de353f4e47d9cb006",
          "sha1": "e2908c0dd7dea1d9331be42bb36f0d043cde085c",
          "md5": "b2cede0fad8b1e2ad7704dc4d6e9fe1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.11",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.11-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.11-0.1.2.jar",
          "size": 1326952,
          "sha512": "e116081815eb1eeb981489f42d8444beb8d0cb3307715ff884afbdc9e16427f911829daed00d75bf3e8f633a187c04f2beb68b7b73aea5c0b2c11fc84ce1118b",
          "sha256": "c7627deeb44cd45647e0bd434e3e30705edbb020c3889d6de353f4e47d9cb006",
          "sha1": "e2908c0dd7dea1d9331be42bb36f0d043cde085c",
          "md5": "b2cede0fad8b1e2ad7704dc4d6e9fe1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.11-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21.11-0.1.2-sources.jar",
          "size": 1059476,
          "sha512": "d125ffe6a36ebfaf3deb155658857f8612aceaf7c0b25c8475a6f86e15459e5e58492e038a513ead32fb9f3cdf573c84b1d3f3b049c3d3395087fddcea0f2a01",
          "sha256": "7ed096614b3c5efac1c8a5a2553fc1ab9204fb825211bf3032bd058ff3dd2331",
          "sha1": "ebb38ad721f9a140c1d7605f91a16e4600c4c133",
          "md5": "aa17331f87e0f53eb6c271fe9b07952f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.11-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.11-0.1.2-javadoc.jar",
          "size": 1567248,
          "sha512": "8bfab65d66e087e21229d56d212eddde0778c61cccaa0a8ef60f5d948730c9e01258753270a5eeb3e424dc435a91456db8bafadff75ebc4b32209c9dac57b65a",
          "sha256": "84814e872aaca095c13bfb70099c9471f6dc5ef4db16dfac30e189328069c67c",
          "sha1": "c4228eba7fb8659bbb2ee6ad9fdcc4c017484bcd",
          "md5": "35e889c73d14fc6b38f42f67e11c67bb"
        }
      ]
    }
  ]
}
