{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.1",
    "version": "0.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT.jar",
          "size": 553569,
          "sha512": "275af12d1e55fb21598f92d3aee1a41af6a9dd32b6303ee5ca5a7efca51a2af956d4a539e70b338c92e86a0ac8af730f22da62e4d0dabf9b5176ea9edf63adeb",
          "sha256": "f81afe251fce22a197b76b7a3b1a1114ec336b07b87804ddca00e6da6fb853bf",
          "sha1": "ca6171d69b9c547e29a042f5e6029d950fd8cb21",
          "md5": "d8fb1be6a3e527e69b383f53d80d62e9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT.jar",
          "size": 553569,
          "sha512": "275af12d1e55fb21598f92d3aee1a41af6a9dd32b6303ee5ca5a7efca51a2af956d4a539e70b338c92e86a0ac8af730f22da62e4d0dabf9b5176ea9edf63adeb",
          "sha256": "f81afe251fce22a197b76b7a3b1a1114ec336b07b87804ddca00e6da6fb853bf",
          "sha1": "ca6171d69b9c547e29a042f5e6029d950fd8cb21",
          "md5": "d8fb1be6a3e527e69b383f53d80d62e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT-sources.jar",
          "size": 489148,
          "sha512": "6782cc06f2129616c502399d268c266eb1670b5f87aefc009e3bd7aad30cd917c00f34cd8a6579f4ceb15ac827693b3ad1ec3abb25723b1a365bb9b1037ed9c0",
          "sha256": "7e98f63ed6e9c3e4f6203d42fb92a1893f7905dd2b667d9c9d087ac6f72abcb6",
          "sha1": "04f5ffe8c768d83888de62f066d10a16acc75193",
          "md5": "e076a7870b0a213fbb29613b8235abec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.20.1-0.0.2-SNAPSHOT-javadoc.jar",
          "size": 684040,
          "sha512": "035fc275d392635252975d352f8dcc8f4eefec1ad0c90282568f61cbc233d42b7c5e171c5a43525cc8af8c2257703c9db76439b14e6767d1348cfbd0cb1d2ba0",
          "sha256": "046ed533eb98771e751bcc52505ffe7e721779378416caa053789365eef87216",
          "sha1": "eebe864983246a4dcc0479a7a7dd75fd1fdea2a0",
          "md5": "6170172f6f3b2fe21809888614eca368"
        }
      ]
    }
  ]
}
