{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-neoforge-1.21.10",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.10-0.1.2.jar",
          "size": 1326441,
          "sha512": "6a3217112cc6b093c010e09c041caae13e108627a8ec041fb54a5fbdb0a5e3485f475cd1532b7bf58f923a04cacfd1e2c3493f750fd87807b340b731bae608de",
          "sha256": "1f73e396feeab9f0e8ca57c66d07d9a58af53b8c2d50dd60164e3c7709cd6108",
          "sha1": "3f92e79ae52086f8819917ed33d776e0351542bb",
          "md5": "3a85bbed1131774d5e552238758b5fad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21.10",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.1.2.jar",
          "url": "numen-api-neoforge-1.21.10-0.1.2.jar",
          "size": 1326441,
          "sha512": "6a3217112cc6b093c010e09c041caae13e108627a8ec041fb54a5fbdb0a5e3485f475cd1532b7bf58f923a04cacfd1e2c3493f750fd87807b340b731bae608de",
          "sha256": "1f73e396feeab9f0e8ca57c66d07d9a58af53b8c2d50dd60164e3c7709cd6108",
          "sha1": "3f92e79ae52086f8819917ed33d776e0351542bb",
          "md5": "3a85bbed1131774d5e552238758b5fad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.1.2-sources.jar",
          "url": "numen-api-neoforge-1.21.10-0.1.2-sources.jar",
          "size": 1058987,
          "sha512": "29c13c23daf7c86712d7d3c4443f44dbe38e26ecdabb9fa8e3d17b1bd1762f978f4bbe52e60bc8c6d065b70b4401a4c4b7a874894e6dd7d71e5980ed71f30186",
          "sha256": "717dde62bcb508b73fd162b829141982d5c511a1ae396f3536bc6925d13a5467",
          "sha1": "b521342153d6b6777feacc6c676c084f6b22be36",
          "md5": "28c5377a72ba99af073c616d0b07f4e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-neoforge-1.21.10-0.1.2-javadoc.jar",
          "url": "numen-api-neoforge-1.21.10-0.1.2-javadoc.jar",
          "size": 1567179,
          "sha512": "a8005b4e7aaf588352b75c81ab403540718041c7f8471651e9d539918d07b8c28a36458f0c546f245e300ffeeba16c38f07a505b61ae600628758963850ae8aa",
          "sha256": "fe35ce210ff3bb6512c2e244c31dd3d69d6d5c9cb4e05a0bc38574bbd588ccd4",
          "sha1": "44d8575be789768339bcd089264dbb915e0f7b50",
          "md5": "abf9eaff083585ee2c8a262a13b9163c"
        }
      ]
    }
  ]
}
