{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21.1",
    "version": "0.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT.jar",
          "size": 855014,
          "sha512": "ca023bab139d1a5e58ab57e7ae222c78e722c4d3056f5b4bb1135fa6ce907aceb8f8568d5b7f2d134eb452952e1c9593332267253578441e74182ed8006178f5",
          "sha256": "4811a33ea3da2fcb175cc2cb42598a908d98bbe7e454c99c53a68e508c71bf77",
          "sha1": "f99ecbb8405c68647e10c6e194e87fcf182f12eb",
          "md5": "43d5a7bb2962e6cf287153ad4f423342"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.116.7+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT.jar",
          "url": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT.jar",
          "size": 855014,
          "sha512": "ca023bab139d1a5e58ab57e7ae222c78e722c4d3056f5b4bb1135fa6ce907aceb8f8568d5b7f2d134eb452952e1c9593332267253578441e74182ed8006178f5",
          "sha256": "4811a33ea3da2fcb175cc2cb42598a908d98bbe7e454c99c53a68e508c71bf77",
          "sha1": "f99ecbb8405c68647e10c6e194e87fcf182f12eb",
          "md5": "43d5a7bb2962e6cf287153ad4f423342"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT-sources.jar",
          "url": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT-sources.jar",
          "size": 698749,
          "sha512": "277e53671f5c4f3b93e444737215a3141cba1e918d212abdcafbd8bfbdb429c8d62018ecbbd3af755bcc20a7533d6dcc6329460f3c541cd8d0abe62e4a05bd5d",
          "sha256": "cd15dc57d9726b07c2b214db855e0deadb45c090e18637b3d6fb583df30797b3",
          "sha1": "d190f916700f59427d61f25b289bc54d1420d295",
          "md5": "aec0de4537aa69d499dd763094c6f4a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT-javadoc.jar",
          "url": "numen-api-fabric-1.21.1-0.0.5-SNAPSHOT-javadoc.jar",
          "size": 1164990,
          "sha512": "99247493de057ffe65da61a65316e3d3fe2b91579307d20f78768a46f7cf5ad456d7c4834705d581bd160843cb24700f02c756a4cc4d6a36d3c91bc5aa99c009",
          "sha256": "10ce2a3724ec3299bfefe47a56bdde9c3188cf4a074bbbdd6edea46e72cb69e2",
          "sha1": "6d63f399e6d67df9f40d84fe3bae4bd80e60931d",
          "md5": "536ee8e84bfd7b0a2f8d2ee4606231cd"
        }
      ]
    }
  ]
}
