{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2.jar",
          "url": "numen-neoforge-1.21-0.1.2.jar",
          "size": 2553190,
          "sha512": "a9fe53bae930639c31679b391334e979144ae7adcdebfcc48a4a17dbd00de19437907759ccd8f2bb19f74232169fca86d555361cc02c3a77e455fe51e9cdefa5",
          "sha256": "38b287891f4c51cea5a3edfeb518621f36fe5726d5d690cd14329c76bb4336dd",
          "sha1": "fc3b8da58fc3c3224a1a04cc0fcd3b21ad81f870",
          "md5": "358724958c86973ee2ee249210ef2aaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21",
          "version": {
            "requires": "0.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2.jar",
          "url": "numen-neoforge-1.21-0.1.2.jar",
          "size": 2553190,
          "sha512": "a9fe53bae930639c31679b391334e979144ae7adcdebfcc48a4a17dbd00de19437907759ccd8f2bb19f74232169fca86d555361cc02c3a77e455fe51e9cdefa5",
          "sha256": "38b287891f4c51cea5a3edfeb518621f36fe5726d5d690cd14329c76bb4336dd",
          "sha1": "fc3b8da58fc3c3224a1a04cc0fcd3b21ad81f870",
          "md5": "358724958c86973ee2ee249210ef2aaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21-0.1.2-sources.jar",
          "size": 1064615,
          "sha512": "96b1bb245a4c0d2ad3abb4cc60445b058e058f47bf9282fb447bc3780dc7e21aaf321e9e83a9f1788dd43b45daddf8c117b2b91873831f84c6fc1d21e29970c3",
          "sha256": "ad46b5d7ce6ab43cbf59009fb3dd8c80dd48e730d4b6ccaf5ab41162e94f2cef",
          "sha1": "e594feeff80c5cd69f18d3d85631ac77c9a676c7",
          "md5": "b6be441f146707b25d179e6370cd6408"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21-0.1.2-javadoc.jar",
          "size": 1524634,
          "sha512": "2733785eaa1fb5187741a7812d5fd0850de14e9d35cd20f74ff48c258334b4b68375d1b9e605693c1531ca29b704a0834077573bacbfc6e562affa4d0a76f79e",
          "sha256": "620176c39e4a84e84783a352f124a074511b43df79cbed8fe1d08e1ee13ed9a7",
          "sha1": "ade75b93dfdce8a93d2e5afb71a99bc7fb6c426a",
          "md5": "fd07509de54a296f08d5c358f5094e3e"
        }
      ]
    }
  ]
}
