{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2.jar",
          "url": "numen-neoforge-1.21-0.1.2.jar",
          "size": 2553172,
          "sha512": "aa497f10454592f1d2096947438a498d89767d01b3525c7e49d246fc3b39e27e3ab2722da8bf68e6931d39f0d964335087678f2f4773a4df23f8cec912640e86",
          "sha256": "811ba70d38029b14bca80b1dcf83f60dab5114797d9834b8ed9dfda27902ec14",
          "sha1": "008eef4f125984f9b17802e333fd1b217a5df459",
          "md5": "d3ee1c7ddf2eb5f8ba3d16cf54f1de46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2.jar",
          "url": "numen-neoforge-1.21-0.1.2.jar",
          "size": 2553172,
          "sha512": "aa497f10454592f1d2096947438a498d89767d01b3525c7e49d246fc3b39e27e3ab2722da8bf68e6931d39f0d964335087678f2f4773a4df23f8cec912640e86",
          "sha256": "811ba70d38029b14bca80b1dcf83f60dab5114797d9834b8ed9dfda27902ec14",
          "sha1": "008eef4f125984f9b17802e333fd1b217a5df459",
          "md5": "d3ee1c7ddf2eb5f8ba3d16cf54f1de46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21-0.1.2-sources.jar",
          "size": 1064615,
          "sha512": "f0607c0aa3e8b7d9798636af3d97207933de639fb0191479f4558efcf4a329efa2b46a4df2a2e8663abe2e6866c87e19e614420b3fb0725f9d381de0d5e46ecd",
          "sha256": "0bace543e4ac83fab864716919de4da3612a44a47921f2734650f9ff20c1b00a",
          "sha1": "b546a012e96bcb3c4e34e66dd59efea6b345fdf2",
          "md5": "6fd7278802ce1841843b04986b9024d8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21-0.1.2-javadoc.jar",
          "size": 1524634,
          "sha512": "2733785eaa1fb5187741a7812d5fd0850de14e9d35cd20f74ff48c258334b4b68375d1b9e605693c1531ca29b704a0834077573bacbfc6e562affa4d0a76f79e",
          "sha256": "620176c39e4a84e84783a352f124a074511b43df79cbed8fe1d08e1ee13ed9a7",
          "sha1": "ade75b93dfdce8a93d2e5afb71a99bc7fb6c426a",
          "md5": "fd07509de54a296f08d5c358f5094e3e"
        }
      ]
    }
  ]
}
