{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2.jar",
          "url": "numen-neoforge-1.21-0.1.2.jar",
          "size": 2553174,
          "sha512": "2ae59ef1ed3f2cd7a9ab641e932d2b80775bf3d63364c2012014ab4468084ddb315ea99c58f2a862d905d1cf40fd9c37770bb0b6b1ef037a15b78dad512734a6",
          "sha256": "f50fda7785231937521f91e33dfa45e0d3576eae010d0539f63f9a9e57af327a",
          "sha1": "2172ceeca031a60fcf75a104003788824941d468",
          "md5": "3544b0c4aa5418d65804240f0fb85db2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2.jar",
          "url": "numen-neoforge-1.21-0.1.2.jar",
          "size": 2553174,
          "sha512": "2ae59ef1ed3f2cd7a9ab641e932d2b80775bf3d63364c2012014ab4468084ddb315ea99c58f2a862d905d1cf40fd9c37770bb0b6b1ef037a15b78dad512734a6",
          "sha256": "f50fda7785231937521f91e33dfa45e0d3576eae010d0539f63f9a9e57af327a",
          "sha1": "2172ceeca031a60fcf75a104003788824941d468",
          "md5": "3544b0c4aa5418d65804240f0fb85db2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21-0.1.2-sources.jar",
          "size": 1064615,
          "sha512": "7961a0ab2d1028855eaa26fc1d661757eec9fed82e21baf948aebd208412c278d2f8d0eb9a94841cec06d248b4698571ab1d203a3a1316c1a20770c3307e61bc",
          "sha256": "5d3dfb7b83468a288425ce3d14cddf6266d07188cae241e3304304b0f93d3211",
          "sha1": "f865c31b0aadd2a3dd7fe5accb8d7d702b191ffa",
          "md5": "13e438d4b6b3fc2ba22d96970fa7f7cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21-0.1.2-javadoc.jar",
          "size": 1524634,
          "sha512": "2733785eaa1fb5187741a7812d5fd0850de14e9d35cd20f74ff48c258334b4b68375d1b9e605693c1531ca29b704a0834077573bacbfc6e562affa4d0a76f79e",
          "sha256": "620176c39e4a84e84783a352f124a074511b43df79cbed8fe1d08e1ee13ed9a7",
          "sha1": "ade75b93dfdce8a93d2e5afb71a99bc7fb6c426a",
          "md5": "fd07509de54a296f08d5c358f5094e3e"
        }
      ]
    }
  ]
}
