{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.6",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.3.jar",
          "url": "numen-api-fabric-1.20.6-0.1.3.jar",
          "size": 1353544,
          "sha512": "6716dc8b19c3a73caffc8443e0aa43b3cce260d4df4879c66f311f5e9e3197a965669dab1130ba9225e3919b691d8f40c8e41c108e55608d824b7727711d897b",
          "sha256": "402834a37627795bbebcb6ea8737ff7a50818264990d0df802ad54419b414a21",
          "sha1": "7091b88e40a24c2899a32c4f99beaf55123c184d",
          "md5": "1131831c5cebb17cf73bd72c386e9f87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.6",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.6",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.10"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.8+1.20.6"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.3.jar",
          "url": "numen-api-fabric-1.20.6-0.1.3.jar",
          "size": 1353544,
          "sha512": "6716dc8b19c3a73caffc8443e0aa43b3cce260d4df4879c66f311f5e9e3197a965669dab1130ba9225e3919b691d8f40c8e41c108e55608d824b7727711d897b",
          "sha256": "402834a37627795bbebcb6ea8737ff7a50818264990d0df802ad54419b414a21",
          "sha1": "7091b88e40a24c2899a32c4f99beaf55123c184d",
          "md5": "1131831c5cebb17cf73bd72c386e9f87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.3-sources.jar",
          "url": "numen-api-fabric-1.20.6-0.1.3-sources.jar",
          "size": 1093837,
          "sha512": "ee313445589a6ed5982aa2dc8de50b519558f3da83e1b4c15736def2376ad4dc30f52b9a25ac73cf41622250b77a7a102a78fbb9bbd90ef85a47521ed3629ed8",
          "sha256": "1dc58dbe159daf867831df08e7bf0b49592f0d7bf952f6cf74d9cc391f072a21",
          "sha1": "74413b1e746b561b24ccc92fee0928d37730866a",
          "md5": "b9e83182c6f23b49fe8bde9038179610"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.6-0.1.3-javadoc.jar",
          "url": "numen-api-fabric-1.20.6-0.1.3-javadoc.jar",
          "size": 1611725,
          "sha512": "ba0feccde993c23a98c77ae22853a17f40ecda5825d2416999953acf5e9eaf17d3e86b625082ffbf98ace7aa3e625eb9bf68d9ed519f95c3b0add74d89c0cd34",
          "sha256": "4af1b4d52850ee8c9c90e91381b3ea928ef5db8d89fd278c32e4b9c015ec3bd7",
          "sha1": "c168c9b15ac4e05f7e716bc679d3c15c7cba86ea",
          "md5": "0b776eb76fe7d3ee51f68a1240a90b73"
        }
      ]
    }
  ]
}
