{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-fabric-26.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-fabric-26.2-0.1.2.jar",
          "url": "numen-fabric-26.2-0.1.2.jar",
          "size": 2488840,
          "sha512": "536bbb0bd5d518dea12b5115a7ad2b16177ee4bfff174ffbcee0b89ea32214fe5853a11275c16c91f1491733a0f041a32351486da0c07c0e8622c00dab00e10f",
          "sha256": "ff15f98e019836c023ad8fb1b55c66861d1767ee56342bdf0ca01b924585d4b3",
          "sha1": "f15cb5e02460af34edf614e69e84184898b4ce5e",
          "md5": "c22d457f879b0c575ad37afe88be19c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.158.0+26.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-fabric-26.2",
          "version": {
            "requires": "0.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-fabric-26.2-0.1.2.jar",
          "url": "numen-fabric-26.2-0.1.2.jar",
          "size": 2488840,
          "sha512": "536bbb0bd5d518dea12b5115a7ad2b16177ee4bfff174ffbcee0b89ea32214fe5853a11275c16c91f1491733a0f041a32351486da0c07c0e8622c00dab00e10f",
          "sha256": "ff15f98e019836c023ad8fb1b55c66861d1767ee56342bdf0ca01b924585d4b3",
          "sha1": "f15cb5e02460af34edf614e69e84184898b4ce5e",
          "md5": "c22d457f879b0c575ad37afe88be19c3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-26.2-0.1.2-sources.jar",
          "url": "numen-fabric-26.2-0.1.2-sources.jar",
          "size": 1012371,
          "sha512": "b967d6036471bb4b9316a851d8d198a7a2ab7ed0fa567fd2a7611f8e236df3fb1beda450ed4adde890b4a9a384dc774fa91c826c3029a1514361bd3141c61ae8",
          "sha256": "eec15fcbb70c581b2aa84272aadf947baac9e4a1e2874588a1926af3d4ad2ea8",
          "sha1": "6b7321cd61fd5b328fd67f3c64d06657a3672b51",
          "md5": "3a7f8981ba5c2dd60ea899296140d1de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-fabric-26.2-0.1.2-javadoc.jar",
          "url": "numen-fabric-26.2-0.1.2-javadoc.jar",
          "size": 5606505,
          "sha512": "52e3b00f49d6bf881ad939ad7ec12758d0562eb549c2e89cdfff22aa5ace5da9e3614292fc487b3998254352dc73de5afc648034982e0766d9cd74e87e6a6dbc",
          "sha256": "0525476ef3144b09f7d4bb07e9fa860ada9c9928e122490cefff3b206cf813dc",
          "sha1": "ffbff2150d169923344e4bdbdca3f24618bbc93b",
          "md5": "c2b3fe74ec1b4a5c97039fb6e3a93afa"
        }
      ]
    }
  ]
}
