{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2.jar",
          "url": "numen-common-1.20.1-0.1.2.jar",
          "size": 1210659,
          "sha512": "6fc65857920b8c3200e7aae8ad5b7a5ae09a675c46d3bc18ce340bbe7954c6005c1ad67982ce00afe5f379a520c379d9955fa1f95c022d7fb142530129173aee",
          "sha256": "4ce8054993f11c1a07d95ba78f0bcadcef829742c0fc1e3988adc02a6a54ed9e",
          "sha1": "86f2692adabdbf78a126b90edf514ab5111d175e",
          "md5": "4da1d06e465dcbfa443b026a6b986a9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2.jar",
          "url": "numen-common-1.20.1-0.1.2.jar",
          "size": 1210659,
          "sha512": "6fc65857920b8c3200e7aae8ad5b7a5ae09a675c46d3bc18ce340bbe7954c6005c1ad67982ce00afe5f379a520c379d9955fa1f95c022d7fb142530129173aee",
          "sha256": "4ce8054993f11c1a07d95ba78f0bcadcef829742c0fc1e3988adc02a6a54ed9e",
          "sha1": "86f2692adabdbf78a126b90edf514ab5111d175e",
          "md5": "4da1d06e465dcbfa443b026a6b986a9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2-sources.jar",
          "url": "numen-common-1.20.1-0.1.2-sources.jar",
          "size": 1002946,
          "sha512": "ce2e2e05aa4e76aacdfbc746ceea70be07a02c9abd22e8a785376326d2b395ef36d05b72cad280b75a816e1cbe79437840e75aba90618678c604019d923a83e0",
          "sha256": "54e78ef17f6c269ca807b7b601f5453587b0a10a5ea4ce541b19466c98746af9",
          "sha1": "059b4e0a23c8cd0cbe7abb2fec4da4900da50ee5",
          "md5": "f988e60d09913dd71da3d7637701eb32"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-common-1.20.1-0.1.2-javadoc.jar",
          "size": 1428700,
          "sha512": "8ec415f92c58fbf9bbd94291546d160d2b2b843ef7b222e9125f73fe6dc10005495b4798ea5c92a27f097a757c0036532a3862778efc50aecc8b8026c406f2f0",
          "sha256": "3f51aa36f10250320a8c1deabad42448a623bd8bbcb5bc7a52291520d122f6f5",
          "sha1": "b38c2bb1348ab2e01b48c6ab4fdbab08d1f08a0e",
          "md5": "4cf0898839428ef8f5c80e35ceea9538"
        }
      ]
    }
  ]
}
