{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-common-1.20.1",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2.jar",
          "url": "numen-common-1.20.1-0.1.2.jar",
          "size": 1210659,
          "sha512": "6b5e8258143409203b02f6fcb0f3c53f0e7003af77194814cbce181591ecdad50d804f78569f11df891c58ab2e5f6d95df61364c945966f2614657a26b87c512",
          "sha256": "afdc282852fdea753bc0ccbda7ac1427ca192953a8505977ca93ea7fae6cb590",
          "sha1": "53a7e717c5041ce4a6ae30762c84e05edfc02525",
          "md5": "a83b2f4c1f7e9ebf32df99c9372be06c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2.jar",
          "url": "numen-common-1.20.1-0.1.2.jar",
          "size": 1210659,
          "sha512": "6b5e8258143409203b02f6fcb0f3c53f0e7003af77194814cbce181591ecdad50d804f78569f11df891c58ab2e5f6d95df61364c945966f2614657a26b87c512",
          "sha256": "afdc282852fdea753bc0ccbda7ac1427ca192953a8505977ca93ea7fae6cb590",
          "sha1": "53a7e717c5041ce4a6ae30762c84e05edfc02525",
          "md5": "a83b2f4c1f7e9ebf32df99c9372be06c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2-sources.jar",
          "url": "numen-common-1.20.1-0.1.2-sources.jar",
          "size": 1002946,
          "sha512": "8ff583ae088b901908647fdd0fe753f4196548fd197e9d54e2218fdf53ed6f8d5f4c7852752e961a0c65f3786ab8558566f887226ef73f47a15ca07544d1e3b3",
          "sha256": "e41e8f14ca172fa9463b587ef7322de9c44000ab120e6ca9ffd32b1bd9b5522b",
          "sha1": "7bae50d339ab07378289fa61da58cf856c831c67",
          "md5": "6b288309b41a25916f093abfda9c2fdb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "common",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-common-1.20.1-0.1.2-javadoc.jar",
          "url": "numen-common-1.20.1-0.1.2-javadoc.jar",
          "size": 1428700,
          "sha512": "95ab1e9f9de3876eb5f6edf7fbb6355a30f67203f6d70c0f5f08e5ebd0e23bf15e3228749a37ea4c6018e030d1ee4ef4b9f3c6799a1f184d21e32d20649f5bf2",
          "sha256": "1290a7ffe6fa421a83f82adff365fc8e0ca3bb8e7940ca2bf05fcaa01db9cbfc",
          "sha1": "35b071986ab76edaf5fa408d7e4f5e92c57d79df",
          "md5": "9951bb0d676ee7657bc80092fa6ecd37"
        }
      ]
    }
  ]
}
