{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.10",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.10",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.3.jar",
          "url": "numen-neoforge-1.21.10-0.1.3.jar",
          "size": 2597695,
          "sha512": "d6362eb4ed19a6466faeb9328fc15cf2496ab59ef478890f0ffda3fc4f2b21ce42445b6e7bda9478631ece492e6119db9a1d1cf208b16bc93bd6ec07ac9d3eae",
          "sha256": "5c28ceb8493e0877f648cd9047514bace3775de72db414d14bd4cfc7e3481403",
          "sha1": "232d845ff3d20e680a3f240fd6e1409a7dcc1e88",
          "md5": "22842ab3eb8006ec561679dba69d8f0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.10",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.3.jar",
          "url": "numen-neoforge-1.21.10-0.1.3.jar",
          "size": 2597695,
          "sha512": "d6362eb4ed19a6466faeb9328fc15cf2496ab59ef478890f0ffda3fc4f2b21ce42445b6e7bda9478631ece492e6119db9a1d1cf208b16bc93bd6ec07ac9d3eae",
          "sha256": "5c28ceb8493e0877f648cd9047514bace3775de72db414d14bd4cfc7e3481403",
          "sha1": "232d845ff3d20e680a3f240fd6e1409a7dcc1e88",
          "md5": "22842ab3eb8006ec561679dba69d8f0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.3-sources.jar",
          "url": "numen-neoforge-1.21.10-0.1.3-sources.jar",
          "size": 1074320,
          "sha512": "51aefe70ab33c4c8f6fe14ae82f889c908e021293b46a216060be63ccedc688b2801844327e7369dae2f78538eced30d7406a5e07a37133ad1c50729a1f0f196",
          "sha256": "3ad8df9c5d639cb3444b9efe398bc4b14de48ed009249a22fab05c01839b31c6",
          "sha1": "ba9e47525edf822abdc303f90841a28b0e8d39c1",
          "md5": "6c99ff42a95826601947dd4d31992c25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.10-0.1.3-javadoc.jar",
          "url": "numen-neoforge-1.21.10-0.1.3-javadoc.jar",
          "size": 1540132,
          "sha512": "2592376d694c15e08026ceab7bdc5a88a5b3531dac01ea33632684c0689dd9466686c826438ff79625bbe8c2563f02d8a08e10355dd072b64c7b9c45626c674b",
          "sha256": "91f49235a175ee18891586ccdf8dcaba193bdc770c2fff4882658aa5dc1c2fae",
          "sha1": "ee64c1679304c6ff61282b18eff1a346b3a23a4c",
          "md5": "085c5968b67862ffb4d9178ec2eabcaf"
        }
      ]
    }
  ]
}
