{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-ai-26.1.2",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-26.1.2-0.1.2.jar",
          "url": "numen-ai-26.1.2-0.1.2.jar",
          "size": 77497,
          "sha512": "fba5538ec475b91978c4485f5e8ddaf49c977217e3fa251afac54e735d8dfb0491f0e2203e7ba3fd79692a48f09a261d7f92af504a1552d1edf33b355fa495a6",
          "sha256": "1d2cb2b0ea4573d7c17d4afcb229dd2907ce41ba1e754845f8a1934a317fac81",
          "sha1": "65de023ae12c36f2344e25f60a2d522c26e3323b",
          "md5": "6299409407d81e76966f53a13c78fe9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.13.2"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "numen-ai-26.1.2-0.1.2.jar",
          "url": "numen-ai-26.1.2-0.1.2.jar",
          "size": 77497,
          "sha512": "fba5538ec475b91978c4485f5e8ddaf49c977217e3fa251afac54e735d8dfb0491f0e2203e7ba3fd79692a48f09a261d7f92af504a1552d1edf33b355fa495a6",
          "sha256": "1d2cb2b0ea4573d7c17d4afcb229dd2907ce41ba1e754845f8a1934a317fac81",
          "sha1": "65de023ae12c36f2344e25f60a2d522c26e3323b",
          "md5": "6299409407d81e76966f53a13c78fe9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-26.1.2-0.1.2-sources.jar",
          "url": "numen-ai-26.1.2-0.1.2-sources.jar",
          "size": 62044,
          "sha512": "e7d3c5f82877a7b94e60c7a8e3b78f4074fc48393e55790198ea0bdf73434041374b1d3edc884462369da8ea09d504254b2145a80aac1fbcb10a3bfd448b0364",
          "sha256": "5f4bca31de27776ce0e3d17bb1d8e096b9a8d5e5cb54715498c03cec434a24ce",
          "sha1": "0dd78e4a49d7cc422a5591cd09d65e803dd78faf",
          "md5": "f9681ff56e1ddcf4cbad439cc734211a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-ai-26.1.2-0.1.2-javadoc.jar",
          "url": "numen-ai-26.1.2-0.1.2-javadoc.jar",
          "size": 4322972,
          "sha512": "504d1b56724baef846df0e0a2b8cdf9e3cd4a05e5fc3d11b2c8b6c20e26bd7440765e737b86556d7817f8c97e2da95baa56cda7be9d6ee353bd927aaedf69003",
          "sha256": "40f057af9ae32c4ec9d9bc769400864568e63013867e4d8571eaca2b38de82ed",
          "sha1": "2d2fbeb75b8d27e89d7567ab0183bcbd0a53f6c0",
          "md5": "ef0906142dde511801ec6a1c642ab082"
        }
      ]
    }
  ]
}
