{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.5",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-neoforge-1.21.5-0.1.2.jar",
          "size": 2563923,
          "sha512": "2f5bce901583955d00c31b13315b5fabf959ac1eab5bd8d486390ca29d74407cc24ff3e995f11df3df3a8f9de7586f908f4cdfd312e48cf7e0ea319b850ea2ca",
          "sha256": "127617f15956f15a269954568f16ae01fb35f8d42acda169141f30ca9d5a1fa8",
          "sha1": "d2dddfa131a697553d62e8576851c44f6d22cd35",
          "md5": "1009d4f93d8f5f413723cf44dfa375fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-neoforge-1.21.5-0.1.2.jar",
          "size": 2563923,
          "sha512": "2f5bce901583955d00c31b13315b5fabf959ac1eab5bd8d486390ca29d74407cc24ff3e995f11df3df3a8f9de7586f908f4cdfd312e48cf7e0ea319b850ea2ca",
          "sha256": "127617f15956f15a269954568f16ae01fb35f8d42acda169141f30ca9d5a1fa8",
          "sha1": "d2dddfa131a697553d62e8576851c44f6d22cd35",
          "md5": "1009d4f93d8f5f413723cf44dfa375fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.5-0.1.2-sources.jar",
          "size": 1073109,
          "sha512": "f573fdf663e097d403077531d35047af55e9c54bb85ff7ad66b1549342de65c686b9ef340454435c04d32bc0d2163dcbca82872a3d2bb18f9042e78824afdeae",
          "sha256": "4dce007099c8d491dbeacb2ac0e8ac16878309d54ce0fcd12d04b4455155c629",
          "sha1": "9725ce242193fb0352ea7064cb40bfade678077a",
          "md5": "e45dcce11cd6114c1f1c20dd0bcbcad9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.5-0.1.2-javadoc.jar",
          "size": 1540351,
          "sha512": "9fabe05cf72b77bdd463ae5931109afea76fa156ec896f9fa2549b82a2d1b5a6c1db54b810b1fc3112dd1fddf17f0dfdddcf95e1269a82f533343a3969192b6b",
          "sha256": "098b03d653608ddd2b5b08841722a35d5eec7551500c75b770c8d2220d89da66",
          "sha1": "c172fb3003ca010b63bc100334a65a0cafe89ddf",
          "md5": "ac90df66f6cb2c9e9901f02038560570"
        }
      ]
    }
  ]
}
