{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.5",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-neoforge-1.21.5-0.1.2.jar",
          "size": 2563934,
          "sha512": "0b30c467edbef7975b6d7a306ecd7ecb34344b860279a2a180b47ace44ff037e7596f807e4c12aacf7f455800bcada3b0611d10331091a2206342ffde5462d58",
          "sha256": "4ae10fbeeb4421a6812f9af689780cffb9123a07235736b7dca40de10472e7c7",
          "sha1": "ddbe1b6dcbf5510c99151d47d598044ca292b94f",
          "md5": "4c26ddb0fc628d6042aee933d9e598f3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.5",
          "version": {
            "requires": "0.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-neoforge-1.21.5-0.1.2.jar",
          "size": 2563934,
          "sha512": "0b30c467edbef7975b6d7a306ecd7ecb34344b860279a2a180b47ace44ff037e7596f807e4c12aacf7f455800bcada3b0611d10331091a2206342ffde5462d58",
          "sha256": "4ae10fbeeb4421a6812f9af689780cffb9123a07235736b7dca40de10472e7c7",
          "sha1": "ddbe1b6dcbf5510c99151d47d598044ca292b94f",
          "md5": "4c26ddb0fc628d6042aee933d9e598f3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.5-0.1.2-sources.jar",
          "size": 1073108,
          "sha512": "a905e180576e7d342d89705cb7fed77339ea5fd1f00b462ebe1fffcab8142eecc757c4d15b2e3b49f27149db783b5a182b851dc23f73e605ffd9ec728d97c289",
          "sha256": "6ffb100faf4e20ff8cade6ca230db5772afbd7fc1f545ba378e23b0256dedbc5",
          "sha1": "43b83260fb575f3612beba25909cc52d7f3e9e9e",
          "md5": "9e14958c0bd7cbe3f9fab36781213ae2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.5-0.1.2-javadoc.jar",
          "size": 1540351,
          "sha512": "9fabe05cf72b77bdd463ae5931109afea76fa156ec896f9fa2549b82a2d1b5a6c1db54b810b1fc3112dd1fddf17f0dfdddcf95e1269a82f533343a3969192b6b",
          "sha256": "098b03d653608ddd2b5b08841722a35d5eec7551500c75b770c8d2220d89da66",
          "sha1": "c172fb3003ca010b63bc100334a65a0cafe89ddf",
          "md5": "ac90df66f6cb2c9e9901f02038560570"
        }
      ]
    }
  ]
}
