{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.5",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-neoforge-1.21.5-0.1.2.jar",
          "size": 2563925,
          "sha512": "7391ddbae2e6ca6395382bdf09ba68f58935ce15cf06c6dfa2805bc4ffb9b1f02ccb9bec403813aafc6d941a58dbca65b84f4ce3798bb3aaa89188dd05c2c137",
          "sha256": "eaee95343e3e031b6571cc667e880147291714ffe531275846aa6b73ca680550",
          "sha1": "e5d5def8fadd4adcdf3c091bef19334e89e236f2",
          "md5": "652909197ff4b608fbcc69a7226e0624"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.5",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2.jar",
          "url": "numen-neoforge-1.21.5-0.1.2.jar",
          "size": 2563925,
          "sha512": "7391ddbae2e6ca6395382bdf09ba68f58935ce15cf06c6dfa2805bc4ffb9b1f02ccb9bec403813aafc6d941a58dbca65b84f4ce3798bb3aaa89188dd05c2c137",
          "sha256": "eaee95343e3e031b6571cc667e880147291714ffe531275846aa6b73ca680550",
          "sha1": "e5d5def8fadd4adcdf3c091bef19334e89e236f2",
          "md5": "652909197ff4b608fbcc69a7226e0624"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2-sources.jar",
          "url": "numen-neoforge-1.21.5-0.1.2-sources.jar",
          "size": 1073109,
          "sha512": "718fb649f077a28bb1042783da7831791187d9d839b91927bcea78198d242f54b4a6d995fdb9916777596c6ca32d22cb5b9db83524543c1a5a31ed8df6456ad8",
          "sha256": "bc296b6ebaec1e5e05c08c1c3a65ea4c54885d95220bc9d24622b870494b6a93",
          "sha1": "8b616f88f80d1ad5c27fc942b61673456917e965",
          "md5": "dc521e1666c8e2a37fe47e995f0e566b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.5-0.1.2-javadoc.jar",
          "url": "numen-neoforge-1.21.5-0.1.2-javadoc.jar",
          "size": 1540351,
          "sha512": "9fabe05cf72b77bdd463ae5931109afea76fa156ec896f9fa2549b82a2d1b5a6c1db54b810b1fc3112dd1fddf17f0dfdddcf95e1269a82f533343a3969192b6b",
          "sha256": "098b03d653608ddd2b5b08841722a35d5eec7551500c75b770c8d2220d89da66",
          "sha1": "c172fb3003ca010b63bc100334a65a0cafe89ddf",
          "md5": "ac90df66f6cb2c9e9901f02038560570"
        }
      ]
    }
  ]
}
