{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.21",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.1.2.jar",
          "url": "numen-api-fabric-1.21-0.1.2.jar",
          "size": 1320007,
          "sha512": "5061a92a4c3fe643d3abef3ca58d8711421c60f989b4c6d972e7dc181249d5089642184fefc5bf40d9f1f7fe34da7b00ff88151f8a27f78047ac7bf4700d3f2e",
          "sha256": "286729f16d6866d81be7a11f5e8f560b9ef5ef484e301b5e34547a6edc95427a",
          "sha1": "2cfdc0fd01357ce59cb6d587e8c2f6d4a7b4aab7",
          "md5": "46d466b13d73bfdb8547d09de343cd25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.21",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.18.1"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.102.0+1.21"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.1.2.jar",
          "url": "numen-api-fabric-1.21-0.1.2.jar",
          "size": 1320007,
          "sha512": "5061a92a4c3fe643d3abef3ca58d8711421c60f989b4c6d972e7dc181249d5089642184fefc5bf40d9f1f7fe34da7b00ff88151f8a27f78047ac7bf4700d3f2e",
          "sha256": "286729f16d6866d81be7a11f5e8f560b9ef5ef484e301b5e34547a6edc95427a",
          "sha1": "2cfdc0fd01357ce59cb6d587e8c2f6d4a7b4aab7",
          "md5": "46d466b13d73bfdb8547d09de343cd25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.1.2-sources.jar",
          "url": "numen-api-fabric-1.21-0.1.2-sources.jar",
          "size": 1058399,
          "sha512": "0554c1f1be8a1b0cce8d5ef04edf6bc3b9da268c418dd78c37ab6ffab7df01751e0fd6846abb79f9e191b79c7e92f2ebdbeb840b76381ca45ecba557007f4d74",
          "sha256": "8f25c505b422c17d9042e25eb223f3c2b1a1c9484fc70807ae4f822d4a691268",
          "sha1": "0c26a9cc559e4dd5ecabddc1ad2fba4fae01e5fc",
          "md5": "12f98b5cce5d515986973d9983f0fa8d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.21-0.1.2-javadoc.jar",
          "url": "numen-api-fabric-1.21-0.1.2-javadoc.jar",
          "size": 1565460,
          "sha512": "7dc5077587fb1715fb3b27ea4317706d2fe82b46ffbde66e1c001b7180bf3943f172efa768c5b1e615fdcb938bd726a39a0c31c7ac4dbad628e351e3723551cc",
          "sha256": "a7c420921b040b9c532aac180059745e7b65029cb73b6979e4df7d63c6ed9da3",
          "sha1": "103577692f5675b80c8020c3338438cabbba2ef0",
          "md5": "45f3ac21e540af919842c1d494ec8a87"
        }
      ]
    }
  ]
}
