{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-api-fabric-1.20.4",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.2.jar",
          "url": "numen-api-fabric-1.20.4-0.1.2.jar",
          "size": 1318542,
          "sha512": "88aafb9cef17c56a7b524f2082debd6870c6f9b0b6f437bb69f9de847e68847f563739b50c6577468e13182245bd228afeaa102408b71bbcd5520394445e6fa7",
          "sha256": "2fd5f9d7a5446f1c9125030c01f66e04716de2b258b4cbdd49dc114fcc41b197",
          "sha1": "4274e5ab93efe6d97eeb267ed3f040fcc4297f7d",
          "md5": "6aeec8135556768aa38509ddb348e91f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ai-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.dwinovo.numen",
          "module": "numen-ui-1.20.4",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.1+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.2.jar",
          "url": "numen-api-fabric-1.20.4-0.1.2.jar",
          "size": 1318542,
          "sha512": "88aafb9cef17c56a7b524f2082debd6870c6f9b0b6f437bb69f9de847e68847f563739b50c6577468e13182245bd228afeaa102408b71bbcd5520394445e6fa7",
          "sha256": "2fd5f9d7a5446f1c9125030c01f66e04716de2b258b4cbdd49dc114fcc41b197",
          "sha1": "4274e5ab93efe6d97eeb267ed3f040fcc4297f7d",
          "md5": "6aeec8135556768aa38509ddb348e91f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.2-sources.jar",
          "url": "numen-api-fabric-1.20.4-0.1.2-sources.jar",
          "size": 1068754,
          "sha512": "db0525dc05dc754ef4dc795145406f8aebcd7ad054fd73a97563a657f8f99b626c27b96caa81aaef42bd777f5172104fa47ba1d73dc414a8e11db2568ebd7bcf",
          "sha256": "cb2e30b075964dd6579ef9e5ff6fba5befb5b49f4025c69955d269aa2cc38357",
          "sha1": "448be7238e6c33b41ed38192e903335c6b5c13d0",
          "md5": "0d4f3cc934b01fc8a5f925a443fa58e6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "fabric",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-api-fabric-1.20.4-0.1.2-javadoc.jar",
          "url": "numen-api-fabric-1.20.4-0.1.2-javadoc.jar",
          "size": 1518766,
          "sha512": "b127736af990620625419da668a9a5153b8880d5cc98b40c9cf642f68d44c42547bea4a32fb6b56040fc844d1a9ef230361f2762e62ac70f3f30db12db31513e",
          "sha256": "ab69437348fb52b47403f89e986c7bdb125937265e38c66ceca670d2f0ca85ab",
          "sha1": "cf59dd7d5460ca19b18a494559660f6fd8bf54a2",
          "md5": "086ea3758c41e8d677e11fc2c889415c"
        }
      ]
    }
  ]
}
