{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dwinovo.numen",
    "module": "numen-neoforge-1.21.1",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.1",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.3.jar",
          "url": "numen-neoforge-1.21.1-0.1.3.jar",
          "size": 2633911,
          "sha512": "b9a19a660b45cb215707d8466335e574f61655f60ac2a999d28a6754964beeee279e446a089d024dd463f3d854ac1af31bae2525e3b2d2cc2c3c33d5704980cc",
          "sha256": "5e60dd459ff4f52ddd6aefda905d70fd64f823fcff8bdf234e26b798fcb1e000",
          "sha1": "052c441c66dd6d330eb00c0556d0885cd931f387",
          "md5": "7de7660fd8afc256adb6992bdaea3e80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.dwinovo.numen",
          "module": "numen-api-neoforge-1.21.1",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.3.jar",
          "url": "numen-neoforge-1.21.1-0.1.3.jar",
          "size": 2633911,
          "sha512": "b9a19a660b45cb215707d8466335e574f61655f60ac2a999d28a6754964beeee279e446a089d024dd463f3d854ac1af31bae2525e3b2d2cc2c3c33d5704980cc",
          "sha256": "5e60dd459ff4f52ddd6aefda905d70fd64f823fcff8bdf234e26b798fcb1e000",
          "sha1": "052c441c66dd6d330eb00c0556d0885cd931f387",
          "md5": "7de7660fd8afc256adb6992bdaea3e80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.3-sources.jar",
          "url": "numen-neoforge-1.21.1-0.1.3-sources.jar",
          "size": 1068662,
          "sha512": "4dafc498ef6e0407fd6a5064be1ddfed400920c112abeea7b65d9354af4d7e6ddb91073371daacda8f340886792cf4668a1976003788bae92a26cd96e6523099",
          "sha256": "6bbe2e200ad30ae31920ccbc2dc8267a0f54412a8a8ae5a797909237a3a72d87",
          "sha1": "c77cce93c6e4ed5f1d74e30d042d702bf2bef762",
          "md5": "3f41ff564debb891eee1c98eab27a8da"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.github.mcgradleconventions.loader": "neoforge",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "numen-neoforge-1.21.1-0.1.3-javadoc.jar",
          "url": "numen-neoforge-1.21.1-0.1.3-javadoc.jar",
          "size": 1535481,
          "sha512": "72f62b798d4f9b9358447bacc7f624fa789483c39f8c3a9b061dde09262480ed16e7e6c4babfb14666963ff7e64bc4fa31e7e1fdb66fb793f4fa06e7692a5393",
          "sha256": "1faf868f3bea69085ddec3f9148e1b00e067143e918299fafd500aeb84d9565e",
          "sha1": "a98d0d3cb7dfe2c59cdc5bdbf9d8dbac105bc561",
          "md5": "60c960b25b589303b9e064f02b27275a"
        }
      ]
    }
  ]
}
